/* WARNING: This file is automatically generated. Please edit the files in the /generation/commands directory. */
import { Command, Flags } from "@oclif/core"
import chalk from "chalk"
import { Output } from '../../output'
import { FreeClimbApi, FreeClimbResponse } from '../../freeclimb'
import * as Errors from '../../errors'
import { wrapJsonOutput, getFormatterForTopic } from '../../ui/format'
import { getOutputFormat } from '../../agent-config'
import { filterFieldsDeep, rejectControlChars, validateResourceId } from '../../validation'

export class callQueuesCreate extends Command {
    static description = ` Create a Queue within the specified account.`
    
    static flags = {
		alias: Flags.string({            char: "a",            description: "A description for this Queue. Max length is 64 characters.",             required: false,             }),
		maxSize: Flags.integer({            char: "M",            description: "Maximum number of Calls this queue can hold. Default is 1000. Maximum is 1000.",             required: false,             }),
		next: Flags.boolean({hidden: true}),
		json: Flags.boolean({description: 'Output as JSON. Auto-enabled when stdout is not a TTY or FREECLIMB_OUTPUT_FORMAT=json is set.', default: false}),
		fields: Flags.string({description: 'Comma-separated list of fields to include in the response. Limits output to protect context windows when used by agents.'}),
		"dry-run": Flags.boolean({description: 'Validate the request without executing it. Shows what would be sent to the API.', default: false}),
		help: Flags.help({char: 'h'}),
	}
    
    async run() {
        const out = new Output(this)
        const {flags} = (() => {
            try {
                return this.parse(callQueuesCreate)
            } catch(error) {
                const err = new Errors.ParseError(error)
                this.error(err.message, { exit: err.code })
            }
        })()
        const outputFormat = getOutputFormat(flags.json)
        if (flags.alias) { rejectControlChars(flags.alias, "alias") }
        if (flags["dry-run"]) {
            const dryRunOutput = {
                dryRun: true,
                method: "POST",
                endpoint: `Queues`,
                body: {
                    alias: flags.alias,
                    maxSize: flags.maxSize
                },
                
            }
            if (outputFormat === "json") {
                out.out(JSON.stringify(dryRunOutput, null, 2))
            } else {
                out.out(chalk.yellow("DRY RUN - No API call will be made"))
                out.out(JSON.stringify(dryRunOutput, null, 2))
            }
            return
        }
        const fcApi = new FreeClimbApi(`Queues`, true, this)
        const formatOutput = (data: any) => {
            const outputData = flags.fields ? filterFieldsDeep(data, flags.fields.split(",").map((f: string) => f.trim())) : data
            if (outputFormat === "json") {
                return JSON.stringify(wrapJsonOutput(outputData), null, 2)
            }
            const formatter = getFormatterForTopic("call-queues", "create")
            return formatter ? formatter(outputData) : JSON.stringify(outputData, null, 2)
        }
        const normalResponse = (response: FreeClimbResponse) => {
            if (response.status === 204) {
                if (outputFormat === "json") {
                    out.out(JSON.stringify(wrapJsonOutput(null, { command: "call-queues:create" }), null, 2))
                } else {
                    out.out(chalk.green("Received a success code from FreeClimb. There is no further output."))
                }
            } else if (response.data) {
                out.out(formatOutput(response.data))
            } else { throw new Errors.UndefinedResponseError() }
        }
        if(flags.next) {
            
                const error = new Errors.NoNextPage();
                this.error(error.message, { exit: error.code});
            
        }
        const belowRangeError = new Errors.OutOfRange("maxSize", 0, "greater")
const aboveRangeError = new Errors.OutOfRange("maxSize", 1000, "less")
if(flags.maxSize && flags.maxSize < 0) { this.error(belowRangeError.message, {exit: belowRangeError.code}) }
if(flags.maxSize && flags.maxSize > 1000) { this.error(aboveRangeError.message, {exit: aboveRangeError.code}) }
        
        await fcApi.apiCall("POST", {data: {
				alias: flags.alias,
				maxSize: flags.maxSize,
			},
		}, normalResponse)
    
    }
}
