/* WARNING: This file is automatically generated. Please edit the files in the /generation/commands directory. */
import { Args, Command, Flags } from "@oclif/core"
import chalk from "chalk"
import { Output } from '../../output.js'
import { FreeClimbApi, FreeClimbResponse } from '../../freeclimb.js'
import * as Errors from '../../errors.js'
import { wrapJsonOutput } from '../../ui/format.js'
import { getOutputFormat } from '../../agent-config.js'
import { extractQuietIds, filterFieldsDeep, rejectControlChars, validateResourceId } from '../../validation.js'

export class callQueuesList extends Command {
    static description = ` Retrieve a list of active Queues associated with the specified account.`
    static examples = [
        "<%= config.bin %> call-queues:list",
        "<%= config.bin %> call-queues:list --json",
        "<%= config.bin %> call-queues:list --quiet",
    ]
    static flags = {
		alias: Flags.string({            char: "a",            description: "Return only the Queue resources with aliases that exactly match this name.",             required: false,             }),
		next: Flags.boolean({char: 'n', description: 'Displays the next page of output.'}),
		json: Flags.boolean({description: 'Output as JSON. Auto-enabled when stdout is not a TTY or FREECLIMB_OUTPUT_FORMAT=json is set.', default: false}),
		quiet: Flags.boolean({description: 'Output only resource IDs, one per line. Useful for piping into other commands.', default: false}),
		fields: Flags.string({description: 'Comma-separated list of fields to include in the response. Limits output to protect context windows when used by agents.'}),
		help: Flags.help({char: 'h'}),
	}
    
    async run() {
        const out = new Output(this)
        const {flags} = await this.parse(callQueuesList)
        const outputFormat = getOutputFormat(flags.json)
        if (flags.alias) { rejectControlChars(flags.alias, "alias") }
        
        const fcApi = new FreeClimbApi(`Queues`, true, this)
        const formatOutput = (data: any) => {
            const outputData = flags.fields ? filterFieldsDeep(data, flags.fields.split(",").map((f: string) => f.trim())) : data
            if (outputFormat === "json") {
                return JSON.stringify(wrapJsonOutput(outputData), null, 2)
            }
            out.render(outputData, { topic: "call-queues", command: "list" })
            return null
        }
        const normalResponse = (response: FreeClimbResponse) => {
            if (response.status === 204) {
                if (flags.quiet) { return }
                if (outputFormat === "json") {
                    out.out(JSON.stringify(wrapJsonOutput(null, { command: "call-queues:list", request: { method: "GET", endpoint: `Queues` } }), null, 2))
                } else {
                    out.render(null, { topic: "call-queues", command: "list" })
                }
            } else if (response.data) {
                if (flags.quiet) {
                    const ids = extractQuietIds(response.data, "queueId")
                    if (ids) { out.out(ids) }
                    return
                }
                const result = formatOutput(response.data)
                if (result !== null) { out.out(result) }
            } else { throw new Errors.UndefinedResponseError() }
        }
        const nextResponse = (response: FreeClimbResponse) => {
            if (response.data) {
                if (flags.quiet) {
                    const ids = extractQuietIds(response.data, "queueId")
                    if (ids) { out.out(ids) }
                } else {
                    const result = formatOutput(response.data)
                    if (result !== null) { out.out(result) }
                }
            } else { throw new Errors.UndefinedResponseError() }
            if(out.next === null && !flags.quiet) {
                out.out("== You are on the last page of output. ==")
            }
        }
        
        if(flags.next) {
            if(out.next === undefined || out.next === "freeclimbUnnamedTest") {
                const error = new Errors.NoNextPage();
                this.error(error.message, { exit: error.code});
            
            }
            else {
                await fcApi.apiCall("GET", { params: {cursor: out.next} }, nextResponse)
            }
            return
        }
        
        
        
        await fcApi.apiCall("GET", {params: {
				alias: flags.alias,
			},
		}, normalResponse)
    
    }
}
