/* WARNING: This file is automatically generated. Please edit the files in the /generation/commands directory. */
import { Args, Command, Flags } from "@oclif/core"
import chalk from "chalk"
import { Output } from "../../output.js"
import { FreeClimbApi, FreeClimbResponse } from "../../freeclimb.js"
import * as Errors from "../../errors.js"
import { wrapJsonOutput, getFormatterForTopic } from "../../ui/format.js"

export class callsListCallLogs extends Command {
    static description = ` Retrieve all logs associated with the specified Call.`

    static flags = {
        next: Flags.boolean({ char: "n", description: "Displays the next page of output." }),
        json: Flags.boolean({ description: "Output as JSON (for scripting/agents)", default: false }),
        help: Flags.help({ char: "h" }),
    }

    static args = {
		callId: Args.string({description: "String that uniquely identifies this call resource.", required: false}),
	}

    async run() {
        const out = new Output(this)
        const { args, flags } = await this.parse(callsListCallLogs)
        const fcApi = new FreeClimbApi(`Calls/${args.callId}/Logs`, true, this)
        const normalResponse = (response: FreeClimbResponse) => {
            if (response.status === 204) {
                out.out(
                    chalk.green(
                        "Received a success code from FreeClimb. There is no further output."
                    )
                )
            } else if (response.data) {
                if (flags.json) {
                out.out(JSON.stringify(wrapJsonOutput(response.data), null, 2))
            } else {
                const formatter = getFormatterForTopic("calls", "list-call-logs")
                out.out(formatter ? formatter(response.data) : JSON.stringify(response.data, null, 2))
            }
            } else {
                throw new Errors.UndefinedResponseError()
            }
        }
        const nextResponse = (response: FreeClimbResponse) => {
            if (response.data) {
                if (flags.json) {
                out.out(JSON.stringify(wrapJsonOutput(response.data), null, 2))
            } else {
                const formatter = getFormatterForTopic("calls", "list-call-logs")
                out.out(formatter ? formatter(response.data) : JSON.stringify(response.data, null, 2))
            }
            } else {
                throw new Errors.UndefinedResponseError()
            }
            if (out.next === null) {
                out.out("== You are on the last page of output. ==")
            }
        }

        if (flags.next) {
            if (out.next === undefined || out.next === "freeclimbUnnamedTest") {
                const error = new Errors.NoNextPage()
                this.error(error.message, { exit: error.code })
            } else {
                await fcApi.apiCall("GET", { params: { cursor: out.next } }, nextResponse)
            }
            return
        }

        await fcApi.apiCall("GET", {}, normalResponse)
    }
}
