/* WARNING: This file is automatically generated. Please edit the files in the /generation/commands directory. */
import { Command, flags } from "@oclif/command"
import chalk from "chalk"
import { Output } from '../../output'
import { FreeClimbApi, FreeClimbResponse } from '../../freeclimb'
import * as Errors from '../../errors'
import { wrapJsonOutput, getFormatterForTopic } from '../../ui/format'
import { getOutputFormat } from '../../agent-config'
import { filterFieldsDeep, rejectControlChars, validateResourceId } from '../../validation'

export class callsList extends Command {
    static description = ` Retrieve a list of phone Calls made to and from the specified account, sorted from date created, newest to oldest.`
    
    static flags = {
		to: flags.string({            char: "T",            description: "Only show Calls to this phone number.",             required: false,             }),
		from: flags.string({            char: "f",            description: "Only show Calls from this phone number.",             required: false,             }),
		status: flags.string({            char: "S",            description: "Only show Calls currently in this status. May be queued, ringing, inProgress, canceled, completed, failed, busy, or noAnswer.",             required: false,             }),
		startTime: flags.string({            char: "s",            description: "Only show Calls that started at or after this time, given as YYYY-MM-DD hh:mm:ss.",             required: false,             }),
		endTime: flags.string({            char: "e",            description: "Only show Calls that ended at or before this time, given as YYYY-MM- DD hh:mm:ss.",             required: false,             }),
		parentCallId: flags.string({            char: "P",            description: "Only show Calls generated by the call with this ID.",             required: false,             }),
		active: flags.string({            char: "a",            description: "Flag defaults to false. Set true to list active calls.",             required: false,             options: ["true", "false"]}),
		next: flags.boolean({char: 'n', description: 'Displays the next page of output.'}),
		json: flags.boolean({description: 'Output as JSON. Auto-enabled when stdout is not a TTY or FREECLIMB_OUTPUT_FORMAT=json is set.', default: false}),
		fields: flags.string({description: 'Comma-separated list of fields to include in the response. Limits output to protect context windows when used by agents.'}),
		help: flags.help({char: 'h'}),
	}
    
    async run() {
        const out = new Output(this)
        const {flags} = (() => {
            try {
                return this.parse(callsList)
            } catch(error) {
                const err = new Errors.ParseError(error)
                this.error(err.message, { exit: err.code })
            }
        })()
        const outputFormat = getOutputFormat(flags.json)
        if (flags.parentCallId) { validateResourceId(flags.parentCallId, "parentCallId") }
        if (flags.to) { rejectControlChars(flags.to, "to") }
        if (flags.from) { rejectControlChars(flags.from, "from") }
        if (flags.status) { rejectControlChars(flags.status, "status") }
        if (flags.startTime) { rejectControlChars(flags.startTime, "startTime") }
        if (flags.endTime) { rejectControlChars(flags.endTime, "endTime") }
        
        const fcApi = new FreeClimbApi(`Calls`, true, this)
        const formatOutput = (data: any) => {
            const outputData = flags.fields ? filterFieldsDeep(data, flags.fields.split(",").map((f: string) => f.trim())) : data
            if (outputFormat === "json") {
                return JSON.stringify(wrapJsonOutput(outputData), null, 2)
            }
            const formatter = getFormatterForTopic("calls", "list")
            return formatter ? formatter(outputData) : JSON.stringify(outputData, null, 2)
        }
        const normalResponse = (response: FreeClimbResponse) => {
            if (response.status === 204) {
                if (outputFormat === "json") {
                    out.out(JSON.stringify(wrapJsonOutput(null, { command: "calls:list" }), null, 2))
                } else {
                    out.out(chalk.green("Received a success code from FreeClimb. There is no further output."))
                }
            } else if (response.data) {
                out.out(formatOutput(response.data))
            } else { throw new Errors.UndefinedResponseError() }
        }
        const nextResponse = (response: FreeClimbResponse) => {
            if (response.data) {
                out.out(formatOutput(response.data))
            } else { throw new Errors.UndefinedResponseError() }
            if(out.next === null) {
                out.out("== You are on the last page of output. ==")
            }
        }
        
        if(flags.next) {
            if(out.next === undefined || out.next === "freeclimbUnnamedTest") {
                const error = new Errors.NoNextPage();
                this.error(error.message, { exit: error.code});
            
            }
            else {
                await fcApi.apiCall("GET", { params: {cursor: out.next} }, nextResponse)
            }
            return
        }
        
        // flags.active === "true" sets active to the boolean representation of the flag
		const active = typeof flags.active  === "undefined" ? undefined : flags.active === "true"
        
        await fcApi.apiCall("GET", {params: {
				to: flags.to,
				from: flags.from,
				status: flags.status,
				startTime: flags.startTime,
				endTime: flags.endTime,
				parentCallId: flags.parentCallId,
				active: active,
			},
		}, normalResponse)
    
    }
}
