/* WARNING: This file is automatically generated. Please edit the files in the /generation/commands directory. */
import { Args, Command, Flags } from "@oclif/core"
import chalk from "chalk"
import { Output } from "../../output.js"
import { FreeClimbApi, FreeClimbResponse } from "../../freeclimb.js"
import * as Errors from "../../errors.js"
import { wrapJsonOutput } from "../../ui/format.js"
import { getOutputFormat } from "../../agent-config.js"
import {
    extractQuietIds,
    filterFieldsDeep,
    rejectControlChars,
    validateResourceId,
} from "../../validation.js"

export class callsUpdate extends Command {
    static description = ` Call hang up may take time. A 202 status code is returned if the hangup request was successfully queued by FreeClimb. Otherwise, an error code is returned. If successfully queued, the asynchronous callback for the result will occur after some time through the statusCallbackUrl.`
    static examples = [
        "<%= config.bin %> calls:update CA1234567890abcdef --status completed",
        "<%= config.bin %> calls:update CA1234567890abcdef --status completed --dry-run",
    ]

    static flags = {
        next: Flags.boolean({ hidden: true }),
        json: Flags.boolean({
            description:
                "Output as JSON. Auto-enabled when stdout is not a TTY or FREECLIMB_OUTPUT_FORMAT=json is set.",
            default: false,
        }),
        quiet: Flags.boolean({
            description:
                "Output only resource IDs, one per line. Useful for piping into other commands.",
            default: false,
        }),
        fields: Flags.string({
            description:
                "Comma-separated list of fields to include in the response. Limits output to protect context windows when used by agents.",
        }),
        "dry-run": Flags.boolean({
            description:
                "Validate the request without executing it. Shows what would be sent to the API.",
            default: false,
        }),
        help: Flags.help({ char: "h" }),
    }

    static args = {
        callId: Args.string({
            description: "String that uniquely identifies this call resource.",
            required: true,
        }),
        status: Args.string({
            description:
                "Either canceled or completed. Specifying canceled attempts to hang up calls that are queued without affecting calls already in progress. Specifying completed attempts to hang up a call already in progress.",
            required: true,
        }),
    }

    async run() {
        const out = new Output(this)
        const { args, flags } = await this.parse(callsUpdate)
        const outputFormat = getOutputFormat(flags.json)
        validateResourceId(args.callId, "callId")
        rejectControlChars(args.status, "status")
        if (flags["dry-run"]) {
            const dryRunOutput = {
                dryRun: true,
                method: "POST",
                endpoint: `Calls/${args.callId}`,
                body: {
                    status: args.status,
                },
            }
            if (outputFormat === "json") {
                out.out(JSON.stringify(dryRunOutput, null, 2))
            } else {
                out.out(chalk.yellow("DRY RUN - No API call will be made"))
                out.out(JSON.stringify(dryRunOutput, null, 2))
            }
            return
        }
        const fcApi = new FreeClimbApi(`Calls/${args.callId}`, true, this)
        const formatOutput = (data: any) => {
            const outputData = flags.fields
                ? filterFieldsDeep(
                      data,
                      flags.fields.split(",").map((f: string) => f.trim()),
                  )
                : data
            if (outputFormat === "json") {
                return JSON.stringify(wrapJsonOutput(outputData), null, 2)
            }
            out.render(outputData, { topic: "calls", command: "update" })
            return null
        }
        const normalResponse = (response: FreeClimbResponse) => {
            if (response.status === 204) {
                if (flags.quiet) {
                    return
                }
                if (outputFormat === "json") {
                    out.out(
                        JSON.stringify(
                            wrapJsonOutput(null, {
                                command: "calls:update",
                                request: {
                                    method: "POST",
                                    endpoint: `Calls/${args.callId}`,
                                    body: {
                                        status: args.status,
                                    },
                                },
                            }),
                            null,
                            2,
                        ),
                    )
                } else {
                    out.render(null, { topic: "calls", command: "update" })
                }
            } else if (response.data) {
                if (flags.quiet) {
                    const ids = extractQuietIds(response.data, "callId")
                    if (ids) {
                        out.out(ids)
                    }
                    return
                }
                const result = formatOutput(response.data)
                if (result !== null) {
                    out.out(result)
                }
            } else {
                throw new Errors.UndefinedResponseError()
            }
        }
        if (flags.next) {
            const error = new Errors.NoNextPage()
            this.error(error.message, { exit: error.code })
        }

        await fcApi.apiCall(
            "POST",
            {
                data: {
                    status: args.status,
                },
            },
            normalResponse,
        )
    }
}
