/* WARNING: This file is automatically generated. Please edit the files in the /generation/commands directory. */
import { Command, flags } from "@oclif/command"
import chalk from "chalk"
import { Output } from "../../output"
import { FreeClimbApi, FreeClimbResponse } from "../../freeclimb"
import * as Errors from "../../errors"
import { wrapJsonOutput, getFormatterForTopic } from "../../ui/format"
import { getOutputFormat } from "../../agent-config"
import { filterFieldsDeep, rejectControlChars, validateResourceId } from "../../validation"
import { sleep, calculateSinceTimestamp } from "../../tail"

let lastTime: number
let tailMax: number

export class logsFilter extends Command {
    static description = ` Returns the first page of Logs associated with the specified account.`

    static flags = {
        maxItem: flags.integer({
            char: "m",
            description: "Show only a certain number of the most recent logs on this page.",
        }),
        tail: flags.boolean({
            char: "t",
            description: "Polls the FreeClimb API to retrieve and display new logs as they occur.",
            default: false,
        }),
        sleep: flags.integer({
            char: "q",
            description:
                "Determines time waited between request for tail command. Defaults at 1 second.",
            default: 1000,
        }),
        since: flags.string({
            char: "Q",
            description:
                "Determines time frame of logs to be printed out before starting tail. Ex.2h9m",
            dependsOn: ["tail"],
        }),
        next: flags.boolean({ char: "n", description: "Displays the next page of output." }),
        json: flags.boolean({
            description:
                "Output as structured JSON. Also enabled via FREECLIMB_OUTPUT_FORMAT=json env var.",
            default: false,
        }),
        fields: flags.string({
            description:
                "Comma-separated list of fields to include in the response. Limits output to protect context windows when used by agents.",
        }),
        "dry-run": flags.boolean({
            description:
                "Validate the request without executing it. Shows what would be sent to the API.",
            default: false,
        }),
        help: flags.help({ char: "h" }),
    }

    static args = [
        { name: "pql", description: "The filter query for retrieving logs.", required: true },
    ]

    async run() {
        const out = new Output(this)
        const { args, flags } = (() => {
            try {
                return this.parse(logsFilter)
            } catch (error) {
                const err = new Errors.ParseError(error)
                this.error(err.message, { exit: err.code })
            }
        })()
        const outputFormat = getOutputFormat(flags.json)
        rejectControlChars(args.pql, "pql")
        if (flags["dry-run"]) {
            const dryRunOutput = {
                dryRun: true,
                method: "POST",
                endpoint: `Logs`,
                body: {
                    pql: args.pql,
                },
            }
            if (outputFormat === "json") {
                out.out(JSON.stringify(dryRunOutput, null, 2))
            } else {
                out.out(chalk.yellow("DRY RUN - No API call will be made"))
                out.out(JSON.stringify(dryRunOutput, null, 2))
            }
            return
        }
        const fcApi = new FreeClimbApi(`Logs`, true, this)
        const formatOutput = (data: any) => {
            const outputData = flags.fields
                ? filterFieldsDeep(
                      data,
                      flags.fields.split(",").map((f: string) => f.trim())
                  )
                : data
            if (outputFormat === "json") {
                return JSON.stringify(wrapJsonOutput(outputData), null, 2)
            }
            const formatter = getFormatterForTopic("logs", "filter")
            return formatter ? formatter(outputData) : JSON.stringify(outputData, null, 2)
        }
        const normalResponse = (response: FreeClimbResponse) => {
            if (response.status === 204) {
                if (outputFormat === "json") {
                    out.out(
                        JSON.stringify(wrapJsonOutput(null, { command: "logs:filter" }), null, 2)
                    )
                } else {
                    out.out(
                        chalk.green(
                            "Received a success code from FreeClimb. There is no further output."
                        )
                    )
                }
            } else if (response.data) {
                const processedData = flags.maxItem
                    ? { ...response.data, logs: response.data.logs.splice(0, flags.maxItem) }
                    : response.data
                out.out(formatOutput(processedData))
            } else {
                throw new Errors.UndefinedResponseError()
            }
        }

        const tailResponse = (response: FreeClimbResponse) => {
            if (response.data.end !== 0) {
                lastTime = response.data.logs[0].timestamp
                out.out(JSON.stringify(response.data.logs.splice(0, tailMax).reverse(), null, 2))
            }
        }

        const nextResponse = (response: FreeClimbResponse) => {
            if (response.data) {
                const processedData = flags.maxItem
                    ? { ...response.data, logs: response.data.logs.splice(0, flags.maxItem) }
                    : response.data
                out.out(formatOutput(processedData))
            } else {
                throw new Errors.UndefinedResponseError()
            }
            if (out.next === null) {
                out.out("== You are on the last page of output. ==")
            }
        }

        if (flags.next) {
            if (out.next === undefined || out.next === "freeclimbUnnamedTest") {
                const error = new Errors.NoNextPage()
                this.error(error.message, { exit: error.code })
            } else {
                await fcApi.apiCall("GET", { params: { cursor: out.next } }, nextResponse)
            }
            return
        }
        if (args.pql.includes("'")) {
            this.warn(
                chalk.yellow(
                    "A single quote has been detected in your pql. Keep in mind that all strings must be encapsulated by double quotes for the pql to be valid. If this was a mistake, please rerun the command with your rewritten pql. The command will now run."
                )
            )
        }

        if (flags.tail) {
            lastTime = 0
            if (args.pql.includes("timestamp")) {
                const err = new Errors.NoTimestamp()
                this.error(err.message, { exit: err.code })
            }

            if (flags.since) {
                const currentTime = Date.now() * 1000
                const sinceTimestamp = (() => {
                    try {
                        return calculateSinceTimestamp(flags.since)
                    } catch (error) {
                        const err = new Errors.SinceFormatError(error)
                        this.error(err.message, { exit: err.code })
                    }
                })()
                lastTime = currentTime - sinceTimestamp
            }
            tailMax = flags.maxItem ? flags.maxItem : 100
            while (flags.tail) {
                await fcApi.apiCall(
                    "POST",
                    {
                        data: {
                            pql: `${args.pql} AND timestamp>${lastTime}`,
                        },
                    },
                    tailResponse
                )
                await sleep(flags.sleep)
                tailMax = 100
            }
        } else {
            await fcApi.apiCall(
                "POST",
                {
                    data: {
                        pql: args.pql,
                    },
                },
                normalResponse
            )
        }
    }
}
