/* WARNING: This file is automatically generated. Please edit the files in the /generation/commands directory. */
import { Command, flags } from "@oclif/command"
import chalk from "chalk"
import { Output } from '../../output'
import { FreeClimbApi, FreeClimbResponse } from '../../freeclimb'
import * as Errors from '../../errors'
import { wrapJsonOutput, getFormatterForTopic } from '../../ui/format'
import { getOutputFormat } from '../../agent-config'
import { filterFieldsDeep, rejectControlChars, validateResourceId } from '../../validation'

export class smsList extends Command {
    static description = ` Retrieve a list of SMS Messages made to and from the specified Account, sorted from latest created to oldest.`
    
    static flags = {
		to: flags.string({            char: "T",            description: "Only show Messages to this phone number.",             required: false,             }),
		from: flags.string({            char: "f",            description: "Only show Messages from this phone number.",             required: false,             }),
		beginTime: flags.string({            char: "b",            description: "Only show Messages sent at or after this time (GMT), given as YYYY-MM-DD hh:mm:ss.",             required: false,             }),
		endTime: flags.string({            char: "e",            description: "Only show messages sent at or before this time (GMT), given as YYYY-MM-DD hh:mm.",             required: false,             }),
		direction: flags.string({            char: "d",            description: "Either inbound or outbound. Only show Messages that were either sent from or received by FreeClimb.",             required: false,             }),
		next: flags.boolean({char: 'n', description: 'Displays the next page of output.'}),
		json: flags.boolean({description: 'Output as JSON. Auto-enabled when stdout is not a TTY or FREECLIMB_OUTPUT_FORMAT=json is set.', default: false}),
		fields: flags.string({description: 'Comma-separated list of fields to include in the response. Limits output to protect context windows when used by agents.'}),
		help: flags.help({char: 'h'}),
	}
    
    async run() {
        const out = new Output(this)
        const {flags} = (() => {
            try {
                return this.parse(smsList)
            } catch(error) {
                const err = new Errors.ParseError(error)
                this.error(err.message, { exit: err.code })
            }
        })()
        const outputFormat = getOutputFormat(flags.json)
        if (flags.to) { rejectControlChars(flags.to, "to") }
        if (flags.from) { rejectControlChars(flags.from, "from") }
        if (flags.beginTime) { rejectControlChars(flags.beginTime, "beginTime") }
        if (flags.endTime) { rejectControlChars(flags.endTime, "endTime") }
        if (flags.direction) { rejectControlChars(flags.direction, "direction") }
        
        const fcApi = new FreeClimbApi(`Messages`, true, this)
        const formatOutput = (data: any) => {
            const outputData = flags.fields ? filterFieldsDeep(data, flags.fields.split(",").map((f: string) => f.trim())) : data
            if (outputFormat === "json") {
                return JSON.stringify(wrapJsonOutput(outputData), null, 2)
            }
            const formatter = getFormatterForTopic("sms", "list")
            return formatter ? formatter(outputData) : JSON.stringify(outputData, null, 2)
        }
        const normalResponse = (response: FreeClimbResponse) => {
            if (response.status === 204) {
                if (outputFormat === "json") {
                    out.out(JSON.stringify(wrapJsonOutput(null, { command: "sms:list" }), null, 2))
                } else {
                    out.out(chalk.green("Received a success code from FreeClimb. There is no further output."))
                }
            } else if (response.data) {
                out.out(formatOutput(response.data))
            } else { throw new Errors.UndefinedResponseError() }
        }
        const nextResponse = (response: FreeClimbResponse) => {
            if (response.data) {
                out.out(formatOutput(response.data))
            } else { throw new Errors.UndefinedResponseError() }
            if(out.next === null) {
                out.out("== You are on the last page of output. ==")
            }
        }
        
        if(flags.next) {
            if(out.next === undefined || out.next === "freeclimbUnnamedTest") {
                const error = new Errors.NoNextPage();
                this.error(error.message, { exit: error.code});
            
            }
            else {
                await fcApi.apiCall("GET", { params: {cursor: out.next} }, nextResponse)
            }
            return
        }
        
        await fcApi.apiCall("GET", {params: {
				to: flags.to,
				from: flags.from,
				beginTime: flags.beginTime,
				endTime: flags.endTime,
				direction: flags.direction,
			},
		}, normalResponse)
    
    }
}
