/* WARNING: This file is automatically generated. Please edit the files in the /generation/commands directory. */
import { Args, Command, Flags } from "@oclif/core"
import chalk from "chalk"
import { Output } from "../../output.js"
import { FreeClimbApi, FreeClimbResponse } from "../../freeclimb.js"
import * as Errors from "../../errors.js"
import { wrapJsonOutput } from "../../ui/format.js"
import { getOutputFormat } from "../../agent-config.js"
import {
    extractQuietIds,
    filterFieldsDeep,
    rejectControlChars,
    validateResourceId,
} from "../../validation.js"

export class smsList extends Command {
    static description = ` Retrieve a list of SMS Messages made to and from the specified Account, sorted from latest created to oldest.`
    static examples = [
        "<%= config.bin %> sms:list",
        "<%= config.bin %> sms:list --json",
        "<%= config.bin %> sms:list --quiet",
        "<%= config.bin %> sms:list --fields messageId,from,to,status",
    ]

    static flags = {
        to: Flags.string({
            char: "T",
            description: "Only show Messages to this phone number.",
            required: false,
        }),
        from: Flags.string({
            char: "f",
            description: "Only show Messages from this phone number.",
            required: false,
        }),
        beginTime: Flags.string({
            char: "b",
            description:
                "Only show Messages sent at or after this time (GMT), given as YYYY-MM-DD hh:mm:ss.",
            required: false,
        }),
        endTime: Flags.string({
            char: "e",
            description:
                "Only show messages sent at or before this time (GMT), given as YYYY-MM-DD hh:mm.",
            required: false,
        }),
        direction: Flags.string({
            char: "d",
            description:
                "Either inbound or outbound. Only show Messages that were either sent from or received by FreeClimb.",
            required: false,
        }),
        next: Flags.boolean({ char: "n", description: "Displays the next page of output." }),
        json: Flags.boolean({
            description:
                "Output as JSON. Auto-enabled when stdout is not a TTY or FREECLIMB_OUTPUT_FORMAT=json is set.",
            default: false,
        }),
        quiet: Flags.boolean({
            description:
                "Output only resource IDs, one per line. Useful for piping into other commands.",
            default: false,
        }),
        fields: Flags.string({
            description:
                "Comma-separated list of fields to include in the response. Limits output to protect context windows when used by agents.",
        }),
        help: Flags.help({ char: "h" }),
    }

    async run() {
        const out = new Output(this)
        const { flags } = await this.parse(smsList)
        const outputFormat = getOutputFormat(flags.json)
        if (flags.to) {
            rejectControlChars(flags.to, "to")
        }
        if (flags.from) {
            rejectControlChars(flags.from, "from")
        }
        if (flags.beginTime) {
            rejectControlChars(flags.beginTime, "beginTime")
        }
        if (flags.endTime) {
            rejectControlChars(flags.endTime, "endTime")
        }
        if (flags.direction) {
            rejectControlChars(flags.direction, "direction")
        }

        const fcApi = new FreeClimbApi(`Messages`, true, this)
        const formatOutput = (data: any) => {
            const outputData = flags.fields
                ? filterFieldsDeep(
                      data,
                      flags.fields.split(",").map((f: string) => f.trim()),
                  )
                : data
            if (outputFormat === "json") {
                return JSON.stringify(wrapJsonOutput(outputData), null, 2)
            }
            out.render(outputData, { topic: "sms", command: "list" })
            return null
        }
        const normalResponse = (response: FreeClimbResponse) => {
            if (response.status === 204) {
                if (flags.quiet) {
                    return
                }
                if (outputFormat === "json") {
                    out.out(
                        JSON.stringify(
                            wrapJsonOutput(null, {
                                command: "sms:list",
                                request: { method: "GET", endpoint: `Messages` },
                            }),
                            null,
                            2,
                        ),
                    )
                } else {
                    out.render(null, { topic: "sms", command: "list" })
                }
            } else if (response.data) {
                if (flags.quiet) {
                    const ids = extractQuietIds(response.data, "messageId")
                    if (ids) {
                        out.out(ids)
                    }
                    return
                }
                const result = formatOutput(response.data)
                if (result !== null) {
                    out.out(result)
                }
            } else {
                throw new Errors.UndefinedResponseError()
            }
        }
        const nextResponse = (response: FreeClimbResponse) => {
            if (response.data) {
                if (flags.quiet) {
                    const ids = extractQuietIds(response.data, "messageId")
                    if (ids) {
                        out.out(ids)
                    }
                } else {
                    const result = formatOutput(response.data)
                    if (result !== null) {
                        out.out(result)
                    }
                }
            } else {
                throw new Errors.UndefinedResponseError()
            }
            if (out.next === null && !flags.quiet) {
                out.out("== You are on the last page of output. ==")
            }
        }

        if (flags.next) {
            if (out.next === undefined || out.next === "freeclimbUnnamedTest") {
                const error = new Errors.NoNextPage()
                this.error(error.message, { exit: error.code })
            } else {
                await fcApi.apiCall("GET", { params: { cursor: out.next } }, nextResponse)
            }
            return
        }

        await fcApi.apiCall(
            "GET",
            {
                params: {
                    to: flags.to,
                    from: flags.from,
                    beginTime: flags.beginTime,
                    endTime: flags.endTime,
                    direction: flags.direction,
                },
            },
            normalResponse,
        )
    }
}
