/* WARNING: This file is automatically generated. Please edit the files in the /generation/commands directory. */
import { Command, Flags, Args } from "@oclif/core"
import chalk from "chalk"
import { Output } from "../../output.js"
import { FreeClimbApi, FreeClimbResponse } from "../../freeclimb.js"
import * as Errors from "../../errors.js"

export class smsSend extends Command {
    static description = `This command allows you to send a sms message.`

    static flags = {
        notificationUrl: Flags.string({
            char: "n",
            description:
                "When the Message changes status, this URL is invoked using HTTP POST with the messageStatus parameters. Note: This is a notification only; any PerCL returned is ignored.",
            required: false,
        }),
        next: Flags.boolean({ hidden: true }),
    }

    static args = {
        from: Args.string({
            description:
                "Phone number to use as the sender. This must be an incoming phone number that you have purchased from FreeClimb.",
            required: true,
        }),
        to: Args.string({
            description:
                "Phone number to receive the message. Must be within FreeClimb's service area. For trial accounts, must be a Verified Number.",
            required: true,
        }),
        text: Args.string({ description: "Text contained in the message.", required: true }),
    }

    async run() {
        const out = new Output(this)
        const { args, flags } = await this.parse(smsSend)
        const fcApi = new FreeClimbApi(`Messages`, true, this)
        const normalResponse = (response: FreeClimbResponse) => {
            if (response.status === 204) {
                out.out(
                    chalk.green(
                        "Received a success code from FreeClimb. There is no further output.",
                    ),
                )
            } else if (response.data) {
                out.out(JSON.stringify(response.data, null, 2))
            } else {
                throw new Errors.UndefinedResponseError()
            }
        }
        if (flags.next) {
            const error = new Errors.NoNextPage()
            this.error(error.message, { exit: error.code })
        }

        await fcApi.apiCall(
            "POST",
            {
                data: {
                    from: args.from,
                    to: args.to,
                    text: args.text,
                    notificationUrl: flags.notificationUrl,
                },
            },
            normalResponse,
        )
    }
}
