/* WARNING: This file is automatically generated. Please edit the files in the /generation/tests directory. */
import { expect } from "chai"
import { runCommand } from "@oclif/test"
import nock from "nock"
import { cred } from "../../src/credentials.js"

const applicationId = "userInput-applicationId"

describe("applications:update Data Test", function () {
    const testJson = {
        message: "Response from server",
    }

    const nockServerResponse = `{
  "message": "Response from server"
}`

    it("Test all required paramaters", async () => {
        nock("https://www.freeclimb.com")
            .post(`/apiserver/Accounts/${await cred.accountId}/Applications/${applicationId}`, {})
            .query({})
            .reply(200, testJson)
        const { stdout, stderr } = await runCommand([
            "applications:update",
            "userInput-applicationId",
        ])
        expect(stdout).to.contain(nockServerResponse)
    })

    const testJsonErrorNoSuggestion = {
        code: 2,
        message: "Method Not Allowed",
        url: "https://docs.freeclimb.com/reference/error-and-warning-dictionary#2",
        details: {},
    }

    const nockServerResponseErrorNoSuggestion = `starting test`

    it("Test Freeclimb Api error repsonce is process correctly without a suggestion", async () => {
        nock("https://www.freeclimb.com")
            .post(`/apiserver/Accounts/${await cred.accountId}/Applications/${applicationId}`, {})
            .query({})
            .reply(500, testJsonErrorNoSuggestion)
        const { error } = await runCommand(["applications:update", "userInput-applicationId"])
        expect(error?.oclif?.exit).to.equal(3)
    })

    it("Sends API requests to the base URL from an environment variable", async () => {
        const orig_FREECLIMB_CLI_BASE_URL = process.env.FREECLIMB_CLI_BASE_URL
        process.env.FREECLIMB_CLI_BASE_URL = "https://user-custom-domain.example.com/apiserver"
        nock("https://user-custom-domain.example.com")
            .post(`/apiserver/Accounts/${await cred.accountId}/Applications/${applicationId}`, {})
            .query({})
            .reply(200, testJson)
        try {
            const { stdout, stderr } = await runCommand([
                "applications:update",
                "userInput-applicationId",
            ])
            expect(stdout).to.contain(nockServerResponse)
        } finally {
            if (orig_FREECLIMB_CLI_BASE_URL === undefined) delete process.env.FREECLIMB_CLI_BASE_URL
            else process.env.FREECLIMB_CLI_BASE_URL = orig_FREECLIMB_CLI_BASE_URL
        }
    })

    const testJsonErrorWithSuggestion = {
        code: 50,
        message: "Unauthorized To Make Request",
        url: "https://docs.freeclimb.com/reference/error-and-warning-dictionary#50",
        details: {},
    }

    const nockServerResponseErrorWithSuggestion = `starting test`

    it("Test Freeclimb Api error repsonce is process correctly with a suggestion", async () => {
        nock("https://www.freeclimb.com")
            .post(`/apiserver/Accounts/${await cred.accountId}/Applications/${applicationId}`, {})
            .query({})
            .reply(500, testJsonErrorWithSuggestion)
        const { error } = await runCommand(["applications:update", "userInput-applicationId"])
        expect(error?.oclif?.exit).to.equal(3)
    })

    it("Test parse error gets triggered when there is an additional argument", async () => {
        const { error } = await runCommand([
            "applications:update",
            "userInput-applicationId",
            "additionalArguments",
        ])
        expect(error?.oclif?.exit).to.equal(2)
    })

    it("Test error resulting in an unreadable response", async () => {
        nock("https://www.freeclimb.com")
            .post(`/apiserver/Accounts/${await cred.accountId}/Applications/${applicationId}`, {})
            .query({})
            .reply(200, undefined)
        const { error } = await runCommand(["applications:update", "userInput-applicationId"])
        expect(error?.oclif?.exit).to.equal(3)
    })

    it("testing all body parameters together and required query are sent through with request", async () => {
        nock("https://www.freeclimb.com")
            .post(`/apiserver/Accounts/${await cred.accountId}/Applications/${applicationId}`, {
                alias: "userInput-alias",
                voiceUrl: "userInput-voiceUrl",
                voiceFallbackUrl: "userInput-voiceFallbackUrl",
                callConnectUrl: "userInput-callConnectUrl",
                statusCallbackUrl: "userInput-statusCallbackUrl",
                smsUrl: "userInput-smsUrl",
                smsFallbackUrl: "userInput-smsFallbackUrl",
            })
            .query({})
            .reply(200, testJson)
        const { stdout, stderr } = await runCommand([
            "applications:update",
            "userInput-applicationId",
            "--alias",
            "userInput-alias",
            "--voiceUrl",
            "userInput-voiceUrl",
            "--voiceFallbackUrl",
            "userInput-voiceFallbackUrl",
            "--callConnectUrl",
            "userInput-callConnectUrl",
            "--statusCallbackUrl",
            "userInput-statusCallbackUrl",
            "--smsUrl",
            "userInput-smsUrl",
            "--smsFallbackUrl",
            "userInput-smsFallbackUrl",
        ])
        expect(stdout).to.contain(nockServerResponse)
    })

    describe("applications:update body param flags", function () {
        it("required params and a body param is sent through with request-alias", async () => {
            nock("https://www.freeclimb.com")
                .post(`/apiserver/Accounts/${await cred.accountId}/Applications/${applicationId}`, {
                    alias: "userInput-alias",
                })
                .query({})
                .reply(200, testJson)
            const { stdout, stderr } = await runCommand([
                "applications:update",
                "userInput-applicationId",
                "--alias",
                "userInput-alias",
            ])
            expect(stdout).to.contain(nockServerResponse)
        })

        it("required params and a body param is sent through with request-voiceUrl", async () => {
            nock("https://www.freeclimb.com")
                .post(`/apiserver/Accounts/${await cred.accountId}/Applications/${applicationId}`, {
                    voiceUrl: "userInput-voiceUrl",
                })
                .query({})
                .reply(200, testJson)
            const { stdout, stderr } = await runCommand([
                "applications:update",
                "userInput-applicationId",
                "--voiceUrl",
                "userInput-voiceUrl",
            ])
            expect(stdout).to.contain(nockServerResponse)
        })

        it("required params and a body param is sent through with request-voiceFallbackUrl", async () => {
            nock("https://www.freeclimb.com")
                .post(`/apiserver/Accounts/${await cred.accountId}/Applications/${applicationId}`, {
                    voiceFallbackUrl: "userInput-voiceFallbackUrl",
                })
                .query({})
                .reply(200, testJson)
            const { stdout, stderr } = await runCommand([
                "applications:update",
                "userInput-applicationId",
                "--voiceFallbackUrl",
                "userInput-voiceFallbackUrl",
            ])
            expect(stdout).to.contain(nockServerResponse)
        })

        it("required params and a body param is sent through with request-callConnectUrl", async () => {
            nock("https://www.freeclimb.com")
                .post(`/apiserver/Accounts/${await cred.accountId}/Applications/${applicationId}`, {
                    callConnectUrl: "userInput-callConnectUrl",
                })
                .query({})
                .reply(200, testJson)
            const { stdout, stderr } = await runCommand([
                "applications:update",
                "userInput-applicationId",
                "--callConnectUrl",
                "userInput-callConnectUrl",
            ])
            expect(stdout).to.contain(nockServerResponse)
        })

        it("required params and a body param is sent through with request-statusCallbackUrl", async () => {
            nock("https://www.freeclimb.com")
                .post(`/apiserver/Accounts/${await cred.accountId}/Applications/${applicationId}`, {
                    statusCallbackUrl: "userInput-statusCallbackUrl",
                })
                .query({})
                .reply(200, testJson)
            const { stdout, stderr } = await runCommand([
                "applications:update",
                "userInput-applicationId",
                "--statusCallbackUrl",
                "userInput-statusCallbackUrl",
            ])
            expect(stdout).to.contain(nockServerResponse)
        })

        it("required params and a body param is sent through with request-smsUrl", async () => {
            nock("https://www.freeclimb.com")
                .post(`/apiserver/Accounts/${await cred.accountId}/Applications/${applicationId}`, {
                    smsUrl: "userInput-smsUrl",
                })
                .query({})
                .reply(200, testJson)
            const { stdout, stderr } = await runCommand([
                "applications:update",
                "userInput-applicationId",
                "--smsUrl",
                "userInput-smsUrl",
            ])
            expect(stdout).to.contain(nockServerResponse)
        })

        it("required params and a body param is sent through with request-smsFallbackUrl", async () => {
            nock("https://www.freeclimb.com")
                .post(`/apiserver/Accounts/${await cred.accountId}/Applications/${applicationId}`, {
                    smsFallbackUrl: "userInput-smsFallbackUrl",
                })
                .query({})
                .reply(200, testJson)
            const { stdout, stderr } = await runCommand([
                "applications:update",
                "userInput-applicationId",
                "--smsFallbackUrl",
                "userInput-smsFallbackUrl",
            ])
            expect(stdout).to.contain(nockServerResponse)
        })
    })

    describe("applications:update next flag test", function () {
        it("Tests return of Exit Code 3 when flag next is not available", async () => {
            const orig_FREECLIMB_APPLICATIONS_UPDATE_NEXT =
                process.env.FREECLIMB_APPLICATIONS_UPDATE_NEXT
            delete process.env.FREECLIMB_APPLICATIONS_UPDATE_NEXT
            nock("https://www.freeclimb.com")
                .post(
                    `/apiserver/Accounts/${await cred.accountId}/Applications/${applicationId}`,
                    {},
                )
                .query({})
                .reply(200, testJson)
            try {
                await runCommand(["applications:update", "userInput-applicationId"])
                const { error } = await runCommand([
                    "applications:update",
                    "userInput-applicationId",
                    "--next",
                ])
                expect(error?.oclif?.exit).to.equal(3)
            } finally {
                if (orig_FREECLIMB_APPLICATIONS_UPDATE_NEXT === undefined)
                    delete process.env.FREECLIMB_APPLICATIONS_UPDATE_NEXT
                else
                    process.env.FREECLIMB_APPLICATIONS_UPDATE_NEXT =
                        orig_FREECLIMB_APPLICATIONS_UPDATE_NEXT
            }
        })
    })
})

describe("applications:update Status Test", function () {
    const testJsonStatus = ""

    const statusResponse = `Received a success code from FreeClimb. There is no further output.
`

    it("Test all required paramaters", async () => {
        nock("https://www.freeclimb.com")
            .post(`/apiserver/Accounts/${await cred.accountId}/Applications/${applicationId}`, {})
            .query({})
            .reply(204, testJsonStatus)
        const { stdout, stderr } = await runCommand([
            "applications:update",
            "userInput-applicationId",
        ])
        expect(stdout).to.contain(statusResponse)
    })
})
