/* WARNING: This file is automatically generated. Please edit the files in the /generation/tests directory. */
import { expect } from "chai"
import nock from "nock"
import { runCommand } from "@oclif/test"

describe("available-numbers:list Data Test", function () {
    const testJson = {
        message: "Response from server",
    }

    const nockServerResponse = `{
  "message": "Response from server"
}`

    afterEach(() => {
        nock.cleanAll()
    })

    it("Test all required paramaters", async () => {
        nock("https://www.freeclimb.com")
            .get(`/apiserver/AvailablePhoneNumbers`)
            .query({})
            .reply(200, testJson)
        const { stdout } = await runCommand(["available-numbers:list"])
        expect(stdout).to.contain(nockServerResponse)
    })

    it("Test Freeclimb Api error repsonce is process correctly without a suggestion", async () => {
        const testJsonErrorNoSuggestion = {
            code: 2,
            message: "Method Not Allowed",
            url: "https://docs.freeclimb.com/reference/error-and-warning-dictionary#2",
            details: {},
        }
        nock("https://www.freeclimb.com")
            .get(`/apiserver/AvailablePhoneNumbers`)
            .query({})
            .reply(500, testJsonErrorNoSuggestion)
        const { error } = await runCommand(["available-numbers:list"])
        expect(error?.oclif?.exit).to.equal(3)
    })

    it("Sends API requests to the base URL from an environment variable", async () => {
        nock("https://user-custom-domain.example.com")
            .get(`/apiserver/AvailablePhoneNumbers`)
            .query({})
            .reply(200, testJson)
        const orig = process.env.FREECLIMB_CLI_BASE_URL
        process.env.FREECLIMB_CLI_BASE_URL = "https://user-custom-domain.example.com/apiserver"
        try {
            const { stdout } = await runCommand(["available-numbers:list"])
            expect(stdout).to.contain(nockServerResponse)
        } finally {
            if (orig !== undefined) process.env.FREECLIMB_CLI_BASE_URL = orig
            else delete process.env.FREECLIMB_CLI_BASE_URL
        }
    })

    it("Test Freeclimb Api error repsonce is process correctly with a suggestion", async () => {
        const testJsonErrorWithSuggestion = {
            code: 50,
            message: "Unauthorized To Make Request",
            url: "https://docs.freeclimb.com/reference/error-and-warning-dictionary#50",
            details: {},
        }
        nock("https://www.freeclimb.com")
            .get(`/apiserver/AvailablePhoneNumbers`)
            .query({})
            .reply(500, testJsonErrorWithSuggestion)
        const { error } = await runCommand(["available-numbers:list"])
        expect(error?.oclif?.exit).to.equal(3)
    })

    it("Test parse error gets triggered when there is an additional argument", async () => {
        const { error } = await runCommand(["available-numbers:list", "additionalArguments"])
        expect(error?.oclif?.exit).to.equal(2)
    })

    it("Test error resulting in an unreadable response", async () => {
        nock("https://www.freeclimb.com")
            .get(`/apiserver/AvailablePhoneNumbers`)
            .query({})
            .reply(200, undefined)
        const { error } = await runCommand(["available-numbers:list"])
        expect(error?.oclif?.exit).to.equal(3)
    })

    it("testing all query parameters and required body are sent through with request", async () => {
        nock("https://www.freeclimb.com")
            .get(`/apiserver/AvailablePhoneNumbers`)
            .query({
                alias: "123-456-7890",
                country: "userInput-country",
                region: "userInput-region",
                smsEnabled: true,
                voiceEnabled: true,
                phoneNumber: "userInput-phoneNumber",
            })
            .reply(200, testJson)
        const { stdout } = await runCommand([
            "available-numbers:list",
            "--alias",
            "123-456-7890",
            "--country",
            "userInput-country",
            "--region",
            "userInput-region",
            "--smsEnabled",
            "true",
            "--voiceEnabled",
            "true",
            "--phoneNumber",
            "userInput-phoneNumber",
        ])
        expect(stdout).to.contain(nockServerResponse)
    })

    describe("available-numbers:list query param flags", function () {
        afterEach(() => {
            nock.cleanAll()
        })

        it("required params and a query param is sent through with request-alias", async () => {
            nock("https://www.freeclimb.com")
                .get(`/apiserver/AvailablePhoneNumbers`)
                .query({ alias: "123-456-7890" })
                .reply(200, testJson)
            const { stdout } = await runCommand([
                "available-numbers:list",
                "--alias",
                "123-456-7890",
            ])
            expect(stdout).to.contain(nockServerResponse)
        })

        it("test that an incorrectly formated alias is responds with a warning", async () => {
            nock("https://www.freeclimb.com")
                .get(`/apiserver/AvailablePhoneNumbers`)
                .query({ alias: "123-456-789" })
                .reply(200, testJson)
            const { stdout } = await runCommand([
                "available-numbers:list",
                "--alias",
                "123-456-789",
            ])
            expect(stdout).to.be.a("string")
        })

        it("required params and a query param is sent through with request-country", async () => {
            nock("https://www.freeclimb.com")
                .get(`/apiserver/AvailablePhoneNumbers`)
                .query({ country: "userInput-country" })
                .reply(200, testJson)
            const { stdout } = await runCommand([
                "available-numbers:list",
                "--country",
                "userInput-country",
            ])
            expect(stdout).to.contain(nockServerResponse)
        })

        it("required params and a query param is sent through with request-region", async () => {
            nock("https://www.freeclimb.com")
                .get(`/apiserver/AvailablePhoneNumbers`)
                .query({ region: "userInput-region" })
                .reply(200, testJson)
            const { stdout } = await runCommand([
                "available-numbers:list",
                "--region",
                "userInput-region",
            ])
            expect(stdout).to.contain(nockServerResponse)
        })

        it("required params and a query param is sent through with request-smsEnabled", async () => {
            nock("https://www.freeclimb.com")
                .get(`/apiserver/AvailablePhoneNumbers`)
                .query({ smsEnabled: true })
                .reply(200, testJson)
            const { stdout } = await runCommand([
                "available-numbers:list",
                "--smsEnabled",
                "true",
            ])
            expect(stdout).to.contain(nockServerResponse)
        })

        it("required params and a query param is sent through with request-voiceEnabled", async () => {
            nock("https://www.freeclimb.com")
                .get(`/apiserver/AvailablePhoneNumbers`)
                .query({ voiceEnabled: true })
                .reply(200, testJson)
            const { stdout } = await runCommand([
                "available-numbers:list",
                "--voiceEnabled",
                "true",
            ])
            expect(stdout).to.contain(nockServerResponse)
        })

        it("required params and a query param is sent through with request-phoneNumber", async () => {
            nock("https://www.freeclimb.com")
                .get(`/apiserver/AvailablePhoneNumbers`)
                .query({ phoneNumber: "userInput-phoneNumber" })
                .reply(200, testJson)
            const { stdout } = await runCommand([
                "available-numbers:list",
                "--phoneNumber",
                "userInput-phoneNumber",
            ])
            expect(stdout).to.contain(nockServerResponse)
        })
    })

    describe("available-numbers:list next flag test", function () {
        const testJsonNext = {
            total: 1,
            start: 0,
            end: 0,
            page: 1,
            numPages: 1,
            pageSize: 100,
            nextPageUri: null,
        }

        const nockServerResponseNext = `== You are on the last page of output. ==`

        const testJsonNext2 = {
            total: 2,
            start: 0,
            end: 0,
            page: 1,
            numPages: 2,
            pageSize: 100,
            nextPageUri: "",
        }

        const nockServerResponseNext2 = `== Currently on page 1. Run this command again with the -n flag to go to the next page. ==`

        before(() => {
            testJsonNext2.nextPageUri = `https://www.freeclimb.com/apiserver/AvailablePhoneNumbers?cursor=freeClimbCLIAutomatedTestCursor`
        })

        afterEach(() => {
            nock.cleanAll()
        })

        it("Tests return of Exit Code 3 when flag next is not available", async () => {
            nock("https://www.freeclimb.com")
                .get(`/apiserver/AvailablePhoneNumbers`)
                .query({})
                .reply(200, testJson)
            const orig = process.env.FREECLIMB_AVAILABLE_NUMBERS_LIST_NEXT
            process.env.FREECLIMB_AVAILABLE_NUMBERS_LIST_NEXT = undefined
            try {
                await runCommand(["available-numbers:list"])
                const { error } = await runCommand(["available-numbers:list", "--next"])
                expect(error?.oclif?.exit).to.equal(3)
            } finally {
                if (orig !== undefined)
                    process.env.FREECLIMB_AVAILABLE_NUMBERS_LIST_NEXT = orig
                else delete process.env.FREECLIMB_AVAILABLE_NUMBERS_LIST_NEXT
            }
        })

        it("Test flag next works as expected when available with on last page", async () => {
            nock("https://www.freeclimb.com")
                .get(`/apiserver/AvailablePhoneNumbers`)
                .query({ cursor: "617661696c61626c652d6e756d626572733a6c697374" })
                .reply(200, testJsonNext)
            const orig = process.env.FREECLIMB_AVAILABLE_NUMBERS_LIST_NEXT
            process.env.FREECLIMB_AVAILABLE_NUMBERS_LIST_NEXT =
                "617661696c61626c652d6e756d626572733a6c697374"
            try {
                const { stdout } = await runCommand(["available-numbers:list", "--next"])
                expect(stdout).to.contain(nockServerResponseNext)
            } finally {
                if (orig !== undefined)
                    process.env.FREECLIMB_AVAILABLE_NUMBERS_LIST_NEXT = orig
                else delete process.env.FREECLIMB_AVAILABLE_NUMBERS_LIST_NEXT
            }
        })

        it("Test flag next works as expected when available with has more pages", async () => {
            nock("https://www.freeclimb.com")
                .get(`/apiserver/AvailablePhoneNumbers`)
                .query({ cursor: "617661696c61626c652d6e756d626572733a6c697374" })
                .reply(200, testJsonNext2)
            const orig = process.env.FREECLIMB_AVAILABLE_NUMBERS_LIST_NEXT
            process.env.FREECLIMB_AVAILABLE_NUMBERS_LIST_NEXT =
                "617661696c61626c652d6e756d626572733a6c697374"
            try {
                const { stdout } = await runCommand(["available-numbers:list", "--next"])
                expect(stdout).to.contain(nockServerResponseNext2)
            } finally {
                if (orig !== undefined)
                    process.env.FREECLIMB_AVAILABLE_NUMBERS_LIST_NEXT = orig
                else delete process.env.FREECLIMB_AVAILABLE_NUMBERS_LIST_NEXT
            }
        })

        it("Test error is caught when when using next flag and no reponse is given", async () => {
            nock("https://www.freeclimb.com")
                .get(`/apiserver/AvailablePhoneNumbers`)
                .query({ cursor: "617661696c61626c652d6e756d626572733a6c697374" })
                .reply(200, undefined)
            const orig = process.env.FREECLIMB_AVAILABLE_NUMBERS_LIST_NEXT
            process.env.FREECLIMB_AVAILABLE_NUMBERS_LIST_NEXT =
                "617661696c61626c652d6e756d626572733a6c697374"
            try {
                const { error } = await runCommand(["available-numbers:list", "--next"])
                expect(error?.oclif?.exit).to.equal(3)
            } finally {
                if (orig !== undefined)
                    process.env.FREECLIMB_AVAILABLE_NUMBERS_LIST_NEXT = orig
                else delete process.env.FREECLIMB_AVAILABLE_NUMBERS_LIST_NEXT
            }
        })
    })

    describe("available-numbers:list boolean input test", function () {
        afterEach(() => {
            nock.cleanAll()
        })

        it("tests that value false can be used with boolean flags and args", async () => {
            nock("https://www.freeclimb.com")
                .get(`/apiserver/AvailablePhoneNumbers`)
                .query({
                    alias: "123-456-7890",
                    country: "userInput-country",
                    region: "userInput-region",
                    smsEnabled: false,
                    voiceEnabled: false,
                    phoneNumber: "userInput-phoneNumber",
                })
                .reply(200, testJson)
            const { stdout } = await runCommand([
                "available-numbers:list",
                "--alias",
                "123-456-7890",
                "--country",
                "userInput-country",
                "--region",
                "userInput-region",
                "--smsEnabled",
                "false",
                "--voiceEnabled",
                "false",
                "--phoneNumber",
                "userInput-phoneNumber",
            ])
            expect(stdout).to.contain(nockServerResponse)
        })

        it("tests incorrect smsEnabled input results in exit code 2", async () => {
            const { error } = await runCommand([
                "available-numbers:list",
                "--smsEnabled",
                "flse",
            ])
            expect(error?.oclif?.exit).to.equal(2)
        })

        it("tests incorrect voiceEnabled input results in exit code 2", async () => {
            const { error } = await runCommand([
                "available-numbers:list",
                "--voiceEnabled",
                "flse",
            ])
            expect(error?.oclif?.exit).to.equal(2)
        })
    })
})

describe("available-numbers:list Status Test", function () {
    const testJsonStatus = ""
    const statusResponse = `Received a success code from FreeClimb. There is no further output.
`

    afterEach(() => {
        nock.cleanAll()
    })

    it("Test all required paramaters", async () => {
        nock("https://www.freeclimb.com")
            .get(`/apiserver/AvailablePhoneNumbers`)
            .query({})
            .reply(204, testJsonStatus)
        const { stdout } = await runCommand(["available-numbers:list"])
        expect(stdout).to.contain(statusResponse)
    })
})
