/* WARNING: This file is automatically generated. Please edit the files in the /generation/tests directory. */
import { expect } from "chai"
import nock from "nock"
import { runCommand } from "@oclif/test"
import { cred } from "../../src/credentials.js"

const callId = "userInput-callId"

describe("calls:update Data Test", function () {
    const testJson = {
        message: "Response from server",
    }

    const nockServerResponse = `{
  "message": "Response from server"
}`

    afterEach(() => {
        nock.cleanAll()
    })

    it("Test all required paramaters", async () => {
        nock("https://www.freeclimb.com")
            .post(`/apiserver/Accounts/${await cred.accountId}/Calls/${callId}`, {
                status: "userInput-status",
            })
            .query({})
            .reply(200, testJson)
        const { stdout } = await runCommand([
            "calls:update",
            "userInput-callId",
            "userInput-status",
        ])
        expect(stdout).to.contain(nockServerResponse)
    })

    it("Test Freeclimb Api error repsonce is process correctly without a suggestion", async () => {
        const testJsonErrorNoSuggestion = {
            code: 2,
            message: "Method Not Allowed",
            url: "https://docs.freeclimb.com/reference/error-and-warning-dictionary#2",
            details: {},
        }
        nock("https://www.freeclimb.com")
            .post(`/apiserver/Accounts/${await cred.accountId}/Calls/${callId}`, {
                status: "userInput-status",
            })
            .query({})
            .reply(500, testJsonErrorNoSuggestion)
        const { error } = await runCommand([
            "calls:update",
            "userInput-callId",
            "userInput-status",
        ])
        expect(error?.oclif?.exit).to.equal(3)
    })

    it("Sends API requests to the base URL from an environment variable", async () => {
        nock("https://user-custom-domain.example.com")
            .post(`/apiserver/Accounts/${await cred.accountId}/Calls/${callId}`, {
                status: "userInput-status",
            })
            .query({})
            .reply(200, testJson)
        const orig = process.env.FREECLIMB_CLI_BASE_URL
        process.env.FREECLIMB_CLI_BASE_URL = "https://user-custom-domain.example.com/apiserver"
        try {
            const { stdout } = await runCommand([
                "calls:update",
                "userInput-callId",
                "userInput-status",
            ])
            expect(stdout).to.contain(nockServerResponse)
        } finally {
            if (orig !== undefined) process.env.FREECLIMB_CLI_BASE_URL = orig
            else delete process.env.FREECLIMB_CLI_BASE_URL
        }
    })

    it("Test Freeclimb Api error repsonce is process correctly with a suggestion", async () => {
        const testJsonErrorWithSuggestion = {
            code: 50,
            message: "Unauthorized To Make Request",
            url: "https://docs.freeclimb.com/reference/error-and-warning-dictionary#50",
            details: {},
        }
        nock("https://www.freeclimb.com")
            .post(`/apiserver/Accounts/${await cred.accountId}/Calls/${callId}`, {
                status: "userInput-status",
            })
            .query({})
            .reply(500, testJsonErrorWithSuggestion)
        const { error } = await runCommand([
            "calls:update",
            "userInput-callId",
            "userInput-status",
        ])
        expect(error?.oclif?.exit).to.equal(3)
    })

    it("Test parse error gets triggered when there is an additional argument", async () => {
        const { error } = await runCommand([
            "calls:update",
            "userInput-callId",
            "userInput-status",
            "additionalArguments",
        ])
        expect(error?.oclif?.exit).to.equal(2)
    })

    it("Test error resulting in an unreadable response", async () => {
        nock("https://www.freeclimb.com")
            .post(`/apiserver/Accounts/${await cred.accountId}/Calls/${callId}`, {
                status: "userInput-status",
            })
            .query({})
            .reply(200, undefined)
        const { error } = await runCommand([
            "calls:update",
            "userInput-callId",
            "userInput-status",
        ])
        expect(error?.oclif?.exit).to.equal(3)
    })

    describe("calls:update next flag test", function () {
        afterEach(() => {
            nock.cleanAll()
        })

        it("Tests return of Exit Code 3 when flag next is not available", async () => {
            nock("https://www.freeclimb.com")
                .post(`/apiserver/Accounts/${await cred.accountId}/Calls/${callId}`, {
                    status: "userInput-status",
                })
                .query({})
                .reply(200, testJson)
            const orig = process.env.FREECLIMB_CALLS_UPDATE_NEXT
            delete process.env.FREECLIMB_CALLS_UPDATE_NEXT
            try {
                await runCommand(["calls:update", "userInput-callId", "userInput-status"])
                const { error } = await runCommand([
                    "calls:update",
                    "userInput-callId",
                    "userInput-status",
                    "--next",
                ])
                expect(error?.oclif?.exit).to.equal(3)
            } finally {
                if (orig !== undefined) process.env.FREECLIMB_CALLS_UPDATE_NEXT = orig
                else delete process.env.FREECLIMB_CALLS_UPDATE_NEXT
            }
        })
    })
})

describe("calls:update Status Test", function () {
    const testJsonStatus = ""
    const statusResponse = `Received a success code from FreeClimb. There is no further output.
`

    afterEach(() => {
        nock.cleanAll()
    })

    it("Test all required paramaters", async () => {
        nock("https://www.freeclimb.com")
            .post(`/apiserver/Accounts/${await cred.accountId}/Calls/${callId}`, {
                status: "userInput-status",
            })
            .query({})
            .reply(204, testJsonStatus)
        const { stdout } = await runCommand([
            "calls:update",
            "userInput-callId",
            "userInput-status",
        ])
        expect(stdout).to.contain(statusResponse)
    })
})
