/* WARNING: This file is automatically generated. Please edit the files in the /generation/tests directory. */
import { expect } from "chai"
import { runCommand } from "@oclif/test"
import nock from "nock"
import { cred } from "../../src/credentials.js"

describe("calls:make Data Test", function () {
    const testJson = {
        message: "Response from server",
    }

    const nockServerResponse = `{
  "message": "Response from server"
}`

    it("Test all required paramaters", async () => {
        nock("https://www.freeclimb.com")
            .post(`/apiserver/Accounts/${await cred.accountId}/Calls`, {
                from: "userInput-from",
                to: "userInput-to",
                applicationId: "userInput-applicationId",
            })
            .query({})
            .reply(200, testJson)
        const { stdout, stderr } = await runCommand([
            "calls:make",
            "userInput-from",
            "userInput-to",
            "userInput-applicationId",
        ])
        expect(stdout).to.contain(nockServerResponse)
    })

    const testJsonErrorNoSuggestion = {
        code: 2,
        message: "Method Not Allowed",
        url: "https://docs.freeclimb.com/reference/error-and-warning-dictionary#2",
        details: {},
    }

    const nockServerResponseErrorNoSuggestion = `starting test`

    it("Test Freeclimb Api error repsonce is process correctly without a suggestion", async () => {
        nock("https://www.freeclimb.com")
            .post(`/apiserver/Accounts/${await cred.accountId}/Calls`, {
                from: "userInput-from",
                to: "userInput-to",
                applicationId: "userInput-applicationId",
            })
            .query({})
            .reply(500, testJsonErrorNoSuggestion)
        const { error } = await runCommand([
            "calls:make",
            "userInput-from",
            "userInput-to",
            "userInput-applicationId",
        ])
        expect(error?.oclif?.exit).to.equal(3)
    })

    it("Sends API requests to the base URL from an environment variable", async () => {
        const orig_FREECLIMB_CLI_BASE_URL = process.env.FREECLIMB_CLI_BASE_URL
        process.env.FREECLIMB_CLI_BASE_URL = "https://user-custom-domain.example.com/apiserver"
        nock("https://user-custom-domain.example.com")
            .post(`/apiserver/Accounts/${await cred.accountId}/Calls`, {
                from: "userInput-from",
                to: "userInput-to",
                applicationId: "userInput-applicationId",
            })
            .query({})
            .reply(200, testJson)
        try {
            const { stdout, stderr } = await runCommand([
                "calls:make",
                "userInput-from",
                "userInput-to",
                "userInput-applicationId",
            ])
            expect(stdout).to.contain(nockServerResponse)
        } finally {
            if (orig_FREECLIMB_CLI_BASE_URL === undefined) delete process.env.FREECLIMB_CLI_BASE_URL
            else process.env.FREECLIMB_CLI_BASE_URL = orig_FREECLIMB_CLI_BASE_URL
        }
    })

    const testJsonErrorWithSuggestion = {
        code: 50,
        message: "Unauthorized To Make Request",
        url: "https://docs.freeclimb.com/reference/error-and-warning-dictionary#50",
        details: {},
    }

    const nockServerResponseErrorWithSuggestion = `starting test`

    it("Test Freeclimb Api error repsonce is process correctly with a suggestion", async () => {
        nock("https://www.freeclimb.com")
            .post(`/apiserver/Accounts/${await cred.accountId}/Calls`, {
                from: "userInput-from",
                to: "userInput-to",
                applicationId: "userInput-applicationId",
            })
            .query({})
            .reply(500, testJsonErrorWithSuggestion)
        const { error } = await runCommand([
            "calls:make",
            "userInput-from",
            "userInput-to",
            "userInput-applicationId",
        ])
        expect(error?.oclif?.exit).to.equal(3)
    })

    it("Test parse error gets triggered when there is an additional argument", async () => {
        const { error } = await runCommand([
            "calls:make",
            "userInput-from",
            "userInput-to",
            "userInput-applicationId",
            "additionalArguments",
        ])
        expect(error?.oclif?.exit).to.equal(2)
    })

    it("Test error resulting in an unreadable response", async () => {
        nock("https://www.freeclimb.com")
            .post(`/apiserver/Accounts/${await cred.accountId}/Calls`, {
                from: "userInput-from",
                to: "userInput-to",
                applicationId: "userInput-applicationId",
            })
            .query({})
            .reply(200, undefined)
        const { error } = await runCommand([
            "calls:make",
            "userInput-from",
            "userInput-to",
            "userInput-applicationId",
        ])
        expect(error?.oclif?.exit).to.equal(3)
    })

    it("testing all body parameters together and required query are sent through with request", async () => {
        nock("https://www.freeclimb.com")
            .post(`/apiserver/Accounts/${await cred.accountId}/Calls`, {
                from: "userInput-from",
                to: "userInput-to",
                applicationId: "userInput-applicationId",
                callConnectUrl: "userInput-callConnectUrl",
                parentCallId: "userInput-parentCallId",
                sendDigits: "userInput-sendDigits",
                ifMachine: "userInput-ifMachine",
                ifMachineUrl: "userInput-ifMachineUrl",
                timeout: 10,
                privacyMode: true,
            })
            .query({})
            .reply(200, testJson)
        const { stdout, stderr } = await runCommand([
            "calls:make",
            "userInput-from",
            "userInput-to",
            "userInput-applicationId",
            "--callConnectUrl",
            "userInput-callConnectUrl",
            "--parentCallId",
            "userInput-parentCallId",
            "--sendDigits",
            "userInput-sendDigits",
            "--ifMachine",
            "userInput-ifMachine",
            "--ifMachineUrl",
            "userInput-ifMachineUrl",
            "--timeout",
            "10",
            "--privacyMode",
            "true",
        ])
        expect(stdout).to.contain(nockServerResponse)
    })

    describe("calls:make body param flags", function () {
        it("required params and a body param is sent through with request-callConnectUrl", async () => {
            nock("https://www.freeclimb.com")
                .post(`/apiserver/Accounts/${await cred.accountId}/Calls`, {
                    from: "userInput-from",
                    to: "userInput-to",
                    applicationId: "userInput-applicationId",
                    callConnectUrl: "userInput-callConnectUrl",
                })
                .query({})
                .reply(200, testJson)
            const { stdout, stderr } = await runCommand([
                "calls:make",
                "userInput-from",
                "userInput-to",
                "userInput-applicationId",
                "--callConnectUrl",
                "userInput-callConnectUrl",
            ])
            expect(stdout).to.contain(nockServerResponse)
        })

        it("required params and a body param is sent through with request-parentCallId", async () => {
            nock("https://www.freeclimb.com")
                .post(`/apiserver/Accounts/${await cred.accountId}/Calls`, {
                    from: "userInput-from",
                    to: "userInput-to",
                    applicationId: "userInput-applicationId",
                    parentCallId: "userInput-parentCallId",
                })
                .query({})
                .reply(200, testJson)
            const { stdout, stderr } = await runCommand([
                "calls:make",
                "userInput-from",
                "userInput-to",
                "userInput-applicationId",
                "--parentCallId",
                "userInput-parentCallId",
            ])
            expect(stdout).to.contain(nockServerResponse)
        })

        it("required params and a body param is sent through with request-sendDigits", async () => {
            nock("https://www.freeclimb.com")
                .post(`/apiserver/Accounts/${await cred.accountId}/Calls`, {
                    from: "userInput-from",
                    to: "userInput-to",
                    applicationId: "userInput-applicationId",
                    sendDigits: "userInput-sendDigits",
                })
                .query({})
                .reply(200, testJson)
            const { stdout, stderr } = await runCommand([
                "calls:make",
                "userInput-from",
                "userInput-to",
                "userInput-applicationId",
                "--sendDigits",
                "userInput-sendDigits",
            ])
            expect(stdout).to.contain(nockServerResponse)
        })

        it("required params and a body param is sent through with request-ifMachine", async () => {
            nock("https://www.freeclimb.com")
                .post(`/apiserver/Accounts/${await cred.accountId}/Calls`, {
                    from: "userInput-from",
                    to: "userInput-to",
                    applicationId: "userInput-applicationId",
                    ifMachine: "userInput-ifMachine",
                })
                .query({})
                .reply(200, testJson)
            const { stdout, stderr } = await runCommand([
                "calls:make",
                "userInput-from",
                "userInput-to",
                "userInput-applicationId",
                "--ifMachine",
                "userInput-ifMachine",
            ])
            expect(stdout).to.contain(nockServerResponse)
        })

        it("required params and a body param is sent through with request-ifMachineUrl", async () => {
            nock("https://www.freeclimb.com")
                .post(`/apiserver/Accounts/${await cred.accountId}/Calls`, {
                    from: "userInput-from",
                    to: "userInput-to",
                    applicationId: "userInput-applicationId",
                    ifMachineUrl: "userInput-ifMachineUrl",
                })
                .query({})
                .reply(200, testJson)
            const { stdout, stderr } = await runCommand([
                "calls:make",
                "userInput-from",
                "userInput-to",
                "userInput-applicationId",
                "--ifMachineUrl",
                "userInput-ifMachineUrl",
            ])
            expect(stdout).to.contain(nockServerResponse)
        })

        it("required params and a body param is sent through with request-timeout", async () => {
            nock("https://www.freeclimb.com")
                .post(`/apiserver/Accounts/${await cred.accountId}/Calls`, {
                    from: "userInput-from",
                    to: "userInput-to",
                    applicationId: "userInput-applicationId",
                    timeout: 10,
                })
                .query({})
                .reply(200, testJson)
            const { stdout, stderr } = await runCommand([
                "calls:make",
                "userInput-from",
                "userInput-to",
                "userInput-applicationId",
                "--timeout",
                "10",
            ])
            expect(stdout).to.contain(nockServerResponse)
        })

        it("test that exit code 2 is used when timeout number goes above 120", async () => {
            const { error } = await runCommand([
                "calls:make",
                "userInput-from",
                "userInput-to",
                "userInput-applicationId",
                "--timeout",
                "121",
            ])
            expect(error?.oclif?.exit).to.equal(2)
        })

        it("test that exit code 2 is used when timeout number goes below 0", async () => {
            const { error } = await runCommand([
                "calls:make",
                "userInput-from",
                "userInput-to",
                "userInput-applicationId",
                "--timeout",
                "-1",
            ])
            expect(error?.oclif?.exit).to.equal(2)
        })

        it("required params and a body param is sent through with request-privacyMode", async () => {
            nock("https://www.freeclimb.com")
                .post(`/apiserver/Accounts/${await cred.accountId}/Calls`, {
                    from: "userInput-from",
                    to: "userInput-to",
                    applicationId: "userInput-applicationId",
                    privacyMode: true,
                })
                .query({})
                .reply(200, testJson)
            const { stdout, stderr } = await runCommand([
                "calls:make",
                "userInput-from",
                "userInput-to",
                "userInput-applicationId",
                "--privacyMode",
                "true",
            ])
            expect(stdout).to.contain(nockServerResponse)
        })
    })

    describe("calls:make next flag test", function () {
        it("Tests return of Exit Code 3 when flag next is not available", async () => {
            const orig_FREECLIMB_CALLS_MAKE_NEXT = process.env.FREECLIMB_CALLS_MAKE_NEXT
            delete process.env.FREECLIMB_CALLS_MAKE_NEXT
            nock("https://www.freeclimb.com")
                .post(`/apiserver/Accounts/${await cred.accountId}/Calls`, {
                    from: "userInput-from",
                    to: "userInput-to",
                    applicationId: "userInput-applicationId",
                })
                .query({})
                .reply(200, testJson)
            try {
                await runCommand([
                    "calls:make",
                    "userInput-from",
                    "userInput-to",
                    "userInput-applicationId",
                ])
                const { error } = await runCommand([
                    "calls:make",
                    "userInput-from",
                    "userInput-to",
                    "userInput-applicationId",
                    "--next",
                ])
                expect(error?.oclif?.exit).to.equal(3)
            } finally {
                if (orig_FREECLIMB_CALLS_MAKE_NEXT === undefined)
                    delete process.env.FREECLIMB_CALLS_MAKE_NEXT
                else process.env.FREECLIMB_CALLS_MAKE_NEXT = orig_FREECLIMB_CALLS_MAKE_NEXT
            }
        })
    })

    describe("calls:make boolean input test", function () {
        it("tests that value false can be used with boolean flags and args", async () => {
            nock("https://www.freeclimb.com")
                .post(`/apiserver/Accounts/${await cred.accountId}/Calls`, {
                    from: "userInput-from",
                    to: "userInput-to",
                    applicationId: "userInput-applicationId",
                    callConnectUrl: "userInput-callConnectUrl",
                    parentCallId: "userInput-parentCallId",
                    sendDigits: "userInput-sendDigits",
                    ifMachine: "userInput-ifMachine",
                    ifMachineUrl: "userInput-ifMachineUrl",
                    timeout: 10,
                    privacyMode: false,
                })
                .query({})
                .reply(200, testJson)
            const { stdout, stderr } = await runCommand([
                "calls:make",
                "userInput-from",
                "userInput-to",
                "userInput-applicationId",
                "--callConnectUrl",
                "userInput-callConnectUrl",
                "--parentCallId",
                "userInput-parentCallId",
                "--sendDigits",
                "userInput-sendDigits",
                "--ifMachine",
                "userInput-ifMachine",
                "--ifMachineUrl",
                "userInput-ifMachineUrl",
                "--timeout",
                "10",
                "--privacyMode",
                "false",
            ])
            expect(stdout).to.contain(nockServerResponse)
        })

        it("tests incorrect privacyMode input results in exit code 2", async () => {
            const { error } = await runCommand([
                "calls:make",
                "userInput-from",
                "userInput-to",
                "userInput-applicationId",
                "--privacyMode",
                "flse",
            ])
            expect(error?.oclif?.exit).to.equal(2)
        })
    })
})

describe("calls:make Status Test", function () {
    const testJsonStatus = ""

    const statusResponse = `Received a success code from FreeClimb. There is no further output.
`

    it("Test all required paramaters", async () => {
        nock("https://www.freeclimb.com")
            .post(`/apiserver/Accounts/${await cred.accountId}/Calls`, {
                from: "userInput-from",
                to: "userInput-to",
                applicationId: "userInput-applicationId",
            })
            .query({})
            .reply(204, testJsonStatus)
        const { stdout, stderr } = await runCommand([
            "calls:make",
            "userInput-from",
            "userInput-to",
            "userInput-applicationId",
        ])
        expect(stdout).to.contain(statusResponse)
    })
})
