/* WARNING: This file is automatically generated. Please edit the files in the /generation/tests directory. */
import { expect } from "chai"
import nock from "nock"
import { runCommand } from "@oclif/test"
import { cred } from "../../src/credentials.js"

describe("call-queues:list Data Test", function () {
    const testJson = {
        message: "Response from server",
    }

    afterEach(() => {
        nock.cleanAll()
    })

    it("Test all required paramaters", async () => {
        nock("https://www.freeclimb.com")
            .get(`/apiserver/Accounts/${await cred.accountId}/Queues`)
            .query({})
            .reply(200, testJson)
        const { stdout } = await runCommand(["call-queues:list", "--json"])
        expect(stdout).to.contain('"message": "Response from server"')
    })

    it("Test Freeclimb Api error repsonce is process correctly without a suggestion", async () => {
        const testJsonErrorNoSuggestion = {
            code: 2,
            message: "Method Not Allowed",
            url: "https://docs.freeclimb.com/reference/error-and-warning-dictionary#2",
            details: {},
        }
        nock("https://www.freeclimb.com")
            .get(`/apiserver/Accounts/${await cred.accountId}/Queues`)
            .query({})
            .reply(500, testJsonErrorNoSuggestion)
        const { error } = await runCommand(["call-queues:list"])
        expect(error?.oclif?.exit).to.equal(3)
    })

    it("Sends API requests to the base URL from an environment variable", async () => {
        nock("https://user-custom-domain.example.com")
            .get(`/apiserver/Accounts/${await cred.accountId}/Queues`)
            .query({})
            .reply(200, testJson)
        const orig = process.env.FREECLIMB_CLI_BASE_URL
        process.env.FREECLIMB_CLI_BASE_URL = "https://user-custom-domain.example.com/apiserver"
        try {
            const { stdout } = await runCommand(["call-queues:list", "--json"])
            expect(stdout).to.contain('"message": "Response from server"')
        } finally {
            if (orig !== undefined) process.env.FREECLIMB_CLI_BASE_URL = orig
            else delete process.env.FREECLIMB_CLI_BASE_URL
        }
    })

    it("Test Freeclimb Api error repsonce is process correctly with a suggestion", async () => {
        const testJsonErrorWithSuggestion = {
            code: 50,
            message: "Unauthorized To Make Request",
            url: "https://docs.freeclimb.com/reference/error-and-warning-dictionary#50",
            details: {},
        }
        nock("https://www.freeclimb.com")
            .get(`/apiserver/Accounts/${await cred.accountId}/Queues`)
            .query({})
            .reply(500, testJsonErrorWithSuggestion)
        const { error } = await runCommand(["call-queues:list"])
        expect(error?.oclif?.exit).to.equal(3)
    })

    it("Test parse error gets triggered when there is an additional argument", async () => {
        const { error } = await runCommand(["call-queues:list", "additionalArguments"])
        expect(error?.oclif?.exit).to.equal(2)
    })

    it("Test error resulting in an unreadable response", async () => {
        nock("https://www.freeclimb.com")
            .get(`/apiserver/Accounts/${await cred.accountId}/Queues`)
            .query({})
            .reply(200, undefined)
        const { error } = await runCommand(["call-queues:list"])
        expect(error?.oclif?.exit).to.equal(3)
    })

    describe("call-queues:list query param flags", function () {
        afterEach(() => {
            nock.cleanAll()
        })

        it("required params and a query param is sent through with request-alias", async () => {
            nock("https://www.freeclimb.com")
                .get(`/apiserver/Accounts/${await cred.accountId}/Queues`)
                .query({ alias: "userInput-alias" })
                .reply(200, testJson)
            const { stdout } = await runCommand([
                "call-queues:list",
                "--alias",
                "userInput-alias",
                "--json",
            ])
            expect(stdout).to.contain('"message": "Response from server"')
        })
    })

    describe("call-queues:list next flag test", function () {
        const testJsonNext = {
            total: 1,
            start: 0,
            end: 0,
            page: 1,
            numPages: 1,
            pageSize: 100,
            nextPageUri: null,
        }

        const testJsonNext2 = {
            total: 2,
            start: 0,
            end: 0,
            page: 1,
            numPages: 2,
            pageSize: 100,
            nextPageUri: "",
        }

        before(async () => {
            const accountId = await cred.accountId
            testJsonNext2.nextPageUri = `https://www.freeclimb.com/apiserver/Accounts/${accountId}/Queues?cursor=freeClimbCLIAutomatedTestCursor`
        })

        afterEach(() => {
            nock.cleanAll()
        })

        it("Tests return of Exit Code 3 when flag next is not available", async () => {
            nock("https://www.freeclimb.com")
                .get(`/apiserver/Accounts/${await cred.accountId}/Queues`)
                .query({})
                .reply(200, testJson)
            const orig = process.env.FREECLIMB_CALL_QUEUES_LIST_NEXT
            delete process.env.FREECLIMB_CALL_QUEUES_LIST_NEXT
            try {
                await runCommand(["call-queues:list", "--json"])
                const { error } = await runCommand(["call-queues:list", "--next"])
                expect(error?.oclif?.exit).to.equal(3)
            } finally {
                if (orig !== undefined) process.env.FREECLIMB_CALL_QUEUES_LIST_NEXT = orig
                else delete process.env.FREECLIMB_CALL_QUEUES_LIST_NEXT
            }
        })

        it("Test flag next works as expected when available with on last page", async () => {
            nock("https://www.freeclimb.com")
                .get(`/apiserver/Accounts/${await cred.accountId}/Queues`)
                .query({ cursor: "63616c6c2d7175657565733a6c697374" })
                .reply(200, testJsonNext)
            const orig = process.env.FREECLIMB_CALL_QUEUES_LIST_NEXT
            process.env.FREECLIMB_CALL_QUEUES_LIST_NEXT = "63616c6c2d7175657565733a6c697374"
            try {
                const { stdout } = await runCommand(["call-queues:list", "--next", "--json"])
                expect(stdout).to.contain('"page": 1')
            } finally {
                if (orig !== undefined) process.env.FREECLIMB_CALL_QUEUES_LIST_NEXT = orig
                else delete process.env.FREECLIMB_CALL_QUEUES_LIST_NEXT
            }
        })

        it("Test flag next works as expected when available with has more pages", async () => {
            nock("https://www.freeclimb.com")
                .get(`/apiserver/Accounts/${await cred.accountId}/Queues`)
                .query({ cursor: "63616c6c2d7175657565733a6c697374" })
                .reply(200, testJsonNext2)
            const orig = process.env.FREECLIMB_CALL_QUEUES_LIST_NEXT
            process.env.FREECLIMB_CALL_QUEUES_LIST_NEXT = "63616c6c2d7175657565733a6c697374"
            try {
                const { stdout } = await runCommand(["call-queues:list", "--next", "--json"])
                expect(stdout).to.contain('"page": 1')
            } finally {
                if (orig !== undefined) process.env.FREECLIMB_CALL_QUEUES_LIST_NEXT = orig
                else delete process.env.FREECLIMB_CALL_QUEUES_LIST_NEXT
            }
        })

        it("Test error is caught when when using next flag and no reponse is given", async () => {
            nock("https://www.freeclimb.com")
                .get(`/apiserver/Accounts/${await cred.accountId}/Queues`)
                .query({ cursor: "63616c6c2d7175657565733a6c697374" })
                .reply(200, undefined)
            const orig = process.env.FREECLIMB_CALL_QUEUES_LIST_NEXT
            process.env.FREECLIMB_CALL_QUEUES_LIST_NEXT = "63616c6c2d7175657565733a6c697374"
            try {
                const { error } = await runCommand(["call-queues:list", "--next"])
                expect(error?.oclif?.exit).to.equal(3)
            } finally {
                if (orig !== undefined) process.env.FREECLIMB_CALL_QUEUES_LIST_NEXT = orig
                else delete process.env.FREECLIMB_CALL_QUEUES_LIST_NEXT
            }
        })
    })
})

describe("call-queues:list Status Test", function () {
    const testJsonStatus = ""
    afterEach(() => {
        nock.cleanAll()
    })

    it("Test all required paramaters", async () => {
        nock("https://www.freeclimb.com")
            .get(`/apiserver/Accounts/${await cred.accountId}/Queues`)
            .query({})
            .reply(204, testJsonStatus)
        const { stdout } = await runCommand(["call-queues:list", "--json"])
        expect(stdout).to.contain('"success": true')
    })
})
