/* WARNING: This file is automatically generated. Please edit the files in the /generation/tests directory. */
import { expect } from "chai"
import { runCommand } from "@oclif/test"
import nock from "nock"
import { cred } from "../../src/credentials.js"

const conferenceId = "userInput-conferenceId"

import { data } from "../../src/commands/data.js"
import { Environment } from "../../src/environment.js"

describe("conference-participants:list Data Test", function () {
    const testJson = {
        message: "Response from server",
    }

    const nockServerResponse = `{
  "message": "Response from server"
}`

    it("Test all required paramaters", async () => {
        nock("https://www.freeclimb.com")
            .get(
                `/apiserver/Accounts/${await cred.accountId}/Conferences/${conferenceId}/Participants`,
            )
            .query({})
            .reply(200, testJson)
        const { stdout, stderr } = await runCommand([
            "conference-participants:list",
            "userInput-conferenceId",
        ])
        expect(stdout).to.contain(nockServerResponse)
    })

    const testJsonErrorNoSuggestion = {
        code: 2,
        message: "Method Not Allowed",
        url: "https://docs.freeclimb.com/reference/error-and-warning-dictionary#2",
        details: {},
    }

    const nockServerResponseErrorNoSuggestion = `starting test`

    it("Test Freeclimb Api error repsonce is process correctly without a suggestion", async () => {
        nock("https://www.freeclimb.com")
            .get(
                `/apiserver/Accounts/${await cred.accountId}/Conferences/${conferenceId}/Participants`,
            )
            .query({})
            .reply(500, testJsonErrorNoSuggestion)
        const { error } = await runCommand([
            "conference-participants:list",
            "userInput-conferenceId",
        ])
        expect(error?.oclif?.exit).to.equal(3)
    })

    it("Sends API requests to the base URL from an environment variable", async () => {
        const orig_FREECLIMB_CLI_BASE_URL = process.env.FREECLIMB_CLI_BASE_URL
        process.env.FREECLIMB_CLI_BASE_URL = "https://user-custom-domain.example.com/apiserver"
        nock("https://user-custom-domain.example.com")
            .get(
                `/apiserver/Accounts/${await cred.accountId}/Conferences/${conferenceId}/Participants`,
            )
            .query({})
            .reply(200, testJson)
        try {
            const { stdout, stderr } = await runCommand([
                "conference-participants:list",
                "userInput-conferenceId",
            ])
            expect(stdout).to.contain(nockServerResponse)
        } finally {
            if (orig_FREECLIMB_CLI_BASE_URL === undefined) delete process.env.FREECLIMB_CLI_BASE_URL
            else process.env.FREECLIMB_CLI_BASE_URL = orig_FREECLIMB_CLI_BASE_URL
        }
    })

    const testJsonErrorWithSuggestion = {
        code: 50,
        message: "Unauthorized To Make Request",
        url: "https://docs.freeclimb.com/reference/error-and-warning-dictionary#50",
        details: {},
    }

    const nockServerResponseErrorWithSuggestion = `starting test`

    it("Test Freeclimb Api error repsonce is process correctly with a suggestion", async () => {
        nock("https://www.freeclimb.com")
            .get(
                `/apiserver/Accounts/${await cred.accountId}/Conferences/${conferenceId}/Participants`,
            )
            .query({})
            .reply(500, testJsonErrorWithSuggestion)
        const { error } = await runCommand([
            "conference-participants:list",
            "userInput-conferenceId",
        ])
        expect(error?.oclif?.exit).to.equal(3)
    })

    it("Test parse error gets triggered when there is an additional argument", async () => {
        const { error } = await runCommand([
            "conference-participants:list",
            "userInput-conferenceId",
            "additionalArguments",
        ])
        expect(error?.oclif?.exit).to.equal(2)
    })

    it("Test error resulting in an unreadable response", async () => {
        nock("https://www.freeclimb.com")
            .get(
                `/apiserver/Accounts/${await cred.accountId}/Conferences/${conferenceId}/Participants`,
            )
            .query({})
            .reply(200, undefined)
        const { error } = await runCommand([
            "conference-participants:list",
            "userInput-conferenceId",
        ])
        expect(error?.oclif?.exit).to.equal(3)
    })

    it("testing all query parameters and required body are sent through with request", async () => {
        nock("https://www.freeclimb.com")
            .get(
                `/apiserver/Accounts/${await cred.accountId}/Conferences/${conferenceId}/Participants`,
            )
            .query({
                talk: true,
                listen: true,
            })
            .reply(200, testJson)
        const { stdout, stderr } = await runCommand([
            "conference-participants:list",
            "userInput-conferenceId",
            "--talk",
            "true",
            "--listen",
            "true",
        ])
        expect(stdout).to.contain(nockServerResponse)
    })

    describe("conference-participants:list query param flags", function () {
        it("required params and a query param is sent through with request-talk", async () => {
            nock("https://www.freeclimb.com")
                .get(
                    `/apiserver/Accounts/${await cred.accountId}/Conferences/${conferenceId}/Participants`,
                )
                .query({
                    talk: true,
                })
                .reply(200, testJson)
            const { stdout, stderr } = await runCommand([
                "conference-participants:list",
                "userInput-conferenceId",
                "--talk",
                "true",
            ])
            expect(stdout).to.contain(nockServerResponse)
        })

        it("required params and a query param is sent through with request-listen", async () => {
            nock("https://www.freeclimb.com")
                .get(
                    `/apiserver/Accounts/${await cred.accountId}/Conferences/${conferenceId}/Participants`,
                )
                .query({
                    listen: true,
                })
                .reply(200, testJson)
            const { stdout, stderr } = await runCommand([
                "conference-participants:list",
                "userInput-conferenceId",
                "--listen",
                "true",
            ])
            expect(stdout).to.contain(nockServerResponse)
        })
    })

    describe("conference-participants:list next flag test", function () {
        it("Tests return of Exit Code 3 when flag next is not available", async () => {
            const orig_FREECLIMB_CONFERENCE_PARTICIPANTS_LIST_NEXT =
                process.env.FREECLIMB_CONFERENCE_PARTICIPANTS_LIST_NEXT
            delete process.env.FREECLIMB_CONFERENCE_PARTICIPANTS_LIST_NEXT
            nock("https://www.freeclimb.com")
                .get(
                    `/apiserver/Accounts/${await cred.accountId}/Conferences/${conferenceId}/Participants`,
                )
                .query({})
                .reply(200, testJson)
            try {
                await runCommand(["conference-participants:list", "userInput-conferenceId"])
                const { error } = await runCommand([
                    "conference-participants:list",
                    "userInput-conferenceId",
                    "--next",
                ])
                expect(error?.oclif?.exit).to.equal(3)
            } finally {
                if (orig_FREECLIMB_CONFERENCE_PARTICIPANTS_LIST_NEXT === undefined)
                    delete process.env.FREECLIMB_CONFERENCE_PARTICIPANTS_LIST_NEXT
                else
                    process.env.FREECLIMB_CONFERENCE_PARTICIPANTS_LIST_NEXT =
                        orig_FREECLIMB_CONFERENCE_PARTICIPANTS_LIST_NEXT
            }
        })

        const testJsonNext = {
            total: 1,
            start: 0,
            end: 0,
            page: 1,
            numPages: 1,
            pageSize: 100,
            nextPageUri: null,
        }

        const nockServerResponseNext = `== You are on the last page of output. ==`

        const testJsonNext2 = {
            total: 2,
            start: 0,
            end: 0,
            page: 1,
            numPages: 2,
            pageSize: 100,
            nextPageUri: "",
        }

        const nockServerResponseNext2 = `== Currently on page 1. Run this command again with the -n flag to go to the next page. ==`

        it("Test flag next works as expected when available with on last page", async () => {
            const orig_FREECLIMB_CONFERENCE_PARTICIPANTS_LIST_NEXT =
                process.env.FREECLIMB_CONFERENCE_PARTICIPANTS_LIST_NEXT
            process.env.FREECLIMB_CONFERENCE_PARTICIPANTS_LIST_NEXT =
                "636f6e666572656e63652d7061727469636970616e74733a6c697374"
            nock("https://www.freeclimb.com")
                .get(
                    `/apiserver/Accounts/${await cred.accountId}/Conferences/${conferenceId}/Participants`,
                )
                .query({ cursor: "636f6e666572656e63652d7061727469636970616e74733a6c697374" })
                .reply(200, testJsonNext)
            try {
                const { stdout, stderr } = await runCommand([
                    "conference-participants:list",
                    "userInput-conferenceId",
                    "--next",
                ])
                expect(stdout).to.contain(nockServerResponseNext)
            } finally {
                if (orig_FREECLIMB_CONFERENCE_PARTICIPANTS_LIST_NEXT === undefined)
                    delete process.env.FREECLIMB_CONFERENCE_PARTICIPANTS_LIST_NEXT
                else
                    process.env.FREECLIMB_CONFERENCE_PARTICIPANTS_LIST_NEXT =
                        orig_FREECLIMB_CONFERENCE_PARTICIPANTS_LIST_NEXT
            }
        })

        const finalCursor = "freeClimbCLIAutomatedTestCursor"

        before(() => {
            ;(async () => {
                testJsonNext2.nextPageUri = `https://www.freeclimb.com/apiserver/Accounts/${await cred.accountId}/Conferences/${conferenceId}/Participants?cursor=${finalCursor}`
            })()
        })
        after(() => {
            const dataDir = data.run([]).then(
                (dataDir) => {
                    const environment = new Environment(dataDir)
                    environment.clearString("FREECLIMB_CONFERENCE_PARTICIPANTS_LIST_NEXT")
                },
                (reason) => console.log(reason),
            )
        })
        it("Test flag next works as expected when available with has more pages", async () => {
            const orig_FREECLIMB_CONFERENCE_PARTICIPANTS_LIST_NEXT =
                process.env.FREECLIMB_CONFERENCE_PARTICIPANTS_LIST_NEXT
            process.env.FREECLIMB_CONFERENCE_PARTICIPANTS_LIST_NEXT =
                "636f6e666572656e63652d7061727469636970616e74733a6c697374"
            nock("https://www.freeclimb.com")
                .get(
                    `/apiserver/Accounts/${await cred.accountId}/Conferences/${conferenceId}/Participants`,
                )
                .query({ cursor: "636f6e666572656e63652d7061727469636970616e74733a6c697374" })
                .reply(200, testJsonNext2)
            try {
                const { stdout, stderr } = await runCommand([
                    "conference-participants:list",
                    "userInput-conferenceId",
                    "--next",
                ])
                expect(stdout).to.contain(nockServerResponseNext2)
            } finally {
                if (orig_FREECLIMB_CONFERENCE_PARTICIPANTS_LIST_NEXT === undefined)
                    delete process.env.FREECLIMB_CONFERENCE_PARTICIPANTS_LIST_NEXT
                else
                    process.env.FREECLIMB_CONFERENCE_PARTICIPANTS_LIST_NEXT =
                        orig_FREECLIMB_CONFERENCE_PARTICIPANTS_LIST_NEXT
            }
        })

        it("Test error is caught when when using next flag and no reponse is given", async () => {
            const orig_FREECLIMB_CONFERENCE_PARTICIPANTS_LIST_NEXT =
                process.env.FREECLIMB_CONFERENCE_PARTICIPANTS_LIST_NEXT
            process.env.FREECLIMB_CONFERENCE_PARTICIPANTS_LIST_NEXT =
                "636f6e666572656e63652d7061727469636970616e74733a6c697374"
            nock("https://www.freeclimb.com")
                .get(
                    `/apiserver/Accounts/${await cred.accountId}/Conferences/${conferenceId}/Participants`,
                )
                .query({ cursor: "636f6e666572656e63652d7061727469636970616e74733a6c697374" })
                .reply(200, undefined)
            try {
                const { error } = await runCommand([
                    "conference-participants:list",
                    "userInput-conferenceId",
                    "--next",
                ])
                expect(error?.oclif?.exit).to.equal(3)
            } finally {
                if (orig_FREECLIMB_CONFERENCE_PARTICIPANTS_LIST_NEXT === undefined)
                    delete process.env.FREECLIMB_CONFERENCE_PARTICIPANTS_LIST_NEXT
                else
                    process.env.FREECLIMB_CONFERENCE_PARTICIPANTS_LIST_NEXT =
                        orig_FREECLIMB_CONFERENCE_PARTICIPANTS_LIST_NEXT
            }
        })
    })

    describe("conference-participants:list boolean input test", function () {
        it("tests that value false can be used with boolean flags and args", async () => {
            nock("https://www.freeclimb.com")
                .get(
                    `/apiserver/Accounts/${await cred.accountId}/Conferences/${conferenceId}/Participants`,
                )
                .query({
                    talk: false,
                    listen: false,
                })
                .reply(200, testJson)
            const { stdout, stderr } = await runCommand([
                "conference-participants:list",
                "userInput-conferenceId",
                "--talk",
                "false",
                "--listen",
                "false",
            ])
            expect(stdout).to.contain(nockServerResponse)
        })

        it("tests incorrect talk input results in exit code 2", async () => {
            const { error } = await runCommand([
                "conference-participants:list",
                "userInput-conferenceId",
                "--talk",
                "flse",
            ])
            expect(error?.oclif?.exit).to.equal(2)
        })

        it("tests incorrect listen input results in exit code 2", async () => {
            const { error } = await runCommand([
                "conference-participants:list",
                "userInput-conferenceId",
                "--listen",
                "flse",
            ])
            expect(error?.oclif?.exit).to.equal(2)
        })
    })
})

describe("conference-participants:list Status Test", function () {
    const testJsonStatus = ""

    const statusResponse = `Received a success code from FreeClimb. There is no further output.
`

    it("Test all required paramaters", async () => {
        nock("https://www.freeclimb.com")
            .get(
                `/apiserver/Accounts/${await cred.accountId}/Conferences/${conferenceId}/Participants`,
            )
            .query({})
            .reply(204, testJsonStatus)
        const { stdout, stderr } = await runCommand([
            "conference-participants:list",
            "userInput-conferenceId",
        ])
        expect(stdout).to.contain(statusResponse)
    })
})
