/* WARNING: This file is automatically generated. Please edit the files in the /generation/tests directory. */
import { expect } from "chai"
import { runCommand } from "@oclif/test"
import nock from "nock"
import { cred } from "../../src/credentials.js"

describe("conferences:create Data Test", function () {
    const testJson = {
        message: "Response from server",
    }

    const nockServerResponse = `{
  "message": "Response from server"
}`

    it("Test all required paramaters", async () => {
        nock("https://www.freeclimb.com")
            .post(`/apiserver/Accounts/${await cred.accountId}/Conferences`, {})
            .query({})
            .reply(200, testJson)
        const { stdout, stderr } = await runCommand(["conferences:create"])
        expect(stdout).to.contain(nockServerResponse)
    })

    const testJsonErrorNoSuggestion = {
        code: 2,
        message: "Method Not Allowed",
        url: "https://docs.freeclimb.com/reference/error-and-warning-dictionary#2",
        details: {},
    }

    const nockServerResponseErrorNoSuggestion = `starting test`

    it("Test Freeclimb Api error repsonce is process correctly without a suggestion", async () => {
        nock("https://www.freeclimb.com")
            .post(`/apiserver/Accounts/${await cred.accountId}/Conferences`, {})
            .query({})
            .reply(500, testJsonErrorNoSuggestion)
        const { error } = await runCommand(["conferences:create"])
        expect(error?.oclif?.exit).to.equal(3)
    })

    it("Sends API requests to the base URL from an environment variable", async () => {
        const orig_FREECLIMB_CLI_BASE_URL = process.env.FREECLIMB_CLI_BASE_URL
        process.env.FREECLIMB_CLI_BASE_URL = "https://user-custom-domain.example.com/apiserver"
        nock("https://user-custom-domain.example.com")
            .post(`/apiserver/Accounts/${await cred.accountId}/Conferences`, {})
            .query({})
            .reply(200, testJson)
        try {
            const { stdout, stderr } = await runCommand(["conferences:create"])
            expect(stdout).to.contain(nockServerResponse)
        } finally {
            if (orig_FREECLIMB_CLI_BASE_URL === undefined) delete process.env.FREECLIMB_CLI_BASE_URL
            else process.env.FREECLIMB_CLI_BASE_URL = orig_FREECLIMB_CLI_BASE_URL
        }
    })

    const testJsonErrorWithSuggestion = {
        code: 50,
        message: "Unauthorized To Make Request",
        url: "https://docs.freeclimb.com/reference/error-and-warning-dictionary#50",
        details: {},
    }

    const nockServerResponseErrorWithSuggestion = `starting test`

    it("Test Freeclimb Api error repsonce is process correctly with a suggestion", async () => {
        nock("https://www.freeclimb.com")
            .post(`/apiserver/Accounts/${await cred.accountId}/Conferences`, {})
            .query({})
            .reply(500, testJsonErrorWithSuggestion)
        const { error } = await runCommand(["conferences:create"])
        expect(error?.oclif?.exit).to.equal(3)
    })

    it("Test parse error gets triggered when there is an additional argument", async () => {
        const { error } = await runCommand(["conferences:create", "additionalArguments"])
        expect(error?.oclif?.exit).to.equal(2)
    })

    it("Test error resulting in an unreadable response", async () => {
        nock("https://www.freeclimb.com")
            .post(`/apiserver/Accounts/${await cred.accountId}/Conferences`, {})
            .query({})
            .reply(200, undefined)
        const { error } = await runCommand(["conferences:create"])
        expect(error?.oclif?.exit).to.equal(3)
    })

    it("testing all body parameters together and required query are sent through with request", async () => {
        nock("https://www.freeclimb.com")
            .post(`/apiserver/Accounts/${await cred.accountId}/Conferences`, {
                alias: "userInput-alias",
                playBeep: "userInput-playBeep",
                record: true,
                waitUrl: "userInput-waitUrl",
                statusCallbackUrl: "userInput-statusCallbackUrl",
            })
            .query({})
            .reply(200, testJson)
        const { stdout, stderr } = await runCommand([
            "conferences:create",
            "--alias",
            "userInput-alias",
            "--playBeep",
            "userInput-playBeep",
            "--record",
            "true",
            "--waitUrl",
            "userInput-waitUrl",
            "--statusCallbackUrl",
            "userInput-statusCallbackUrl",
        ])
        expect(stdout).to.contain(nockServerResponse)
    })

    describe("conferences:create body param flags", function () {
        it("required params and a body param is sent through with request-alias", async () => {
            nock("https://www.freeclimb.com")
                .post(`/apiserver/Accounts/${await cred.accountId}/Conferences`, {
                    alias: "userInput-alias",
                })
                .query({})
                .reply(200, testJson)
            const { stdout, stderr } = await runCommand([
                "conferences:create",
                "--alias",
                "userInput-alias",
            ])
            expect(stdout).to.contain(nockServerResponse)
        })

        it("required params and a body param is sent through with request-playBeep", async () => {
            nock("https://www.freeclimb.com")
                .post(`/apiserver/Accounts/${await cred.accountId}/Conferences`, {
                    playBeep: "userInput-playBeep",
                })
                .query({})
                .reply(200, testJson)
            const { stdout, stderr } = await runCommand([
                "conferences:create",
                "--playBeep",
                "userInput-playBeep",
            ])
            expect(stdout).to.contain(nockServerResponse)
        })

        it("required params and a body param is sent through with request-record", async () => {
            nock("https://www.freeclimb.com")
                .post(`/apiserver/Accounts/${await cred.accountId}/Conferences`, {
                    record: true,
                })
                .query({})
                .reply(200, testJson)
            const { stdout, stderr } = await runCommand(["conferences:create", "--record", "true"])
            expect(stdout).to.contain(nockServerResponse)
        })

        it("required params and a body param is sent through with request-waitUrl", async () => {
            nock("https://www.freeclimb.com")
                .post(`/apiserver/Accounts/${await cred.accountId}/Conferences`, {
                    waitUrl: "userInput-waitUrl",
                })
                .query({})
                .reply(200, testJson)
            const { stdout, stderr } = await runCommand([
                "conferences:create",
                "--waitUrl",
                "userInput-waitUrl",
            ])
            expect(stdout).to.contain(nockServerResponse)
        })

        it("required params and a body param is sent through with request-statusCallbackUrl", async () => {
            nock("https://www.freeclimb.com")
                .post(`/apiserver/Accounts/${await cred.accountId}/Conferences`, {
                    statusCallbackUrl: "userInput-statusCallbackUrl",
                })
                .query({})
                .reply(200, testJson)
            const { stdout, stderr } = await runCommand([
                "conferences:create",
                "--statusCallbackUrl",
                "userInput-statusCallbackUrl",
            ])
            expect(stdout).to.contain(nockServerResponse)
        })
    })

    describe("conferences:create next flag test", function () {
        it("Tests return of Exit Code 3 when flag next is not available", async () => {
            const orig_FREECLIMB_CONFERENCES_CREATE_NEXT =
                process.env.FREECLIMB_CONFERENCES_CREATE_NEXT
            delete process.env.FREECLIMB_CONFERENCES_CREATE_NEXT
            nock("https://www.freeclimb.com")
                .post(`/apiserver/Accounts/${await cred.accountId}/Conferences`, {})
                .query({})
                .reply(200, testJson)
            try {
                await runCommand(["conferences:create"])
                const { error } = await runCommand(["conferences:create", "--next"])
                expect(error?.oclif?.exit).to.equal(3)
            } finally {
                if (orig_FREECLIMB_CONFERENCES_CREATE_NEXT === undefined)
                    delete process.env.FREECLIMB_CONFERENCES_CREATE_NEXT
                else
                    process.env.FREECLIMB_CONFERENCES_CREATE_NEXT =
                        orig_FREECLIMB_CONFERENCES_CREATE_NEXT
            }
        })
    })

    describe("conferences:create boolean input test", function () {
        it("tests that value false can be used with boolean flags and args", async () => {
            nock("https://www.freeclimb.com")
                .post(`/apiserver/Accounts/${await cred.accountId}/Conferences`, {
                    alias: "userInput-alias",
                    playBeep: "userInput-playBeep",
                    record: false,
                    waitUrl: "userInput-waitUrl",
                    statusCallbackUrl: "userInput-statusCallbackUrl",
                })
                .query({})
                .reply(200, testJson)
            const { stdout, stderr } = await runCommand([
                "conferences:create",
                "--alias",
                "userInput-alias",
                "--playBeep",
                "userInput-playBeep",
                "--record",
                "false",
                "--waitUrl",
                "userInput-waitUrl",
                "--statusCallbackUrl",
                "userInput-statusCallbackUrl",
            ])
            expect(stdout).to.contain(nockServerResponse)
        })

        it("tests incorrect record input results in exit code 2", async () => {
            const { error } = await runCommand(["conferences:create", "--record", "flse"])
            expect(error?.oclif?.exit).to.equal(2)
        })
    })
})

describe("conferences:create Status Test", function () {
    const testJsonStatus = ""

    const statusResponse = `Received a success code from FreeClimb. There is no further output.
`

    it("Test all required paramaters", async () => {
        nock("https://www.freeclimb.com")
            .post(`/apiserver/Accounts/${await cred.accountId}/Conferences`, {})
            .query({})
            .reply(204, testJsonStatus)
        const { stdout, stderr } = await runCommand(["conferences:create"])
        expect(stdout).to.contain(statusResponse)
    })
})
