/* WARNING: This file is automatically generated. Please edit the files in the /generation/tests directory. */
import { expect } from "chai"
import nock from "nock"
import { runCommand } from "@oclif/test"
import { cred } from "../../src/credentials.js"

const conferenceId = "userInput-conferenceId"

describe("conference-participants:list Data Test", function () {
    const testJson = {
        message: "Response from server",
    }

    const nockServerResponse = `{
  "message": "Response from server"
}`

    afterEach(() => {
        nock.cleanAll()
    })

    it("Test all required paramaters", async () => {
        nock("https://www.freeclimb.com")
            .get(
                `/apiserver/Accounts/${await cred.accountId}/Conferences/${conferenceId}/Participants`
            )
            .query({})
            .reply(200, testJson)
        const { stdout } = await runCommand([
            "conference-participants:list",
            "userInput-conferenceId",
        ])
        expect(stdout).to.contain(nockServerResponse)
    })

    it("Test Freeclimb Api error repsonce is process correctly without a suggestion", async () => {
        const testJsonErrorNoSuggestion = {
            code: 2,
            message: "Method Not Allowed",
            url: "https://docs.freeclimb.com/reference/error-and-warning-dictionary#2",
            details: {},
        }
        nock("https://www.freeclimb.com")
            .get(
                `/apiserver/Accounts/${await cred.accountId}/Conferences/${conferenceId}/Participants`
            )
            .query({})
            .reply(500, testJsonErrorNoSuggestion)
        const { error } = await runCommand([
            "conference-participants:list",
            "userInput-conferenceId",
        ])
        expect(error?.oclif?.exit).to.equal(3)
    })

    it("Sends API requests to the base URL from an environment variable", async () => {
        try {
            process.env.FREECLIMB_CLI_BASE_URL =
                "https://user-custom-domain.example.com/apiserver"
            nock("https://user-custom-domain.example.com")
                .get(
                    `/apiserver/Accounts/${await cred.accountId}/Conferences/${conferenceId}/Participants`
                )
                .query({})
                .reply(200, testJson)
            const { stdout } = await runCommand([
                "conference-participants:list",
                "userInput-conferenceId",
            ])
            expect(stdout).to.contain(nockServerResponse)
        } finally {
            delete process.env.FREECLIMB_CLI_BASE_URL
        }
    })

    it("Test Freeclimb Api error repsonce is process correctly with a suggestion", async () => {
        const testJsonErrorWithSuggestion = {
            code: 50,
            message: "Unauthorized To Make Request",
            url: "https://docs.freeclimb.com/reference/error-and-warning-dictionary#50",
            details: {},
        }
        nock("https://www.freeclimb.com")
            .get(
                `/apiserver/Accounts/${await cred.accountId}/Conferences/${conferenceId}/Participants`
            )
            .query({})
            .reply(500, testJsonErrorWithSuggestion)
        const { error } = await runCommand([
            "conference-participants:list",
            "userInput-conferenceId",
        ])
        expect(error?.oclif?.exit).to.equal(3)
    })

    it("Test parse error gets triggered when there is an additional argument", async () => {
        const { error } = await runCommand([
            "conference-participants:list",
            "userInput-conferenceId",
            "additionalArguments",
        ])
        expect(error?.oclif?.exit).to.equal(2)
    })

    it("Test error resulting in an unreadable response", async () => {
        nock("https://www.freeclimb.com")
            .get(
                `/apiserver/Accounts/${await cred.accountId}/Conferences/${conferenceId}/Participants`
            )
            .query({})
            .reply(200, undefined)
        const { error } = await runCommand([
            "conference-participants:list",
            "userInput-conferenceId",
        ])
        expect(error?.oclif?.exit).to.equal(3)
    })

    it("testing all query parameters and required body are sent through with request", async () => {
        nock("https://www.freeclimb.com")
            .get(
                `/apiserver/Accounts/${await cred.accountId}/Conferences/${conferenceId}/Participants`
            )
            .query({
                talk: true,
                listen: true,
            })
            .reply(200, testJson)
        const { stdout } = await runCommand([
            "conference-participants:list",
            "userInput-conferenceId",
            "--talk",
            "true",
            "--listen",
            "true",
        ])
        expect(stdout).to.contain(nockServerResponse)
    })

    describe("conference-participants:list query param flags", function () {
        it("required params and a query param is sent through with request-talk", async () => {
            nock("https://www.freeclimb.com")
                .get(
                    `/apiserver/Accounts/${await cred.accountId}/Conferences/${conferenceId}/Participants`
                )
                .query({
                    talk: true,
                })
                .reply(200, testJson)
            const { stdout } = await runCommand([
                "conference-participants:list",
                "userInput-conferenceId",
                "--talk",
                "true",
            ])
            expect(stdout).to.contain(nockServerResponse)
        })

        it("required params and a query param is sent through with request-listen", async () => {
            nock("https://www.freeclimb.com")
                .get(
                    `/apiserver/Accounts/${await cred.accountId}/Conferences/${conferenceId}/Participants`
                )
                .query({
                    listen: true,
                })
                .reply(200, testJson)
            const { stdout } = await runCommand([
                "conference-participants:list",
                "userInput-conferenceId",
                "--listen",
                "true",
            ])
            expect(stdout).to.contain(nockServerResponse)
        })
    })

    describe("conference-participants:list next flag test", function () {
        it("Tests return of Exit Code 3 when flag next is not available", async () => {
            try {
                delete process.env.FREECLIMB_CONFERENCE_PARTICIPANTS_LIST_NEXT
                nock("https://www.freeclimb.com")
                    .get(
                        `/apiserver/Accounts/${await cred.accountId}/Conferences/${conferenceId}/Participants`
                    )
                    .query({})
                    .reply(200, testJson)
                await runCommand([
                    "conference-participants:list",
                    "userInput-conferenceId",
                ])
                const { error } = await runCommand([
                    "conference-participants:list",
                    "userInput-conferenceId",
                    "--next",
                ])
                expect(error?.oclif?.exit).to.equal(3)
            } finally {
                delete process.env.FREECLIMB_CONFERENCE_PARTICIPANTS_LIST_NEXT
            }
        })

        it("Test flag next works as expected when available with on last page", async () => {
            const testJsonNext = {
                total: 1,
                start: 0,
                end: 0,
                page: 1,
                numPages: 1,
                pageSize: 100,
                nextPageUri: null,
            }
            const nockServerResponseNext = `== You are on the last page of output. ==`
            try {
                process.env.FREECLIMB_CONFERENCE_PARTICIPANTS_LIST_NEXT =
                    "636f6e666572656e63652d7061727469636970616e74733a6c697374"
                nock("https://www.freeclimb.com")
                    .get(
                        `/apiserver/Accounts/${await cred.accountId}/Conferences/${conferenceId}/Participants`
                    )
                    .query({
                        cursor: "636f6e666572656e63652d7061727469636970616e74733a6c697374",
                    })
                    .reply(200, testJsonNext)
                const { stdout } = await runCommand([
                    "conference-participants:list",
                    "userInput-conferenceId",
                    "--next",
                ])
                expect(stdout).to.contain(nockServerResponseNext)
            } finally {
                delete process.env.FREECLIMB_CONFERENCE_PARTICIPANTS_LIST_NEXT
            }
        })

        it("Test flag next works as expected when available with has more pages", async () => {
            const finalCursor = "freeClimbCLIAutomatedTestCursor"
            const testJsonNext2 = {
                total: 2,
                start: 0,
                end: 0,
                page: 1,
                numPages: 2,
                pageSize: 100,
                nextPageUri: `https://www.freeclimb.com/apiserver/Accounts/${await cred.accountId}/Conferences/${conferenceId}/Participants?cursor=${finalCursor}`,
            }
            const nockServerResponseNext2 = `== Currently on page 1. Run this command again with the -n flag to go to the next page. ==`
            try {
                process.env.FREECLIMB_CONFERENCE_PARTICIPANTS_LIST_NEXT =
                    "636f6e666572656e63652d7061727469636970616e74733a6c697374"
                nock("https://www.freeclimb.com")
                    .get(
                        `/apiserver/Accounts/${await cred.accountId}/Conferences/${conferenceId}/Participants`
                    )
                    .query({
                        cursor: "636f6e666572656e63652d7061727469636970616e74733a6c697374",
                    })
                    .reply(200, testJsonNext2)
                const { stdout } = await runCommand([
                    "conference-participants:list",
                    "userInput-conferenceId",
                    "--next",
                ])
                expect(stdout).to.contain(nockServerResponseNext2)
            } finally {
                delete process.env.FREECLIMB_CONFERENCE_PARTICIPANTS_LIST_NEXT
            }
        })

        it("Test error is caught when when using next flag and no reponse is given", async () => {
            try {
                process.env.FREECLIMB_CONFERENCE_PARTICIPANTS_LIST_NEXT =
                    "636f6e666572656e63652d7061727469636970616e74733a6c697374"
                nock("https://www.freeclimb.com")
                    .get(
                        `/apiserver/Accounts/${await cred.accountId}/Conferences/${conferenceId}/Participants`
                    )
                    .query({
                        cursor: "636f6e666572656e63652d7061727469636970616e74733a6c697374",
                    })
                    .reply(200, undefined)
                const { error } = await runCommand([
                    "conference-participants:list",
                    "userInput-conferenceId",
                    "--next",
                ])
                expect(error?.oclif?.exit).to.equal(3)
            } finally {
                delete process.env.FREECLIMB_CONFERENCE_PARTICIPANTS_LIST_NEXT
            }
        })
    })

    describe("conference-participants:list boolean input test", function () {
        it("tests that value false can be used with boolean flags and args", async () => {
            nock("https://www.freeclimb.com")
                .get(
                    `/apiserver/Accounts/${await cred.accountId}/Conferences/${conferenceId}/Participants`
                )
                .query({
                    talk: false,
                    listen: false,
                })
                .reply(200, testJson)
            const { stdout } = await runCommand([
                "conference-participants:list",
                "userInput-conferenceId",
                "--talk",
                "false",
                "--listen",
                "false",
            ])
            expect(stdout).to.contain(nockServerResponse)
        })

        it("tests incorrect talk input results in exit code 2", async () => {
            const { error } = await runCommand([
                "conference-participants:list",
                "userInput-conferenceId",
                "--talk",
                "flse",
            ])
            expect(error?.oclif?.exit).to.equal(2)
        })

        it("tests incorrect listen input results in exit code 2", async () => {
            const { error } = await runCommand([
                "conference-participants:list",
                "userInput-conferenceId",
                "--listen",
                "flse",
            ])
            expect(error?.oclif?.exit).to.equal(2)
        })
    })
})

describe("conference-participants:list Status Test", function () {
    const testJsonStatus = ""

    const statusResponse = `Received a success code from FreeClimb. There is no further output.
`

    afterEach(() => {
        nock.cleanAll()
    })

    it("Test all required paramaters", async () => {
        nock("https://www.freeclimb.com")
            .get(
                `/apiserver/Accounts/${await cred.accountId}/Conferences/${conferenceId}/Participants`
            )
            .query({})
            .reply(204, testJsonStatus)
        const { stdout } = await runCommand([
            "conference-participants:list",
            "userInput-conferenceId",
        ])
        expect(stdout).to.contain(statusResponse)
    })
})
