/* WARNING: This file is automatically generated. Please edit the files in the /generation/tests directory. */
import { expect } from "chai"
import { runCommand } from "@oclif/test"
import nock from "nock"
import { cred } from "../../src/credentials.js"

const conferenceId = "userInput-conferenceId"

describe("conferences:get Data Test", function () {
    const testJson = {
        message: "Response from server",
    }

    const nockServerResponse = `{
  "message": "Response from server"
}`

    it("Test all required paramaters", async () => {
        nock("https://www.freeclimb.com")
            .get(`/apiserver/Accounts/${await cred.accountId}/Conferences/${conferenceId}`)
            .query({})
            .reply(200, testJson)
        const { stdout, stderr } = await runCommand(["conferences:get", "userInput-conferenceId"])
        expect(stdout).to.contain(nockServerResponse)
    })

    const testJsonErrorNoSuggestion = {
        code: 2,
        message: "Method Not Allowed",
        url: "https://docs.freeclimb.com/reference/error-and-warning-dictionary#2",
        details: {},
    }

    const nockServerResponseErrorNoSuggestion = `starting test`

    it("Test Freeclimb Api error repsonce is process correctly without a suggestion", async () => {
        nock("https://www.freeclimb.com")
            .get(`/apiserver/Accounts/${await cred.accountId}/Conferences/${conferenceId}`)
            .query({})
            .reply(500, testJsonErrorNoSuggestion)
        const { error } = await runCommand(["conferences:get", "userInput-conferenceId"])
        expect(error?.oclif?.exit).to.equal(3)
    })

    it("Sends API requests to the base URL from an environment variable", async () => {
        const orig_FREECLIMB_CLI_BASE_URL = process.env.FREECLIMB_CLI_BASE_URL
        process.env.FREECLIMB_CLI_BASE_URL = "https://user-custom-domain.example.com/apiserver"
        nock("https://user-custom-domain.example.com")
            .get(`/apiserver/Accounts/${await cred.accountId}/Conferences/${conferenceId}`)
            .query({})
            .reply(200, testJson)
        try {
            const { stdout, stderr } = await runCommand([
                "conferences:get",
                "userInput-conferenceId",
            ])
            expect(stdout).to.contain(nockServerResponse)
        } finally {
            if (orig_FREECLIMB_CLI_BASE_URL === undefined) delete process.env.FREECLIMB_CLI_BASE_URL
            else process.env.FREECLIMB_CLI_BASE_URL = orig_FREECLIMB_CLI_BASE_URL
        }
    })

    const testJsonErrorWithSuggestion = {
        code: 50,
        message: "Unauthorized To Make Request",
        url: "https://docs.freeclimb.com/reference/error-and-warning-dictionary#50",
        details: {},
    }

    const nockServerResponseErrorWithSuggestion = `starting test`

    it("Test Freeclimb Api error repsonce is process correctly with a suggestion", async () => {
        nock("https://www.freeclimb.com")
            .get(`/apiserver/Accounts/${await cred.accountId}/Conferences/${conferenceId}`)
            .query({})
            .reply(500, testJsonErrorWithSuggestion)
        const { error } = await runCommand(["conferences:get", "userInput-conferenceId"])
        expect(error?.oclif?.exit).to.equal(3)
    })

    it("Test parse error gets triggered when there is an additional argument", async () => {
        const { error } = await runCommand([
            "conferences:get",
            "userInput-conferenceId",
            "additionalArguments",
        ])
        expect(error?.oclif?.exit).to.equal(2)
    })

    it("Test error resulting in an unreadable response", async () => {
        nock("https://www.freeclimb.com")
            .get(`/apiserver/Accounts/${await cred.accountId}/Conferences/${conferenceId}`)
            .query({})
            .reply(200, undefined)
        const { error } = await runCommand(["conferences:get", "userInput-conferenceId"])
        expect(error?.oclif?.exit).to.equal(3)
    })

    describe("conferences:get next flag test", function () {
        it("Tests return of Exit Code 3 when flag next is not available", async () => {
            const orig_FREECLIMB_CONFERENCES_GET_NEXT = process.env.FREECLIMB_CONFERENCES_GET_NEXT
            delete process.env.FREECLIMB_CONFERENCES_GET_NEXT
            nock("https://www.freeclimb.com")
                .get(`/apiserver/Accounts/${await cred.accountId}/Conferences/${conferenceId}`)
                .query({})
                .reply(200, testJson)
            try {
                await runCommand(["conferences:get", "userInput-conferenceId"])
                const { error } = await runCommand([
                    "conferences:get",
                    "userInput-conferenceId",
                    "--next",
                ])
                expect(error?.oclif?.exit).to.equal(3)
            } finally {
                if (orig_FREECLIMB_CONFERENCES_GET_NEXT === undefined)
                    delete process.env.FREECLIMB_CONFERENCES_GET_NEXT
                else
                    process.env.FREECLIMB_CONFERENCES_GET_NEXT = orig_FREECLIMB_CONFERENCES_GET_NEXT
            }
        })
    })
})

describe("conferences:get Status Test", function () {
    const testJsonStatus = ""

    const statusResponse = `Received a success code from FreeClimb. There is no further output.
`

    it("Test all required paramaters", async () => {
        nock("https://www.freeclimb.com")
            .get(`/apiserver/Accounts/${await cred.accountId}/Conferences/${conferenceId}`)
            .query({})
            .reply(204, testJsonStatus)
        const { stdout, stderr } = await runCommand(["conferences:get", "userInput-conferenceId"])
        expect(stdout).to.contain(statusResponse)
    })
})
