/* WARNING: This file is automatically generated. Please edit the files in the /generation/tests directory. */
import { expect } from "chai"
import { runCommand } from "@oclif/test"
import nock from "nock"
import { cred } from "../../src/credentials.js"

import { data } from "../../src/commands/data.js"
import { Environment } from "../../src/environment.js"

describe("incoming-numbers:list Data Test", function () {
    const testJson = {
        message: "Response from server",
    }

    const nockServerResponse = `{
  "message": "Response from server"
}`

    it("Test all required paramaters", async () => {
        nock("https://www.freeclimb.com")
            .get(`/apiserver/Accounts/${await cred.accountId}/IncomingPhoneNumbers`)
            .query({})
            .reply(200, testJson)
        const { stdout, stderr } = await runCommand(["incoming-numbers:list"])
        expect(stdout).to.contain(nockServerResponse)
    })

    const testJsonErrorNoSuggestion = {
        code: 2,
        message: "Method Not Allowed",
        url: "https://docs.freeclimb.com/reference/error-and-warning-dictionary#2",
        details: {},
    }

    const nockServerResponseErrorNoSuggestion = `starting test`

    it("Test Freeclimb Api error repsonce is process correctly without a suggestion", async () => {
        nock("https://www.freeclimb.com")
            .get(`/apiserver/Accounts/${await cred.accountId}/IncomingPhoneNumbers`)
            .query({})
            .reply(500, testJsonErrorNoSuggestion)
        const { error } = await runCommand(["incoming-numbers:list"])
        expect(error?.oclif?.exit).to.equal(3)
    })

    it("Sends API requests to the base URL from an environment variable", async () => {
        const orig_FREECLIMB_CLI_BASE_URL = process.env.FREECLIMB_CLI_BASE_URL
        process.env.FREECLIMB_CLI_BASE_URL = "https://user-custom-domain.example.com/apiserver"
        nock("https://user-custom-domain.example.com")
            .get(`/apiserver/Accounts/${await cred.accountId}/IncomingPhoneNumbers`)
            .query({})
            .reply(200, testJson)
        try {
            const { stdout, stderr } = await runCommand(["incoming-numbers:list"])
            expect(stdout).to.contain(nockServerResponse)
        } finally {
            if (orig_FREECLIMB_CLI_BASE_URL === undefined) delete process.env.FREECLIMB_CLI_BASE_URL
            else process.env.FREECLIMB_CLI_BASE_URL = orig_FREECLIMB_CLI_BASE_URL
        }
    })

    const testJsonErrorWithSuggestion = {
        code: 50,
        message: "Unauthorized To Make Request",
        url: "https://docs.freeclimb.com/reference/error-and-warning-dictionary#50",
        details: {},
    }

    const nockServerResponseErrorWithSuggestion = `starting test`

    it("Test Freeclimb Api error repsonce is process correctly with a suggestion", async () => {
        nock("https://www.freeclimb.com")
            .get(`/apiserver/Accounts/${await cred.accountId}/IncomingPhoneNumbers`)
            .query({})
            .reply(500, testJsonErrorWithSuggestion)
        const { error } = await runCommand(["incoming-numbers:list"])
        expect(error?.oclif?.exit).to.equal(3)
    })

    it("Test parse error gets triggered when there is an additional argument", async () => {
        const { error } = await runCommand(["incoming-numbers:list", "additionalArguments"])
        expect(error?.oclif?.exit).to.equal(2)
    })

    it("Test error resulting in an unreadable response", async () => {
        nock("https://www.freeclimb.com")
            .get(`/apiserver/Accounts/${await cred.accountId}/IncomingPhoneNumbers`)
            .query({})
            .reply(200, undefined)
        const { error } = await runCommand(["incoming-numbers:list"])
        expect(error?.oclif?.exit).to.equal(3)
    })

    it("testing all query parameters and required body are sent through with request", async () => {
        nock("https://www.freeclimb.com")
            .get(`/apiserver/Accounts/${await cred.accountId}/IncomingPhoneNumbers`)
            .query({
                phoneNumber: "userInput-phoneNumber",
                alias: "userInput-alias",
                applicationId: "userInput-applicationId",
                hasApplication: true,
                country: "userInput-country",
                region: "userInput-region",
                smsEnabled: true,
                voiceEnabled: true,
            })
            .reply(200, testJson)
        const { stdout, stderr } = await runCommand([
            "incoming-numbers:list",
            "--phoneNumber",
            "userInput-phoneNumber",
            "--alias",
            "userInput-alias",
            "--applicationId",
            "userInput-applicationId",
            "--hasApplication",
            "true",
            "--country",
            "userInput-country",
            "--region",
            "userInput-region",
            "--smsEnabled",
            "true",
            "--voiceEnabled",
            "true",
        ])
        expect(stdout).to.contain(nockServerResponse)
    })

    describe("incoming-numbers:list query param flags", function () {
        it("required params and a query param is sent through with request-phoneNumber", async () => {
            nock("https://www.freeclimb.com")
                .get(`/apiserver/Accounts/${await cred.accountId}/IncomingPhoneNumbers`)
                .query({
                    phoneNumber: "userInput-phoneNumber",
                })
                .reply(200, testJson)
            const { stdout, stderr } = await runCommand([
                "incoming-numbers:list",
                "--phoneNumber",
                "userInput-phoneNumber",
            ])
            expect(stdout).to.contain(nockServerResponse)
        })

        it("required params and a query param is sent through with request-alias", async () => {
            nock("https://www.freeclimb.com")
                .get(`/apiserver/Accounts/${await cred.accountId}/IncomingPhoneNumbers`)
                .query({
                    alias: "userInput-alias",
                })
                .reply(200, testJson)
            const { stdout, stderr } = await runCommand([
                "incoming-numbers:list",
                "--alias",
                "userInput-alias",
            ])
            expect(stdout).to.contain(nockServerResponse)
        })

        it("required params and a query param is sent through with request-applicationId", async () => {
            nock("https://www.freeclimb.com")
                .get(`/apiserver/Accounts/${await cred.accountId}/IncomingPhoneNumbers`)
                .query({
                    applicationId: "userInput-applicationId",
                })
                .reply(200, testJson)
            const { stdout, stderr } = await runCommand([
                "incoming-numbers:list",
                "--applicationId",
                "userInput-applicationId",
            ])
            expect(stdout).to.contain(nockServerResponse)
        })

        it("required params and a query param is sent through with request-hasApplication", async () => {
            nock("https://www.freeclimb.com")
                .get(`/apiserver/Accounts/${await cred.accountId}/IncomingPhoneNumbers`)
                .query({
                    hasApplication: true,
                })
                .reply(200, testJson)
            const { stdout, stderr } = await runCommand([
                "incoming-numbers:list",
                "--hasApplication",
                "true",
            ])
            expect(stdout).to.contain(nockServerResponse)
        })

        it("required params and a query param is sent through with request-country", async () => {
            nock("https://www.freeclimb.com")
                .get(`/apiserver/Accounts/${await cred.accountId}/IncomingPhoneNumbers`)
                .query({
                    country: "userInput-country",
                })
                .reply(200, testJson)
            const { stdout, stderr } = await runCommand([
                "incoming-numbers:list",
                "--country",
                "userInput-country",
            ])
            expect(stdout).to.contain(nockServerResponse)
        })

        it("required params and a query param is sent through with request-region", async () => {
            nock("https://www.freeclimb.com")
                .get(`/apiserver/Accounts/${await cred.accountId}/IncomingPhoneNumbers`)
                .query({
                    region: "userInput-region",
                })
                .reply(200, testJson)
            const { stdout, stderr } = await runCommand([
                "incoming-numbers:list",
                "--region",
                "userInput-region",
            ])
            expect(stdout).to.contain(nockServerResponse)
        })

        it("required params and a query param is sent through with request-smsEnabled", async () => {
            nock("https://www.freeclimb.com")
                .get(`/apiserver/Accounts/${await cred.accountId}/IncomingPhoneNumbers`)
                .query({
                    smsEnabled: true,
                })
                .reply(200, testJson)
            const { stdout, stderr } = await runCommand([
                "incoming-numbers:list",
                "--smsEnabled",
                "true",
            ])
            expect(stdout).to.contain(nockServerResponse)
        })

        it("required params and a query param is sent through with request-voiceEnabled", async () => {
            nock("https://www.freeclimb.com")
                .get(`/apiserver/Accounts/${await cred.accountId}/IncomingPhoneNumbers`)
                .query({
                    voiceEnabled: true,
                })
                .reply(200, testJson)
            const { stdout, stderr } = await runCommand([
                "incoming-numbers:list",
                "--voiceEnabled",
                "true",
            ])
            expect(stdout).to.contain(nockServerResponse)
        })
    })

    describe("incoming-numbers:list next flag test", function () {
        it("Tests return of Exit Code 3 when flag next is not available", async () => {
            const orig_FREECLIMB_INCOMING_NUMBERS_LIST_NEXT =
                process.env.FREECLIMB_INCOMING_NUMBERS_LIST_NEXT
            delete process.env.FREECLIMB_INCOMING_NUMBERS_LIST_NEXT
            nock("https://www.freeclimb.com")
                .get(`/apiserver/Accounts/${await cred.accountId}/IncomingPhoneNumbers`)
                .query({})
                .reply(200, testJson)
            try {
                await runCommand(["incoming-numbers:list"])
                const { error } = await runCommand(["incoming-numbers:list", "--next"])
                expect(error?.oclif?.exit).to.equal(3)
            } finally {
                if (orig_FREECLIMB_INCOMING_NUMBERS_LIST_NEXT === undefined)
                    delete process.env.FREECLIMB_INCOMING_NUMBERS_LIST_NEXT
                else
                    process.env.FREECLIMB_INCOMING_NUMBERS_LIST_NEXT =
                        orig_FREECLIMB_INCOMING_NUMBERS_LIST_NEXT
            }
        })

        const testJsonNext = {
            total: 1,
            start: 0,
            end: 0,
            page: 1,
            numPages: 1,
            pageSize: 100,
            nextPageUri: null,
        }

        const nockServerResponseNext = `== You are on the last page of output. ==`

        const testJsonNext2 = {
            total: 2,
            start: 0,
            end: 0,
            page: 1,
            numPages: 2,
            pageSize: 100,
            nextPageUri: "",
        }

        const nockServerResponseNext2 = `== Currently on page 1. Run this command again with the -n flag to go to the next page. ==`

        it("Test flag next works as expected when available with on last page", async () => {
            const orig_FREECLIMB_INCOMING_NUMBERS_LIST_NEXT =
                process.env.FREECLIMB_INCOMING_NUMBERS_LIST_NEXT
            process.env.FREECLIMB_INCOMING_NUMBERS_LIST_NEXT =
                "696e636f6d696e672d6e756d626572733a6c697374"
            nock("https://www.freeclimb.com")
                .get(`/apiserver/Accounts/${await cred.accountId}/IncomingPhoneNumbers`)
                .query({ cursor: "696e636f6d696e672d6e756d626572733a6c697374" })
                .reply(200, testJsonNext)
            try {
                const { stdout, stderr } = await runCommand(["incoming-numbers:list", "--next"])
                expect(stdout).to.contain(nockServerResponseNext)
            } finally {
                if (orig_FREECLIMB_INCOMING_NUMBERS_LIST_NEXT === undefined)
                    delete process.env.FREECLIMB_INCOMING_NUMBERS_LIST_NEXT
                else
                    process.env.FREECLIMB_INCOMING_NUMBERS_LIST_NEXT =
                        orig_FREECLIMB_INCOMING_NUMBERS_LIST_NEXT
            }
        })

        const finalCursor = "freeClimbCLIAutomatedTestCursor"

        before(() => {
            ;(async () => {
                testJsonNext2.nextPageUri = `https://www.freeclimb.com/apiserver/Accounts/${await cred.accountId}/IncomingPhoneNumbers?cursor=${finalCursor}`
            })()
        })
        after(() => {
            const dataDir = data.run([]).then(
                (dataDir) => {
                    const environment = new Environment(dataDir)
                    environment.clearString("FREECLIMB_INCOMING_NUMBERS_LIST_NEXT")
                },
                (reason) => console.log(reason),
            )
        })
        it("Test flag next works as expected when available with has more pages", async () => {
            const orig_FREECLIMB_INCOMING_NUMBERS_LIST_NEXT =
                process.env.FREECLIMB_INCOMING_NUMBERS_LIST_NEXT
            process.env.FREECLIMB_INCOMING_NUMBERS_LIST_NEXT =
                "696e636f6d696e672d6e756d626572733a6c697374"
            nock("https://www.freeclimb.com")
                .get(`/apiserver/Accounts/${await cred.accountId}/IncomingPhoneNumbers`)
                .query({ cursor: "696e636f6d696e672d6e756d626572733a6c697374" })
                .reply(200, testJsonNext2)
            try {
                const { stdout, stderr } = await runCommand(["incoming-numbers:list", "--next"])
                expect(stdout).to.contain(nockServerResponseNext2)
            } finally {
                if (orig_FREECLIMB_INCOMING_NUMBERS_LIST_NEXT === undefined)
                    delete process.env.FREECLIMB_INCOMING_NUMBERS_LIST_NEXT
                else
                    process.env.FREECLIMB_INCOMING_NUMBERS_LIST_NEXT =
                        orig_FREECLIMB_INCOMING_NUMBERS_LIST_NEXT
            }
        })

        it("Test error is caught when when using next flag and no reponse is given", async () => {
            const orig_FREECLIMB_INCOMING_NUMBERS_LIST_NEXT =
                process.env.FREECLIMB_INCOMING_NUMBERS_LIST_NEXT
            process.env.FREECLIMB_INCOMING_NUMBERS_LIST_NEXT =
                "696e636f6d696e672d6e756d626572733a6c697374"
            nock("https://www.freeclimb.com")
                .get(`/apiserver/Accounts/${await cred.accountId}/IncomingPhoneNumbers`)
                .query({ cursor: "696e636f6d696e672d6e756d626572733a6c697374" })
                .reply(200, undefined)
            try {
                const { error } = await runCommand(["incoming-numbers:list", "--next"])
                expect(error?.oclif?.exit).to.equal(3)
            } finally {
                if (orig_FREECLIMB_INCOMING_NUMBERS_LIST_NEXT === undefined)
                    delete process.env.FREECLIMB_INCOMING_NUMBERS_LIST_NEXT
                else
                    process.env.FREECLIMB_INCOMING_NUMBERS_LIST_NEXT =
                        orig_FREECLIMB_INCOMING_NUMBERS_LIST_NEXT
            }
        })
    })

    describe("incoming-numbers:list boolean input test", function () {
        it("tests that value false can be used with boolean flags and args", async () => {
            nock("https://www.freeclimb.com")
                .get(`/apiserver/Accounts/${await cred.accountId}/IncomingPhoneNumbers`)
                .query({
                    phoneNumber: "userInput-phoneNumber",
                    alias: "userInput-alias",
                    applicationId: "userInput-applicationId",
                    hasApplication: false,
                    country: "userInput-country",
                    region: "userInput-region",
                    smsEnabled: false,
                    voiceEnabled: false,
                })
                .reply(200, testJson)
            const { stdout, stderr } = await runCommand([
                "incoming-numbers:list",
                "--phoneNumber",
                "userInput-phoneNumber",
                "--alias",
                "userInput-alias",
                "--applicationId",
                "userInput-applicationId",
                "--hasApplication",
                "false",
                "--country",
                "userInput-country",
                "--region",
                "userInput-region",
                "--smsEnabled",
                "false",
                "--voiceEnabled",
                "false",
            ])
            expect(stdout).to.contain(nockServerResponse)
        })

        it("tests incorrect hasApplication input results in exit code 2", async () => {
            const { error } = await runCommand([
                "incoming-numbers:list",
                "--hasApplication",
                "flse",
            ])
            expect(error?.oclif?.exit).to.equal(2)
        })

        it("tests incorrect smsEnabled input results in exit code 2", async () => {
            const { error } = await runCommand(["incoming-numbers:list", "--smsEnabled", "flse"])
            expect(error?.oclif?.exit).to.equal(2)
        })

        it("tests incorrect voiceEnabled input results in exit code 2", async () => {
            const { error } = await runCommand(["incoming-numbers:list", "--voiceEnabled", "flse"])
            expect(error?.oclif?.exit).to.equal(2)
        })
    })
})

describe("incoming-numbers:list Status Test", function () {
    const testJsonStatus = ""

    const statusResponse = `Received a success code from FreeClimb. There is no further output.
`

    it("Test all required paramaters", async () => {
        nock("https://www.freeclimb.com")
            .get(`/apiserver/Accounts/${await cred.accountId}/IncomingPhoneNumbers`)
            .query({})
            .reply(204, testJsonStatus)
        const { stdout, stderr } = await runCommand(["incoming-numbers:list"])
        expect(stdout).to.contain(statusResponse)
    })
})
