/* WARNING: This file is automatically generated. Please edit the files in the /generation/tests directory. */
import { expect } from "chai"
import nock from "nock"
import { runCommand } from "@oclif/test"
import { cred } from "../../src/credentials.js"

const queueId = "userInput-queueId"

describe("queue-members:dequeue-head Data Test", function () {
    const testJson = {
        message: "Response from server",
    }

    const nockServerResponse = `{
  "message": "Response from server"
}`

    afterEach(() => {
        nock.cleanAll()
    })

    it("Test all required paramaters", async () => {
        nock("https://www.freeclimb.com")
            .post(
                `/apiserver/Accounts/${await cred.accountId}/Queues/${queueId}/Members/Front`
            )
            .query({})
            .reply(200, testJson)
        const { stdout } = await runCommand([
            "queue-members:dequeue-head",
            "userInput-queueId",
        ])
        expect(stdout).to.contain(nockServerResponse)
    })

    it("Test Freeclimb Api error repsonce is process correctly without a suggestion", async () => {
        const testJsonErrorNoSuggestion = {
            code: 2,
            message: "Method Not Allowed",
            url: "https://docs.freeclimb.com/reference/error-and-warning-dictionary#2",
            details: {},
        }
        nock("https://www.freeclimb.com")
            .post(
                `/apiserver/Accounts/${await cred.accountId}/Queues/${queueId}/Members/Front`
            )
            .query({})
            .reply(500, testJsonErrorNoSuggestion)
        const { error } = await runCommand([
            "queue-members:dequeue-head",
            "userInput-queueId",
        ])
        expect(error?.oclif?.exit).to.equal(3)
    })

    it("Sends API requests to the base URL from an environment variable", async () => {
        try {
            process.env.FREECLIMB_CLI_BASE_URL =
                "https://user-custom-domain.example.com/apiserver"
            nock("https://user-custom-domain.example.com")
                .post(
                    `/apiserver/Accounts/${await cred.accountId}/Queues/${queueId}/Members/Front`
                )
                .query({})
                .reply(200, testJson)
            const { stdout } = await runCommand([
                "queue-members:dequeue-head",
                "userInput-queueId",
            ])
            expect(stdout).to.contain(nockServerResponse)
        } finally {
            delete process.env.FREECLIMB_CLI_BASE_URL
        }
    })

    it("Test Freeclimb Api error repsonce is process correctly with a suggestion", async () => {
        const testJsonErrorWithSuggestion = {
            code: 50,
            message: "Unauthorized To Make Request",
            url: "https://docs.freeclimb.com/reference/error-and-warning-dictionary#50",
            details: {},
        }
        nock("https://www.freeclimb.com")
            .post(
                `/apiserver/Accounts/${await cred.accountId}/Queues/${queueId}/Members/Front`
            )
            .query({})
            .reply(500, testJsonErrorWithSuggestion)
        const { error } = await runCommand([
            "queue-members:dequeue-head",
            "userInput-queueId",
        ])
        expect(error?.oclif?.exit).to.equal(3)
    })

    it("Test parse error gets triggered when there is an additional argument", async () => {
        const { error } = await runCommand([
            "queue-members:dequeue-head",
            "userInput-queueId",
            "additionalArguments",
        ])
        expect(error?.oclif?.exit).to.equal(2)
    })

    it("Test error resulting in an unreadable response", async () => {
        nock("https://www.freeclimb.com")
            .post(
                `/apiserver/Accounts/${await cred.accountId}/Queues/${queueId}/Members/Front`
            )
            .query({})
            .reply(200, undefined)
        const { error } = await runCommand([
            "queue-members:dequeue-head",
            "userInput-queueId",
        ])
        expect(error?.oclif?.exit).to.equal(3)
    })

    describe("queue-members:dequeue-head next flag test", function () {
        it("Tests return of Exit Code 3 when flag next is not available", async () => {
            try {
                delete process.env.FREECLIMB_QUEUE_MEMBERS_DEQUEUE_HEAD_NEXT
                nock("https://www.freeclimb.com")
                    .post(
                        `/apiserver/Accounts/${await cred.accountId}/Queues/${queueId}/Members/Front`
                    )
                    .query({})
                    .reply(200, testJson)
                await runCommand([
                    "queue-members:dequeue-head",
                    "userInput-queueId",
                ])
                const { error } = await runCommand([
                    "queue-members:dequeue-head",
                    "userInput-queueId",
                    "--next",
                ])
                expect(error?.oclif?.exit).to.equal(3)
            } finally {
                delete process.env.FREECLIMB_QUEUE_MEMBERS_DEQUEUE_HEAD_NEXT
            }
        })
    })
})

describe("queue-members:dequeue-head Status Test", function () {
    const testJsonStatus = ""

    const statusResponse = `Received a success code from FreeClimb. There is no further output.
`

    afterEach(() => {
        nock.cleanAll()
    })

    it("Test all required paramaters", async () => {
        nock("https://www.freeclimb.com")
            .post(
                `/apiserver/Accounts/${await cred.accountId}/Queues/${queueId}/Members/Front`
            )
            .query({})
            .reply(204, testJsonStatus)
        const { stdout } = await runCommand([
            "queue-members:dequeue-head",
            "userInput-queueId",
        ])
        expect(stdout).to.contain(statusResponse)
    })
})
