/* WARNING: This file is automatically generated. Please edit the files in the /generation/tests directory. */
import { expect } from "chai"
import { runCommand } from "@oclif/test"
import nock from "nock"
import { cred } from "../../src/credentials.js"

import { data } from "../../src/commands/data.js"
import { Environment } from "../../src/environment.js"

describe("sms:list Data Test", function () {
    const testJson = {
        message: "Response from server",
    }

    const nockServerResponse = `{
  "message": "Response from server"
}`

    it("Test all required paramaters", async () => {
        nock("https://www.freeclimb.com")
            .get(`/apiserver/Accounts/${await cred.accountId}/Messages`)
            .query({})
            .reply(200, testJson)
        const { stdout, stderr } = await runCommand(["sms:list"])
        expect(stdout).to.contain(nockServerResponse)
    })

    const testJsonErrorNoSuggestion = {
        code: 2,
        message: "Method Not Allowed",
        url: "https://docs.freeclimb.com/reference/error-and-warning-dictionary#2",
        details: {},
    }

    const nockServerResponseErrorNoSuggestion = `starting test`

    it("Test Freeclimb Api error repsonce is process correctly without a suggestion", async () => {
        nock("https://www.freeclimb.com")
            .get(`/apiserver/Accounts/${await cred.accountId}/Messages`)
            .query({})
            .reply(500, testJsonErrorNoSuggestion)
        const { error } = await runCommand(["sms:list"])
        expect(error?.oclif?.exit).to.equal(3)
    })

    it("Sends API requests to the base URL from an environment variable", async () => {
        const orig_FREECLIMB_CLI_BASE_URL = process.env.FREECLIMB_CLI_BASE_URL
        process.env.FREECLIMB_CLI_BASE_URL = "https://user-custom-domain.example.com/apiserver"
        nock("https://user-custom-domain.example.com")
            .get(`/apiserver/Accounts/${await cred.accountId}/Messages`)
            .query({})
            .reply(200, testJson)
        try {
            const { stdout, stderr } = await runCommand(["sms:list"])
            expect(stdout).to.contain(nockServerResponse)
        } finally {
            if (orig_FREECLIMB_CLI_BASE_URL === undefined) delete process.env.FREECLIMB_CLI_BASE_URL
            else process.env.FREECLIMB_CLI_BASE_URL = orig_FREECLIMB_CLI_BASE_URL
        }
    })

    const testJsonErrorWithSuggestion = {
        code: 50,
        message: "Unauthorized To Make Request",
        url: "https://docs.freeclimb.com/reference/error-and-warning-dictionary#50",
        details: {},
    }

    const nockServerResponseErrorWithSuggestion = `starting test`

    it("Test Freeclimb Api error repsonce is process correctly with a suggestion", async () => {
        nock("https://www.freeclimb.com")
            .get(`/apiserver/Accounts/${await cred.accountId}/Messages`)
            .query({})
            .reply(500, testJsonErrorWithSuggestion)
        const { error } = await runCommand(["sms:list"])
        expect(error?.oclif?.exit).to.equal(3)
    })

    it("Test parse error gets triggered when there is an additional argument", async () => {
        const { error } = await runCommand(["sms:list", "additionalArguments"])
        expect(error?.oclif?.exit).to.equal(2)
    })

    it("Test error resulting in an unreadable response", async () => {
        nock("https://www.freeclimb.com")
            .get(`/apiserver/Accounts/${await cred.accountId}/Messages`)
            .query({})
            .reply(200, undefined)
        const { error } = await runCommand(["sms:list"])
        expect(error?.oclif?.exit).to.equal(3)
    })

    it("testing all query parameters and required body are sent through with request", async () => {
        nock("https://www.freeclimb.com")
            .get(`/apiserver/Accounts/${await cred.accountId}/Messages`)
            .query({
                to: "userInput-to",
                from: "userInput-from",
                beginTime: "userInput-beginTime",
                endTime: "userInput-endTime",
                direction: "userInput-direction",
            })
            .reply(200, testJson)
        const { stdout, stderr } = await runCommand([
            "sms:list",
            "--to",
            "userInput-to",
            "--from",
            "userInput-from",
            "--beginTime",
            "userInput-beginTime",
            "--endTime",
            "userInput-endTime",
            "--direction",
            "userInput-direction",
        ])
        expect(stdout).to.contain(nockServerResponse)
    })

    describe("sms:list query param flags", function () {
        it("required params and a query param is sent through with request-to", async () => {
            nock("https://www.freeclimb.com")
                .get(`/apiserver/Accounts/${await cred.accountId}/Messages`)
                .query({
                    to: "userInput-to",
                })
                .reply(200, testJson)
            const { stdout, stderr } = await runCommand(["sms:list", "--to", "userInput-to"])
            expect(stdout).to.contain(nockServerResponse)
        })

        it("required params and a query param is sent through with request-from", async () => {
            nock("https://www.freeclimb.com")
                .get(`/apiserver/Accounts/${await cred.accountId}/Messages`)
                .query({
                    from: "userInput-from",
                })
                .reply(200, testJson)
            const { stdout, stderr } = await runCommand(["sms:list", "--from", "userInput-from"])
            expect(stdout).to.contain(nockServerResponse)
        })

        it("required params and a query param is sent through with request-beginTime", async () => {
            nock("https://www.freeclimb.com")
                .get(`/apiserver/Accounts/${await cred.accountId}/Messages`)
                .query({
                    beginTime: "userInput-beginTime",
                })
                .reply(200, testJson)
            const { stdout, stderr } = await runCommand([
                "sms:list",
                "--beginTime",
                "userInput-beginTime",
            ])
            expect(stdout).to.contain(nockServerResponse)
        })

        it("required params and a query param is sent through with request-endTime", async () => {
            nock("https://www.freeclimb.com")
                .get(`/apiserver/Accounts/${await cred.accountId}/Messages`)
                .query({
                    endTime: "userInput-endTime",
                })
                .reply(200, testJson)
            const { stdout, stderr } = await runCommand([
                "sms:list",
                "--endTime",
                "userInput-endTime",
            ])
            expect(stdout).to.contain(nockServerResponse)
        })

        it("required params and a query param is sent through with request-direction", async () => {
            nock("https://www.freeclimb.com")
                .get(`/apiserver/Accounts/${await cred.accountId}/Messages`)
                .query({
                    direction: "userInput-direction",
                })
                .reply(200, testJson)
            const { stdout, stderr } = await runCommand([
                "sms:list",
                "--direction",
                "userInput-direction",
            ])
            expect(stdout).to.contain(nockServerResponse)
        })
    })

    describe("sms:list next flag test", function () {
        it("Tests return of Exit Code 3 when flag next is not available", async () => {
            const orig_FREECLIMB_SMS_LIST_NEXT = process.env.FREECLIMB_SMS_LIST_NEXT
            delete process.env.FREECLIMB_SMS_LIST_NEXT
            nock("https://www.freeclimb.com")
                .get(`/apiserver/Accounts/${await cred.accountId}/Messages`)
                .query({})
                .reply(200, testJson)
            try {
                await runCommand(["sms:list"])
                const { error } = await runCommand(["sms:list", "--next"])
                expect(error?.oclif?.exit).to.equal(3)
            } finally {
                if (orig_FREECLIMB_SMS_LIST_NEXT === undefined)
                    delete process.env.FREECLIMB_SMS_LIST_NEXT
                else process.env.FREECLIMB_SMS_LIST_NEXT = orig_FREECLIMB_SMS_LIST_NEXT
            }
        })

        const testJsonNext = {
            total: 1,
            start: 0,
            end: 0,
            page: 1,
            numPages: 1,
            pageSize: 100,
            nextPageUri: null,
        }

        const nockServerResponseNext = `== You are on the last page of output. ==`

        const testJsonNext2 = {
            total: 2,
            start: 0,
            end: 0,
            page: 1,
            numPages: 2,
            pageSize: 100,
            nextPageUri: "",
        }

        const nockServerResponseNext2 = `== Currently on page 1. Run this command again with the -n flag to go to the next page. ==`

        it("Test flag next works as expected when available with on last page", async () => {
            const orig_FREECLIMB_SMS_LIST_NEXT = process.env.FREECLIMB_SMS_LIST_NEXT
            process.env.FREECLIMB_SMS_LIST_NEXT = "736d733a6c697374"
            nock("https://www.freeclimb.com")
                .get(`/apiserver/Accounts/${await cred.accountId}/Messages`)
                .query({ cursor: "736d733a6c697374" })
                .reply(200, testJsonNext)
            try {
                const { stdout, stderr } = await runCommand(["sms:list", "--next"])
                expect(stdout).to.contain(nockServerResponseNext)
            } finally {
                if (orig_FREECLIMB_SMS_LIST_NEXT === undefined)
                    delete process.env.FREECLIMB_SMS_LIST_NEXT
                else process.env.FREECLIMB_SMS_LIST_NEXT = orig_FREECLIMB_SMS_LIST_NEXT
            }
        })

        const finalCursor = "freeClimbCLIAutomatedTestCursor"

        before(() => {
            ;(async () => {
                testJsonNext2.nextPageUri = `https://www.freeclimb.com/apiserver/Accounts/${await cred.accountId}/Messages?cursor=${finalCursor}`
            })()
        })
        after(() => {
            const dataDir = data.run([]).then(
                (dataDir) => {
                    const environment = new Environment(dataDir)
                    environment.clearString("FREECLIMB_SMS_LIST_NEXT")
                },
                (reason) => console.log(reason),
            )
        })
        it("Test flag next works as expected when available with has more pages", async () => {
            const orig_FREECLIMB_SMS_LIST_NEXT = process.env.FREECLIMB_SMS_LIST_NEXT
            process.env.FREECLIMB_SMS_LIST_NEXT = "736d733a6c697374"
            nock("https://www.freeclimb.com")
                .get(`/apiserver/Accounts/${await cred.accountId}/Messages`)
                .query({ cursor: "736d733a6c697374" })
                .reply(200, testJsonNext2)
            try {
                const { stdout, stderr } = await runCommand(["sms:list", "--next"])
                expect(stdout).to.contain(nockServerResponseNext2)
            } finally {
                if (orig_FREECLIMB_SMS_LIST_NEXT === undefined)
                    delete process.env.FREECLIMB_SMS_LIST_NEXT
                else process.env.FREECLIMB_SMS_LIST_NEXT = orig_FREECLIMB_SMS_LIST_NEXT
            }
        })

        it("Test error is caught when when using next flag and no reponse is given", async () => {
            const orig_FREECLIMB_SMS_LIST_NEXT = process.env.FREECLIMB_SMS_LIST_NEXT
            process.env.FREECLIMB_SMS_LIST_NEXT = "736d733a6c697374"
            nock("https://www.freeclimb.com")
                .get(`/apiserver/Accounts/${await cred.accountId}/Messages`)
                .query({ cursor: "736d733a6c697374" })
                .reply(200, undefined)
            try {
                const { error } = await runCommand(["sms:list", "--next"])
                expect(error?.oclif?.exit).to.equal(3)
            } finally {
                if (orig_FREECLIMB_SMS_LIST_NEXT === undefined)
                    delete process.env.FREECLIMB_SMS_LIST_NEXT
                else process.env.FREECLIMB_SMS_LIST_NEXT = orig_FREECLIMB_SMS_LIST_NEXT
            }
        })
    })
})

describe("sms:list Status Test", function () {
    const testJsonStatus = ""

    const statusResponse = `Received a success code from FreeClimb. There is no further output.
`

    it("Test all required paramaters", async () => {
        nock("https://www.freeclimb.com")
            .get(`/apiserver/Accounts/${await cred.accountId}/Messages`)
            .query({})
            .reply(204, testJsonStatus)
        const { stdout, stderr } = await runCommand(["sms:list"])
        expect(stdout).to.contain(statusResponse)
    })
})
