/* WARNING: This file is automatically generated. Please edit the files in the /generation/tests directory. */
import { expect } from "chai"
import { runCommand } from "@oclif/test"
import nock from "nock"
import { cred } from "../../src/credentials.js"

describe("sms:send Data Test", function () {
    const testJson = {
        message: "Response from server",
    }

    const nockServerResponse = `{
  "message": "Response from server"
}`

    it("Test all required paramaters", async () => {
        nock("https://www.freeclimb.com")
            .post(`/apiserver/Accounts/${await cred.accountId}/Messages`, {
                from: "userInput-from",
                to: "userInput-to",
                text: "userInput-text",
            })
            .query({})
            .reply(200, testJson)
        const { stdout, stderr } = await runCommand([
            "sms:send",
            "userInput-from",
            "userInput-to",
            "userInput-text",
        ])
        expect(stdout).to.contain(nockServerResponse)
    })

    const testJsonErrorNoSuggestion = {
        code: 2,
        message: "Method Not Allowed",
        url: "https://docs.freeclimb.com/reference/error-and-warning-dictionary#2",
        details: {},
    }

    const nockServerResponseErrorNoSuggestion = `starting test`

    it("Test Freeclimb Api error repsonce is process correctly without a suggestion", async () => {
        nock("https://www.freeclimb.com")
            .post(`/apiserver/Accounts/${await cred.accountId}/Messages`, {
                from: "userInput-from",
                to: "userInput-to",
                text: "userInput-text",
            })
            .query({})
            .reply(500, testJsonErrorNoSuggestion)
        const { error } = await runCommand([
            "sms:send",
            "userInput-from",
            "userInput-to",
            "userInput-text",
        ])
        expect(error?.oclif?.exit).to.equal(3)
    })

    it("Sends API requests to the base URL from an environment variable", async () => {
        const orig_FREECLIMB_CLI_BASE_URL = process.env.FREECLIMB_CLI_BASE_URL
        process.env.FREECLIMB_CLI_BASE_URL = "https://user-custom-domain.example.com/apiserver"
        nock("https://user-custom-domain.example.com")
            .post(`/apiserver/Accounts/${await cred.accountId}/Messages`, {
                from: "userInput-from",
                to: "userInput-to",
                text: "userInput-text",
            })
            .query({})
            .reply(200, testJson)
        try {
            const { stdout, stderr } = await runCommand([
                "sms:send",
                "userInput-from",
                "userInput-to",
                "userInput-text",
            ])
            expect(stdout).to.contain(nockServerResponse)
        } finally {
            if (orig_FREECLIMB_CLI_BASE_URL === undefined) delete process.env.FREECLIMB_CLI_BASE_URL
            else process.env.FREECLIMB_CLI_BASE_URL = orig_FREECLIMB_CLI_BASE_URL
        }
    })

    const testJsonErrorWithSuggestion = {
        code: 50,
        message: "Unauthorized To Make Request",
        url: "https://docs.freeclimb.com/reference/error-and-warning-dictionary#50",
        details: {},
    }

    const nockServerResponseErrorWithSuggestion = `starting test`

    it("Test Freeclimb Api error repsonce is process correctly with a suggestion", async () => {
        nock("https://www.freeclimb.com")
            .post(`/apiserver/Accounts/${await cred.accountId}/Messages`, {
                from: "userInput-from",
                to: "userInput-to",
                text: "userInput-text",
            })
            .query({})
            .reply(500, testJsonErrorWithSuggestion)
        const { error } = await runCommand([
            "sms:send",
            "userInput-from",
            "userInput-to",
            "userInput-text",
        ])
        expect(error?.oclif?.exit).to.equal(3)
    })

    it("Test parse error gets triggered when there is an additional argument", async () => {
        const { error } = await runCommand([
            "sms:send",
            "userInput-from",
            "userInput-to",
            "userInput-text",
            "additionalArguments",
        ])
        expect(error?.oclif?.exit).to.equal(2)
    })

    it("Test error resulting in an unreadable response", async () => {
        nock("https://www.freeclimb.com")
            .post(`/apiserver/Accounts/${await cred.accountId}/Messages`, {
                from: "userInput-from",
                to: "userInput-to",
                text: "userInput-text",
            })
            .query({})
            .reply(200, undefined)
        const { error } = await runCommand([
            "sms:send",
            "userInput-from",
            "userInput-to",
            "userInput-text",
        ])
        expect(error?.oclif?.exit).to.equal(3)
    })

    describe("sms:send body param flags", function () {
        it("required params and a body param is sent through with request-notificationUrl", async () => {
            nock("https://www.freeclimb.com")
                .post(`/apiserver/Accounts/${await cred.accountId}/Messages`, {
                    from: "userInput-from",
                    to: "userInput-to",
                    text: "userInput-text",
                    notificationUrl: "userInput-notificationUrl",
                })
                .query({})
                .reply(200, testJson)
            const { stdout, stderr } = await runCommand([
                "sms:send",
                "userInput-from",
                "userInput-to",
                "userInput-text",
                "--notificationUrl",
                "userInput-notificationUrl",
            ])
            expect(stdout).to.contain(nockServerResponse)
        })
    })

    describe("sms:send next flag test", function () {
        it("Tests return of Exit Code 3 when flag next is not available", async () => {
            const orig_FREECLIMB_SMS_SEND_NEXT = process.env.FREECLIMB_SMS_SEND_NEXT
            delete process.env.FREECLIMB_SMS_SEND_NEXT
            nock("https://www.freeclimb.com")
                .post(`/apiserver/Accounts/${await cred.accountId}/Messages`, {
                    from: "userInput-from",
                    to: "userInput-to",
                    text: "userInput-text",
                })
                .query({})
                .reply(200, testJson)
            try {
                await runCommand(["sms:send", "userInput-from", "userInput-to", "userInput-text"])
                const { error } = await runCommand([
                    "sms:send",
                    "userInput-from",
                    "userInput-to",
                    "userInput-text",
                    "--next",
                ])
                expect(error?.oclif?.exit).to.equal(3)
            } finally {
                if (orig_FREECLIMB_SMS_SEND_NEXT === undefined)
                    delete process.env.FREECLIMB_SMS_SEND_NEXT
                else process.env.FREECLIMB_SMS_SEND_NEXT = orig_FREECLIMB_SMS_SEND_NEXT
            }
        })
    })
})

describe("sms:send Status Test", function () {
    const testJsonStatus = ""

    const statusResponse = `Received a success code from FreeClimb. There is no further output.
`

    it("Test all required paramaters", async () => {
        nock("https://www.freeclimb.com")
            .post(`/apiserver/Accounts/${await cred.accountId}/Messages`, {
                from: "userInput-from",
                to: "userInput-to",
                text: "userInput-text",
            })
            .query({})
            .reply(204, testJsonStatus)
        const { stdout, stderr } = await runCommand([
            "sms:send",
            "userInput-from",
            "userInput-to",
            "userInput-text",
        ])
        expect(stdout).to.contain(statusResponse)
    })
})
