/* WARNING: This file is automatically generated. Please edit the files in the /generation/commands directory. */
import { Args, Command, Flags } from "@oclif/core"
import chalk from "chalk"
import { Output } from '../../output.js'
import { FreeClimbApi, FreeClimbResponse } from '../../freeclimb.js'
import * as Errors from '../../errors.js'
import { wrapJsonOutput } from '../../ui/format.js'
import { getOutputFormat } from '../../agent-config.js'
import { extractQuietIds, filterFieldsDeep, rejectControlChars, validateResourceId } from '../../validation.js'

export class applicationsDelete extends Command {
    static description = ` Delete the specified application. If this application's ID is assigned to any Incoming phone number, that relationship will be cleared.`
    static examples = [
        "<%= config.bin %> applications:delete AP1234567890abcdef1234567890abcdef12345678",
        "<%= config.bin %> applications:delete AP1234567890abcdef1234567890abcdef12345678 --dry-run",
    ]
    static flags = {
		next: Flags.boolean({hidden: true}),
		json: Flags.boolean({description: 'Output as JSON. Auto-enabled when stdout is not a TTY or FREECLIMB_OUTPUT_FORMAT=json is set.', default: false}),
		quiet: Flags.boolean({description: 'Output only resource IDs, one per line. Useful for piping into other commands.', default: false}),
		fields: Flags.string({description: 'Comma-separated list of fields to include in the response. Limits output to protect context windows when used by agents.'}),
		"dry-run": Flags.boolean({description: 'Validate the request without executing it. Shows what would be sent to the API.', default: false}),
		help: Flags.help({char: 'h'}),
	}
    
	static args = {
		applicationId: Args.string({description: "String that uniquely identifies this application resource.", required: true}),
	}

    async run() {
        const out = new Output(this)
        const {args, flags} = await this.parse(applicationsDelete)
        const outputFormat = getOutputFormat(flags.json)
        validateResourceId(args.applicationId, "applicationId")
        if (flags["dry-run"]) {
            const dryRunOutput = {
                dryRun: true,
                method: "DELETE",
                endpoint: `Applications/${args.applicationId}`,
                
                
            }
            if (outputFormat === "json") {
                out.out(JSON.stringify(dryRunOutput, null, 2))
            } else {
                out.out(chalk.yellow("DRY RUN - No API call will be made"))
                out.out(JSON.stringify(dryRunOutput, null, 2))
            }
            return
        }
        const fcApi = new FreeClimbApi(`Applications/${args.applicationId}`, true, this)
        const formatOutput = (data: any) => {
            const outputData = flags.fields ? filterFieldsDeep(data, flags.fields.split(",").map((f: string) => f.trim())) : data
            if (outputFormat === "json") {
                return JSON.stringify(wrapJsonOutput(outputData), null, 2)
            }
            out.render(outputData, { topic: "applications", command: "delete" })
            return null
        }
        const normalResponse = (response: FreeClimbResponse) => {
            if (response.status === 204) {
                if (flags.quiet) { return }
                if (outputFormat === "json") {
                    out.out(JSON.stringify(wrapJsonOutput(null, { command: "applications:delete", request: { method: "DELETE", endpoint: `Applications/${args.applicationId}` } }), null, 2))
                } else {
                    out.render(null, { topic: "applications", command: "delete" })
                }
            } else if (response.data) {
                if (flags.quiet) {
                    const ids = extractQuietIds(response.data, "applicationId")
                    if (ids) { out.out(ids) }
                    return
                }
                const result = formatOutput(response.data)
                if (result !== null) { out.out(result) }
            } else { throw new Errors.UndefinedResponseError() }
        }
        if(flags.next) {
            
                const error = new Errors.NoNextPage();
                this.error(error.message, { exit: error.code});
            
        }
        
        
        
        await fcApi.apiCall("DELETE", {}, normalResponse)
    
    }
}
