/* WARNING: This file is automatically generated. Please edit the files in the /generation/commands directory. */
import { Command, Flags } from "@oclif/core"
import chalk from "chalk"
import { Output } from "../../output"
import { FreeClimbApi, FreeClimbResponse } from "../../freeclimb"
import * as Errors from "../../errors"
import { wrapJsonOutput, getFormatterForTopic } from "../../ui/format"

export class applicationsList extends Command {
    static description = ` Retrieve a list of Applications associated with the specified account, sorted from latest created to oldest.`

    static flags = {
        alias: Flags.string({
            char: "a",
            description: "Return only applications with aliases that exactly match this value.",
            required: false,
        }),
        next: Flags.boolean({ char: "n", description: "Displays the next page of output." }),
        json: Flags.boolean({ description: "Output as JSON (for scripting/agents)", default: false }),
        help: Flags.help({ char: "h" }),
    }

    async run() {
        const out = new Output(this)
        const { flags } = await (async () => {
            try {
                return await this.parse(applicationsList)
            } catch (error) {
                const err = new Errors.ParseError(error)
                this.error(err.message, { exit: err.code })
            }
        })()
        const fcApi = new FreeClimbApi(`Applications`, true, this)
        const normalResponse = (response: FreeClimbResponse) => {
            if (response.status === 204) {
                out.out(
                    chalk.green(
                        "Received a success code from FreeClimb. There is no further output."
                    )
                )
            } else if (response.data) {
                if (flags.json) {
                out.out(JSON.stringify(wrapJsonOutput(response.data), null, 2))
            } else {
                const formatter = getFormatterForTopic("applications", "list")
                out.out(formatter ? formatter(response.data) : JSON.stringify(response.data, null, 2))
            }
            } else {
                throw new Errors.UndefinedResponseError()
            }
        }
        const nextResponse = (response: FreeClimbResponse) => {
            if (response.data) {
                if (flags.json) {
                out.out(JSON.stringify(wrapJsonOutput(response.data), null, 2))
            } else {
                const formatter = getFormatterForTopic("applications", "list")
                out.out(formatter ? formatter(response.data) : JSON.stringify(response.data, null, 2))
            }
            } else {
                throw new Errors.UndefinedResponseError()
            }
            if (out.next === null) {
                out.out("== You are on the last page of output. ==")
            }
        }

        if (flags.next) {
            if (out.next === undefined || out.next === "freeclimbUnnamedTest") {
                const error = new Errors.NoNextPage()
                this.error(error.message, { exit: error.code })
            } else {
                await fcApi.apiCall("GET", { params: { cursor: out.next } }, nextResponse)
            }
            return
        }

        await fcApi.apiCall(
            "GET",
            {
                params: {
                    alias: flags.alias,
                },
            },
            normalResponse
        )
    }
}
