/**
 * This file creates, or overrides, the src directory containing command
 * files which are used by the CLI. For each FreeClimb command, this file
 * composes a typescript file by creating an ApiCommand object and using
 * helper method to retrieve necessary components. generate-commands-files.js
 * is not a part of the CLI but rather a necessary component for generating
 * command files. Changes made to this file may affect generated command files.
 */
import fs from "node:fs"
import { exec } from "node:child_process"
import { fileURLToPath } from "node:url"
import { dirname } from "node:path"
import pkg from "lodash"
const { isEmpty } = pkg
import { readFileSync } from "node:fs"

const __filename = fileURLToPath(import.meta.url)
const __dirname = dirname(__filename)

const apiInfo = JSON.parse(readFileSync(new URL("../schema/generated-api-schema.json", import.meta.url), "utf-8"))
const descriptionOverrides = JSON.parse(readFileSync(new URL("../schema/description-overrides.json", import.meta.url), "utf-8"))
const localFlags = JSON.parse(readFileSync(new URL("../schema/local-flags.json", import.meta.url), "utf-8"))
const topicIdFields = JSON.parse(readFileSync(new URL("../schema/topic-id-fields.json", import.meta.url), "utf-8"))
const commandExamples = JSON.parse(readFileSync(new URL("../schema/examples.json", import.meta.url), "utf-8"))
import ApiCommand from "./api-command.js"
import mapChars from "./character-mapping.js"

// Mapping of the names of flags to the characters to use for those flags
const charMap = mapChars(apiInfo, localFlags)

let commandsWithTail = new Map()
commandsWithTail.set("logs", ["filter", "list"])

const hasPQLClassName = ["logsFilter"]

// Create src/commands if directory does not already exist
fs.mkdirSync("./src/commands", { recursive: true })

// Generated files to be linted
const generatedFiles = []

// Delete old topic descriptions from package.json
const packageFilepath = `${__dirname}/../../package.json`
const topicsKey = /( {2}"oclif": {[\s\S]* {2}"topics": {)([\s\S]*)(}[\s\S]*},\n {2}"do-not-move": {)/
let packageContents = fs.readFileSync(packageFilepath, "utf-8")
packageContents = packageContents.replace(topicsKey, "$1$3") // clears the previous contents of the topics key

// Create directories and files in /commands
apiInfo.forEach((topic, index, arr) => {
    // Create topic directory
    const path = `./src/commands/${topic.topic.replace(" ", "_")}`
    if (!fs.existsSync(path)) fs.mkdirSync(path)

    // Add topic description to package.json
    packageContents = packageContents.replace(
        topicsKey,
        `$1${index === arr.length - 1 ? "" : ","}"${
            topic.topic
        }": { "description": "${getTopicDescription(topic)
            .replace(/\n/g, " ")
            .replace(/"/g, '\\"')}" }$2$3`
    )

    // Create typescript files for each command in current topic
    topic.commands.forEach((command) => {
        const currentCommand = new ApiCommand(topic, command)
        const fileContents = getFileContents(currentCommand)

        const newFilepath = `${path}/${command.commandName}.ts`
        fs.writeFileSync(newFilepath, fileContents)
        generatedFiles.push(newFilepath)
    })
})

// Write to package.json
fs.writeFileSync(packageFilepath, JSON.stringify(JSON.parse(packageContents), null, 2)) // this is to beautify the output
generatedFiles.push(packageFilepath)

// Run linter on generated files
exec(
    `git add ${generatedFiles.join(
        " "
    )} && yarn lint-staged --allow-empty; git restore --staged ${generatedFiles.join(" ")}`,
    (err, stdout, stderr) => {
        // Stages to allow lint and then unstages
        if (err) {
            console.log("Linter errors were found.")
        }
        console.log(`stdout: ${stdout}`)
        console.log(`stderr: ${stderr}`)
    }
)

// Return description of topic
function getTopicDescription(topic) {
    let description = ""

    // First looks for description in descriptionOverrides
    // If not found, use description from apiInfo
    try {
        description = descriptionOverrides.topics[topic.topic].self
        if (!description) {
            throw new Error("No override exists")
        }
    } catch (error) {
        ;({ description } = topic)
    }

    return description
}

function includeTail(topic, command) {
    if (commandsWithTail.has(topic)) {
        let tailCommand = commandsWithTail.get(topic)
        if (tailCommand.includes(command)) {
            return true
        }
    }
    return false
}

// Return contents for the typescript file of current command
function isMutatingMethod(method) {
    return ["POST", "PUT", "DELETE", "PATCH"].includes(method.toUpperCase())
}

function getFileContents(command) {
    const tail = includeTail(command.topic, command.commandName)
    const isMutating = isMutatingMethod(command.method)
    return `/* WARNING: This file is automatically generated. Please edit the files in the /generation/commands directory. */
import { Args, Command, Flags } from "@oclif/core"
import chalk from "chalk"
import { Output } from '../../output.js'
import { FreeClimbApi, FreeClimbResponse } from '../../freeclimb.js'
import * as Errors from '../../errors.js'
import { wrapJsonOutput } from '../../ui/format.js'
import { getOutputFormat } from '../../agent-config.js'
import { extractQuietIds, filterFieldsDeep, rejectControlChars, validateResourceId } from '../../validation.js'
${
    tail
        ? `import { sleep, calculateSinceTimestamp } from "../../tail.js"\n\nlet lastTime: number\nlet tailMax: number\n`
        : ""
}
export class ${command.className} extends Command {
    static description = \`${command.description}\`
    ${getExamples(command.topic, command.name)}
    static flags = {${getAxiosFlags(command.flags)}${getAdditionalFlags(
        command.topic,
        tail,
        command.pagination,
        isMutating
    )}}
    ${getAxiosArgs(command.args, tail)}
    async run() {
        const out = new Output(this)
        const {${setConstArgs(command.args, tail)}flags} = await this.parse(${command.className})
        const outputFormat = getOutputFormat(flags.json)
        ${getInputValidation(command).trim()}
        ${isMutating ? getDryRunCheck(command).trim() : ""}
        const fcApi = new FreeClimbApi(\`${command.endpoint}\`, ${command.usesAuthentication}, this)
        const formatOutput = (data: any) => {
            const outputData = flags.fields ? filterFieldsDeep(data, flags.fields.split(",").map((f: string) => f.trim())) : data
            if (outputFormat === "json") {
                return JSON.stringify(wrapJsonOutput(outputData), null, 2)
            }
            out.render(outputData, { topic: "${command.topic}", command: "${command.name}" })
            return null
        }
        const normalResponse = (response: FreeClimbResponse) => {
            if (response.status === 204) {
                if (flags.quiet) { return }
                if (outputFormat === "json") {
                    out.out(JSON.stringify(wrapJsonOutput(null, { command: "${command.topic}:${command.name}", ${getRequestMetadata(command)} }), null, 2))
                } else {
                    out.render(null, { topic: "${command.topic}", command: "${command.name}" })
                }
            } else if (response.data) {
                if (flags.quiet) {
                    const ids = extractQuietIds(response.data, "${topicIdFields[command.topic] || "id"}")
                    if (ids) { out.out(ids) }
                    return
                }
                ${command.topic === "logs" ? `const processedData = flags.maxItem ? { ...response.data, logs: response.data.logs.splice(0, flags.maxItem) } : response.data
                const result = formatOutput(processedData)
                if (result !== null) { out.out(result) }` : `const result = formatOutput(response.data)
                if (result !== null) { out.out(result) }`}
            } else { throw new Errors.UndefinedResponseError() }
        }${tail ? getTailResponse() : ""}${
        command.pagination
            ? `
        const nextResponse = (response: FreeClimbResponse) => {
            if (response.data) {
                if (flags.quiet) {
                    const ids = extractQuietIds(response.data, "${topicIdFields[command.topic] || "id"}")
                    if (ids) { out.out(ids) }
                } else {
                    ${command.topic === "logs" ? `const result = formatOutput(flags.maxItem ? { ...response.data, logs: response.data.logs.splice(0, flags.maxItem) } : response.data)
                    if (result !== null) { out.out(result) }` : `const result = formatOutput(response.data)
                    if (result !== null) { out.out(result) }`}
                }
            } else { throw new Errors.UndefinedResponseError() }
            if(out.next === null && !flags.quiet) {
                out.out("== You are on the last page of output. ==")
            }
        }
        `
            : ""
    }
        if(flags.next) {
            ${
                command.pagination
                    ? `if(out.next === undefined || out.next === "freeclimbUnnamedTest") {`
                    : ""
            }
                const error = new Errors.NoNextPage();
                this.error(error.message, { exit: error.code});
            ${
                command.pagination
                    ? `
            }
            else {
                await fcApi.apiCall("GET", { params: {cursor: out.next} }, nextResponse)
            }
            return`
                    : ""
            }
        }
        ${getErrorHandling(command).trim()}
        ${getBooleanParams(command.booleanParams).trim()}
        ${tail ? getTailApi(command) : ""}
        await fcApi.apiCall("${command.method}", {${getAxiosParams(
        command.bodyParams,
        command.queryParams
    )}}, normalResponse)
    ${tail ? "}" : ""}
    }
}
`
}

// Return flags used in axios request
function getAxiosFlags(flags) {
    let data = ""

    flags.forEach((flag) => {
        data += `\n\t\t${flag.name}: Flags.${getFlagType(flag)}({\
            ${getAxiosFlagsCharHelper(flag)}\
            description: "${flag.description}", \
            required: ${flag.required}, \
            ${getAxiosFlagsBooleanHelper(flag)}}),`
    })

    return data
}

// Return type of flag
function getFlagType(flag) {
    return flag.dataType === "int32" ? "integer" : "string"
}

// Return char option for flags with chars
function getAxiosFlagsCharHelper(flag) {
    return charMap.has(flag.name) ? `char: "${charMap.get(flag.name)}",` : ""
}

// Return flag options for boolean parameters
function getAxiosFlagsBooleanHelper(flag) {
    return flag.dataType === "boolean" ? 'options: ["true", "false"]' : ""
}

// Return flags not used in axios request
function getAdditionalFlags(topicName, tail, pagination, isMutating) {
    let data = ""
    if (topicName === "logs") {
        data += `\n\t\tmaxItem: Flags.integer({ char: "m", description: "${localFlags.maxItem.description}"}),`
    }
    if (tail) {
        data += `\n\t\ttail: Flags.boolean({char: '${localFlags.tail.char}', description: '${localFlags.tail.description}',default : ${localFlags.tail.default}}),\n\t\tsleep: Flags.integer({ char: "${localFlags.sleep.char}", description: "${localFlags.sleep.description}", default: ${localFlags.sleep.default}}),\n\t\tsince: Flags.string({ char: "${localFlags.since.char}", description: "${localFlags.since.description}", dependsOn:${localFlags.since.dependsOn}}),`
    }
    if (pagination) {
        data += `\n\t\tnext: Flags.boolean({char: 'n', description: '${localFlags.next.description}'}),`
    } else {
        data += "\n\t\tnext: Flags.boolean({hidden: true}),"
    }

    data += `\n\t\tjson: Flags.boolean({description: 'Output as JSON. Auto-enabled when stdout is not a TTY or FREECLIMB_OUTPUT_FORMAT=json is set.', default: false}),`
    data += `\n\t\tquiet: Flags.boolean({description: 'Output only resource IDs, one per line. Useful for piping into other commands.', default: false}),`
    data += `\n\t\tfields: Flags.string({description: 'Comma-separated list of fields to include in the response. Limits output to protect context windows when used by agents.'}),`

    if (isMutating) {
        data += `\n\t\t"dry-run": Flags.boolean({description: 'Validate the request without executing it. Shows what would be sent to the API.', default: false}),`
    }

    data += "\n\t\thelp: Flags.help({char: 'h'}),\n\t"

    return data
}

// Return arguments used in Axios request
function getAxiosArgs(args, tail) {
    let data = ""

    if (!isEmpty(args) || tail) {
        data += "\n\tstatic args = {"
        args.forEach((arg) => {
            data += `\n\t\t${arg.name}: Args.string({description: "${arg.description}", required: ${arg.required}}),`
        })
        data += "\n\t}\n"
    }

    return data
}

// Add args to deconstructor if the command requires arguments
// "freeclimb topic:command -h" will not work if flags are not in deconstructor. So flags
// must be in the deconstructor even when no Axios flags are present.
function setConstArgs(args, tail) {
    return isEmpty(args) ? "" : "args, "
}

// Return Error Handling
function getErrorHandling(command) {
    let data = ""

    // If a update/manage command has a non-path argument, then the command will update that
    // attribute in freeclimb. Thus this should only be added if all arguments are path
    // parameters. This is relevant in calls:update
    if (
        (command.name === "update" || command.name === "manage") &&
        command.args.every((arg) => arg.paramType === "path")
    ) {
        data += createWarning(
            `Object.entries(flags).length === 0`,
            `Nothing Has Been Updated: Please enter a parameter to update ('freeclimb ${command.topic}:` +
                `${command.name} -h' for a list of parameters to be updated)`
        )
    }

    // Bounds for integer parameters
    command.integerParams.forEach((param) => {
        let { min, max } = getIntegerBounds(param)
        data += `const belowRangeError = new Errors.OutOfRange("${param.name}", ${min}, "greater")\n`
        data += `const aboveRangeError = new Errors.OutOfRange("${param.name}", ${max}, "less")\n`
        data += createError(
            `${accessSpecifier(param)}.${param.name} && ${accessSpecifier(param)}.${
                param.name
            } < ${min}`,
            `belowRangeError.message`,
            `belowRangeError.code`
        )
        data += createError(
            `${accessSpecifier(param)}.${param.name} && ${accessSpecifier(param)}.${
                param.name
            } > ${max}`,
            `aboveRangeError.message`,
            `aboveRangeError.code`
        )
    })

    // Aliases for available numbers are always in this format "123-456-7890"
    if (command.topic === "available-numbers" && command.name === "list") {
        data += createWarning(
            `flags.alias && !/\\d{3}-\\d{3}-\\d{4}/.test(flags.alias)`,
            `Incorrect Format: Please enter an alias in the format '123-456-7890'`
        )
    }

    if (hasPQLClassName.includes(command.className)) {
        data += createWarning(
            `args.pql.includes("'")`,
            `A single quote has been detected in your pql. Keep in mind that all strings must be encapsulated by double quotes for the pql to be valid. If this was a mistake, please rerun the command with your rewritten pql. The command will now run.`
        )
    }

    return data
}

// Return if statement that gives the user a error
function createError(conditional, errorMessage, exitCode) {
    return `if(${conditional}) { this.error(${errorMessage}, {exit: ${exitCode}}) }\n`
}

// Return if statement that gives the user a warning
function createWarning(conditional, errorMessage) {
    return `if(${conditional}) { this.warn(chalk.yellow("${errorMessage}"))}\n`
}

// Return integer bounds for specific parameter
function getIntegerBounds(flag) {
    // Freeclimb ignores parameter when 0 is passed to it
    switch (flag.name) {
        case "timeout":
            return {
                min: 0,
                max: 120,
            }
        case "maxSize":
            return {
                min: 0,
                max: 1000,
            }
    }
}

// Return boolean parsing logic for each boolean parameter
function getBooleanParams(booleanParams) {
    let data = ""

    if (!isEmpty(booleanParams)) {
        data += "\n"
        booleanParams.forEach((param) => {
            data += `// ${accessSpecifier(param)}.${param.name} === "true" sets ${
                param.name
            } to the boolean representation of the flag\n\t\t`
            data += `const ${param.name} = typeof ${accessSpecifier(param)}.${
                param.name
            }  === "undefined" ? undefined : ${accessSpecifier(param)}.${param.name} === "true"\n`
        })
    }

    return data
}

// Return body and query parameters to be added to the Axios request
function getAxiosParams(bodyParams, queryParams) {
    let data = ""

    if (!isEmpty(bodyParams)) {
        data += "data: {"
        bodyParams.forEach((param) => {
            data +=
                param.dataType === "boolean"
                    ? `\n\t\t\t\t${param.name}: ${param.name},`
                    : `\n\t\t\t\t${param.name}: ${accessSpecifier(param)}.${param.name},`
        })
        data += "\n\t\t\t},\n\t\t"
    }

    if (!isEmpty(queryParams)) {
        data += "params: {"

        queryParams.forEach((param) => {
            if (param.paramType === "query") {
                data +=
                    param.dataType === "boolean"
                        ? `\n\t\t\t\t${param.name}: ${param.name},`
                        : `\n\t\t\t\t${param.name}: ${accessSpecifier(param)}.${param.name},`
            }
        })
        data += "\n\t\t\t},\n\t\t"
    }

    return data
}


function getExamples(topic, commandName) {
    const key = `${topic}:${commandName}`
    const examples = commandExamples[key]
    if (!examples || examples.length === 0) return ""
    const items = examples.map((ex) => {
        const escaped = ex.replace("freeclimb ", "").replace(/"/g, '\\"')
        return `"<%= config.bin %> ${escaped}"`
    }).join(",\n        ")
    return `static examples = [\n        ${items},\n    ]`
}

function accessSpecifier(param) {
    return param.required ? "args" : "flags"
}

function getInputValidation(command) {
    let data = ""
    const idParams = command.params.filter(
        (p) => p.paramType === "path" || p.name.toLowerCase().endsWith("id")
    )
    if (idParams.length > 0) {
        for (const param of idParams) {
            const accessor = accessSpecifier(param)
            if (param.required) {
                data += `validateResourceId(${accessor}.${param.name}, "${param.name}")\n        `
            } else {
                data += `if (${accessor}.${param.name}) { validateResourceId(${accessor}.${param.name}, "${param.name}") }\n        `
            }
        }
    }
    const stringParams = command.params.filter(
        (p) =>
            p.dataType === "string" &&
            !p.name.toLowerCase().endsWith("id") &&
            p.paramType !== "path"
    )
    for (const param of stringParams) {
        const accessor = accessSpecifier(param)
        if (param.required) {
            data += `rejectControlChars(${accessor}.${param.name}, "${param.name}")\n        `
        } else {
            data += `if (${accessor}.${param.name}) { rejectControlChars(${accessor}.${param.name}, "${param.name}") }\n        `
        }
    }
    return data
}

function getRequestMetadata(command) {
    const bodyObj = command.bodyParams.length > 0
        ? `, body: {${command.bodyParams.map((p) => {
            if (p.dataType === "boolean") return `\n                        ${p.name}: typeof ${accessSpecifier(p)}.${p.name} === "undefined" ? undefined : ${accessSpecifier(p)}.${p.name} === "true"`
            return `\n                        ${p.name}: ${accessSpecifier(p)}.${p.name}`
        }).join(",")}\n                    }`
        : ""
    return `request: { method: "${command.method}", endpoint: \`${command.endpoint}\`${bodyObj} }`
}

function getDryRunCheck(command) {
    return `if (flags["dry-run"]) {
            const dryRunOutput = {
                dryRun: true,
                method: "${command.method}",
                endpoint: \`${command.endpoint}\`,
                ${command.bodyParams.length > 0 ? `body: {${command.bodyParams.map((p) => {
                    if (p.dataType === "boolean") return `\n                    ${p.name}: typeof ${accessSpecifier(p)}.${p.name} === "undefined" ? undefined : ${accessSpecifier(p)}.${p.name} === "true"`
                    return `\n                    ${p.name}: ${accessSpecifier(p)}.${p.name}`
                }).join(",")}
                },` : ""}
                ${command.queryParams.length > 0 ? `params: {${command.queryParams.filter((p) => p.paramType === "query").map((p) => {
                    if (p.dataType === "boolean") return `\n                    ${p.name}: typeof ${accessSpecifier(p)}.${p.name} === "undefined" ? undefined : ${accessSpecifier(p)}.${p.name} === "true"`
                    return `\n                    ${p.name}: ${accessSpecifier(p)}.${p.name}`
                }).join(",")}
                },` : ""}
            }
            if (outputFormat === "json") {
                out.out(JSON.stringify(dryRunOutput, null, 2))
            } else {
                out.out(chalk.yellow("DRY RUN - No API call will be made"))
                out.out(JSON.stringify(dryRunOutput, null, 2))
            }
            return
        }
        `
}

function getTailResponse() {
    return `\n
    const tailResponse = (response: FreeClimbResponse) => {
        if (response.data.end !== 0) {
            lastTime = response.data.logs[0].timestamp
            out.out(JSON.stringify(response.data.logs.splice(0, tailMax).reverse(), null, 2))
        }
    }
    `
}

function includesTimestamp() {
    return `if (args.pql.includes("timestamp")) {
        const err = new Errors.NoTimestamp()
        this.error(err.message, { exit: err.code })
    }\n`
}

function addToPQL() {
    return `${"${args.pql}"} AND `
}

function getTailApi(command) {
    const includesPQL = hasPQLClassName.includes(command.className)
    return `
    if (flags.tail) {
        lastTime = 0
        ${includesPQL ? includesTimestamp() : ""}
        if (flags.since) {
            const currentTime = Date.now() * 1000
            const sinceTimestamp = (() => {
                try {
                    return calculateSinceTimestamp(flags.since)
                } catch (error) {
                    const err = new Errors.SinceFormatError(error)
                    this.error(err.message, { exit: err.code })
                }
            })()
            lastTime = currentTime - sinceTimestamp
        }
        tailMax = flags.maxItem ? flags.maxItem : 100
        while (flags.tail) {
            await fcApi.apiCall(
                "POST",
                {
                    data: {
                        pql: ${"`"}${includesPQL ? addToPQL() : ""}timestamp>${"${lastTime}"}${"`"},
                    },
                },
                tailResponse
            )
            await sleep(flags.sleep)
            tailMax = 100
        }
    } else {
    `
}
