/* WARNING: This file is automatically generated. Please edit the files in the /generation/commands directory. */
import { Command, flags } from "@oclif/command"
import chalk from "chalk"
import { Output } from "../../output"
import { FreeClimbApi, FreeClimbResponse } from "../../freeclimb"
import * as Errors from "../../errors"
import { wrapJsonOutput, getFormatterForTopic } from "../../ui/format"
import { getOutputFormat } from "../../agent-config"
import { filterFieldsDeep, rejectControlChars, validateResourceId } from "../../validation"

export class conferenceParticipantsGet extends Command {
    static description = ` Retrieve a representation of the specified Conference Participant.`

    static flags = {
        next: flags.boolean({ hidden: true }),
        json: flags.boolean({
            description:
                "Output as structured JSON. Also enabled via FREECLIMB_OUTPUT_FORMAT=json env var.",
            default: false,
        }),
        fields: flags.string({
            description:
                "Comma-separated list of fields to include in the response. Limits output to protect context windows when used by agents.",
        }),
        help: flags.help({ char: "h" }),
    }

    static args = [
        {
            name: "conferenceId",
            description: "ID of the conference this participant is in.",
            required: true,
        },
        {
            name: "callId",
            description: "ID of the Call associated with this participant.",
            required: true,
        },
    ]

    async run() {
        const out = new Output(this)
        const { args, flags } = (() => {
            try {
                return this.parse(conferenceParticipantsGet)
            } catch (error) {
                const err = new Errors.ParseError(error)
                this.error(err.message, { exit: err.code })
            }
        })()
        const outputFormat = getOutputFormat(flags.json)
        validateResourceId(args.conferenceId, "conferenceId")
        validateResourceId(args.callId, "callId")

        const fcApi = new FreeClimbApi(
            `Conferences/${args.conferenceId}/Participants/${args.callId}`,
            true,
            this
        )
        const formatOutput = (data: any) => {
            const outputData = flags.fields
                ? filterFieldsDeep(
                      data,
                      flags.fields.split(",").map((f: string) => f.trim())
                  )
                : data
            if (outputFormat === "json") {
                return JSON.stringify(wrapJsonOutput(outputData), null, 2)
            }
            const formatter = getFormatterForTopic("conference-participants", "get")
            return formatter ? formatter(outputData) : JSON.stringify(outputData, null, 2)
        }
        const normalResponse = (response: FreeClimbResponse) => {
            if (response.status === 204) {
                if (outputFormat === "json") {
                    out.out(
                        JSON.stringify(
                            wrapJsonOutput(null, { command: "conference-participants:get" }),
                            null,
                            2
                        )
                    )
                } else {
                    out.out(
                        chalk.green(
                            "Received a success code from FreeClimb. There is no further output."
                        )
                    )
                }
            } else if (response.data) {
                out.out(formatOutput(response.data))
            } else {
                throw new Errors.UndefinedResponseError()
            }
        }
        if (flags.next) {
            const error = new Errors.NoNextPage()
            this.error(error.message, { exit: error.code })
        }

        await fcApi.apiCall("GET", {}, normalResponse)
    }
}
