/* WARNING: This file is automatically generated. Please edit the files in the /generation/commands directory. */
import { Args, Command, Flags } from "@oclif/core"
import chalk from "chalk"
import { Output } from "../../output.js"
import { FreeClimbApi, FreeClimbResponse } from "../../freeclimb.js"
import * as Errors from "../../errors.js"
import { wrapJsonOutput } from "../../ui/format.js"
import { getOutputFormat } from "../../agent-config.js"
import {
    extractQuietIds,
    filterFieldsDeep,
    rejectControlChars,
    validateResourceId,
} from "../../validation.js"

export class conferenceParticipantsList extends Command {
    static description = ` Retrieve a list of Participants in the specified Conference, sorted by date created, newest to oldest.`
    static examples = [
        "<%= config.bin %> conference-participants:list CF1234567890abcdef",
        "<%= config.bin %> conference-participants:list CF1234567890abcdef --json",
    ]

    static flags = {
        talk: Flags.string({
            char: "L",
            description: "Only show Participants with the talk privilege.",
            required: false,
            options: ["true", "false"],
        }),
        listen: Flags.string({
            char: "l",
            description: "Only show Participants with the listen privilege.",
            required: false,
            options: ["true", "false"],
        }),
        next: Flags.boolean({ char: "n", description: "Displays the next page of output." }),
        json: Flags.boolean({
            description:
                "Output as JSON. Auto-enabled when stdout is not a TTY or FREECLIMB_OUTPUT_FORMAT=json is set.",
            default: false,
        }),
        quiet: Flags.boolean({
            description:
                "Output only resource IDs, one per line. Useful for piping into other commands.",
            default: false,
        }),
        fields: Flags.string({
            description:
                "Comma-separated list of fields to include in the response. Limits output to protect context windows when used by agents.",
        }),
        help: Flags.help({ char: "h" }),
    }

    static args = {
        conferenceId: Args.string({
            description: "ID of the conference this participant is in.",
            required: true,
        }),
    }

    async run() {
        const out = new Output(this)
        const { args, flags } = await this.parse(conferenceParticipantsList)
        const outputFormat = getOutputFormat(flags.json)
        validateResourceId(args.conferenceId, "conferenceId")

        const fcApi = new FreeClimbApi(`Conferences/${args.conferenceId}/Participants`, true, this)
        const formatOutput = (data: any) => {
            const outputData = flags.fields
                ? filterFieldsDeep(
                      data,
                      flags.fields.split(",").map((f: string) => f.trim()),
                  )
                : data
            if (outputFormat === "json") {
                return JSON.stringify(wrapJsonOutput(outputData), null, 2)
            }
            out.render(outputData, { topic: "conference-participants", command: "list" })
            return null
        }
        const normalResponse = (response: FreeClimbResponse) => {
            if (response.status === 204) {
                if (flags.quiet) {
                    return
                }
                if (outputFormat === "json") {
                    out.out(
                        JSON.stringify(
                            wrapJsonOutput(null, {
                                command: "conference-participants:list",
                                request: {
                                    method: "GET",
                                    endpoint: `Conferences/${args.conferenceId}/Participants`,
                                },
                            }),
                            null,
                            2,
                        ),
                    )
                } else {
                    out.render(null, { topic: "conference-participants", command: "list" })
                }
            } else if (response.data) {
                if (flags.quiet) {
                    const ids = extractQuietIds(response.data, "callId")
                    if (ids) {
                        out.out(ids)
                    }
                    return
                }
                const result = formatOutput(response.data)
                if (result !== null) {
                    out.out(result)
                }
            } else {
                throw new Errors.UndefinedResponseError()
            }
        }
        const nextResponse = (response: FreeClimbResponse) => {
            if (response.data) {
                if (flags.quiet) {
                    const ids = extractQuietIds(response.data, "callId")
                    if (ids) {
                        out.out(ids)
                    }
                } else {
                    const result = formatOutput(response.data)
                    if (result !== null) {
                        out.out(result)
                    }
                }
            } else {
                throw new Errors.UndefinedResponseError()
            }
            if (out.next === null && !flags.quiet) {
                out.out("== You are on the last page of output. ==")
            }
        }

        if (flags.next) {
            if (out.next === undefined || out.next === "freeclimbUnnamedTest") {
                const error = new Errors.NoNextPage()
                this.error(error.message, { exit: error.code })
            } else {
                await fcApi.apiCall("GET", { params: { cursor: out.next } }, nextResponse)
            }
            return
        }

        // flags.talk === "true" sets talk to the boolean representation of the flag
        const talk = typeof flags.talk === "undefined" ? undefined : flags.talk === "true"
        // flags.listen === "true" sets listen to the boolean representation of the flag
        const listen = typeof flags.listen === "undefined" ? undefined : flags.listen === "true"

        await fcApi.apiCall(
            "GET",
            {
                params: {
                    talk: talk,
                    listen: listen,
                },
            },
            normalResponse,
        )
    }
}
