/* WARNING: This file is automatically generated. Please edit the files in the /generation/commands directory. */
import { Command, flags } from "@oclif/command"
import chalk from "chalk"
import { Output } from "../../output"
import { FreeClimbApi, FreeClimbResponse } from "../../freeclimb"
import * as Errors from "../../errors"
import { wrapJsonOutput, getFormatterForTopic } from "../../ui/format"
import { getOutputFormat } from "../../agent-config"
import { filterFieldsDeep, rejectControlChars, validateResourceId } from "../../validation"

export class queueMembersDequeueHead extends Command {
    static description = ` Dequeue the Member at the head of the Queue. The Member's Call will begin executing the PerCL script returned from the callback specified in the actionUrl parameter when the Member was added.`

    static flags = {
        next: flags.boolean({ hidden: true }),
        json: flags.boolean({
            description:
                "Output as structured JSON. Also enabled via FREECLIMB_OUTPUT_FORMAT=json env var.",
            default: false,
        }),
        fields: flags.string({
            description:
                "Comma-separated list of fields to include in the response. Limits output to protect context windows when used by agents.",
        }),
        "dry-run": flags.boolean({
            description:
                "Validate the request without executing it. Shows what would be sent to the API.",
            default: false,
        }),
        help: flags.help({ char: "h" }),
    }

    static args = [
        {
            name: "queueId",
            description: "String that uniquely identifies this queue resource.",
            required: true,
        },
    ]

    async run() {
        const out = new Output(this)
        const { args, flags } = (() => {
            try {
                return this.parse(queueMembersDequeueHead)
            } catch (error) {
                const err = new Errors.ParseError(error)
                this.error(err.message, { exit: err.code })
            }
        })()
        const outputFormat = getOutputFormat(flags.json)
        validateResourceId(args.queueId, "queueId")
        if (flags["dry-run"]) {
            const dryRunOutput = {
                dryRun: true,
                method: "POST",
                endpoint: `Queues/${args.queueId}/Members/Front`,
            }
            if (outputFormat === "json") {
                out.out(JSON.stringify(dryRunOutput, null, 2))
            } else {
                out.out(chalk.yellow("DRY RUN - No API call will be made"))
                out.out(JSON.stringify(dryRunOutput, null, 2))
            }
            return
        }
        const fcApi = new FreeClimbApi(`Queues/${args.queueId}/Members/Front`, true, this)
        const formatOutput = (data: any) => {
            const outputData = flags.fields
                ? filterFieldsDeep(
                      data,
                      flags.fields.split(",").map((f: string) => f.trim())
                  )
                : data
            if (outputFormat === "json") {
                return JSON.stringify(wrapJsonOutput(outputData), null, 2)
            }
            const formatter = getFormatterForTopic("queue-members", "dequeue-head")
            return formatter ? formatter(outputData) : JSON.stringify(outputData, null, 2)
        }
        const normalResponse = (response: FreeClimbResponse) => {
            if (response.status === 204) {
                if (outputFormat === "json") {
                    out.out(
                        JSON.stringify(
                            wrapJsonOutput(null, { command: "queue-members:dequeue-head" }),
                            null,
                            2
                        )
                    )
                } else {
                    out.out(
                        chalk.green(
                            "Received a success code from FreeClimb. There is no further output."
                        )
                    )
                }
            } else if (response.data) {
                out.out(formatOutput(response.data))
            } else {
                throw new Errors.UndefinedResponseError()
            }
        }
        if (flags.next) {
            const error = new Errors.NoNextPage()
            this.error(error.message, { exit: error.code })
        }

        await fcApi.apiCall("POST", {}, normalResponse)
    }
}
