/* WARNING: This file is automatically generated. Please edit the files in the /generation/commands directory. */
import { Args, Command, Flags } from "@oclif/core"
import chalk from "chalk"
import { Output } from '../../output'
import { FreeClimbApi, FreeClimbResponse } from '../../freeclimb'
import * as Errors from '../../errors'
import { wrapJsonOutput } from '../../ui/format'
import { getOutputFormat } from '../../agent-config'
import { extractQuietIds, filterFieldsDeep, rejectControlChars, validateResourceId } from '../../validation'

export class queueMembersDequeueHead extends Command {
    static description = ` Dequeue the Member at the head of the Queue. The Member's Call will begin executing the PerCL script returned from the callback specified in the actionUrl parameter when the Member was added.`
    static examples = [
        "<%= config.bin %> queue-members:dequeue-head QU1234567890abcdef",
        "<%= config.bin %> queue-members:dequeue-head QU1234567890abcdef --dry-run",
    ]
    static flags = {
		next: Flags.boolean({hidden: true}),
		json: Flags.boolean({description: 'Output as JSON. Auto-enabled when stdout is not a TTY or FREECLIMB_OUTPUT_FORMAT=json is set.', default: false}),
		quiet: Flags.boolean({description: 'Output only resource IDs, one per line. Useful for piping into other commands.', default: false}),
		fields: Flags.string({description: 'Comma-separated list of fields to include in the response. Limits output to protect context windows when used by agents.'}),
		"dry-run": Flags.boolean({description: 'Validate the request without executing it. Shows what would be sent to the API.', default: false}),
		help: Flags.help({char: 'h'}),
	}
    
	static args = {
		queueId: Args.string({description: "String that uniquely identifies this queue resource.", required: true}),
	}

    async run() {
        const out = new Output(this)
        const {args, flags} = await this.parse(queueMembersDequeueHead)
        const outputFormat = getOutputFormat(flags.json)
        validateResourceId(args.queueId, "queueId")
        if (flags["dry-run"]) {
            const dryRunOutput = {
                dryRun: true,
                method: "POST",
                endpoint: `Queues/${args.queueId}/Members/Front`,
                
                
            }
            if (outputFormat === "json") {
                out.out(JSON.stringify(dryRunOutput, null, 2))
            } else {
                out.out(chalk.yellow("DRY RUN - No API call will be made"))
                out.out(JSON.stringify(dryRunOutput, null, 2))
            }
            return
        }
        const fcApi = new FreeClimbApi(`Queues/${args.queueId}/Members/Front`, true, this)
        const formatOutput = (data: any) => {
            const outputData = flags.fields ? filterFieldsDeep(data, flags.fields.split(",").map((f: string) => f.trim())) : data
            if (outputFormat === "json") {
                return JSON.stringify(wrapJsonOutput(outputData), null, 2)
            }
            out.render(outputData, { topic: "queue-members", command: "dequeue-head" })
            return null
        }
        const normalResponse = (response: FreeClimbResponse) => {
            if (response.status === 204) {
                if (flags.quiet) { return }
                if (outputFormat === "json") {
                    out.out(JSON.stringify(wrapJsonOutput(null, { command: "queue-members:dequeue-head" }), null, 2))
                } else {
                    out.render(null, { topic: "queue-members", command: "dequeue-head" })
                }
            } else if (response.data) {
                if (flags.quiet) {
                    const ids = extractQuietIds(response.data, "callId")
                    if (ids) { out.out(ids) }
                    return
                }
                const result = formatOutput(response.data)
                if (result !== null) { out.out(result) }
            } else { throw new Errors.UndefinedResponseError() }
        }
        if(flags.next) {
            
                const error = new Errors.NoNextPage();
                this.error(error.message, { exit: error.code});
            
        }
        
        
        
        await fcApi.apiCall("POST", {}, normalResponse)
    
    }
}
