/* WARNING: This file is automatically generated. Please edit the files in the /generation/commands directory. */
import { Command, flags } from "@oclif/command"
import chalk from "chalk"
import { Output } from '../../output'
import { FreeClimbApi, FreeClimbResponse } from '../../freeclimb'
import * as Errors from '../../errors'
import { wrapJsonOutput, getFormatterForTopic } from '../../ui/format'
import { getOutputFormat } from '../../agent-config'
import { filterFieldsDeep, rejectControlChars, validateResourceId } from '../../validation'

export class queueMembersGetHead extends Command {
    static description = ` Retrieve a representation of the Queue Member currently at the head of the Queue.`
    
    static flags = {
		next: flags.boolean({hidden: true}),
		json: flags.boolean({description: 'Output as JSON. Auto-enabled when stdout is not a TTY or FREECLIMB_OUTPUT_FORMAT=json is set.', default: false}),
		fields: flags.string({description: 'Comma-separated list of fields to include in the response. Limits output to protect context windows when used by agents.'}),
		help: flags.help({char: 'h'}),
	}
    
	static args = [		{name: "queueId", description: "String that uniquely identifies the Queue that the Member belongs to.", required: true},
]

    async run() {
        const out = new Output(this)
        const {args, flags} = (() => {
            try {
                return this.parse(queueMembersGetHead)
            } catch(error) {
                const err = new Errors.ParseError(error)
                this.error(err.message, { exit: err.code })
            }
        })()
        const outputFormat = getOutputFormat(flags.json)
        validateResourceId(args.queueId, "queueId")
        
        const fcApi = new FreeClimbApi(`Queues/${args.queueId}/Members/Front`, true, this)
        const formatOutput = (data: any) => {
            const outputData = flags.fields ? filterFieldsDeep(data, flags.fields.split(",").map((f: string) => f.trim())) : data
            if (outputFormat === "json") {
                return JSON.stringify(wrapJsonOutput(outputData), null, 2)
            }
            const formatter = getFormatterForTopic("queue-members", "get-head")
            return formatter ? formatter(outputData) : JSON.stringify(outputData, null, 2)
        }
        const normalResponse = (response: FreeClimbResponse) => {
            if (response.status === 204) {
                if (outputFormat === "json") {
                    out.out(JSON.stringify(wrapJsonOutput(null, { command: "queue-members:get-head" }), null, 2))
                } else {
                    out.out(chalk.green("Received a success code from FreeClimb. There is no further output."))
                }
            } else if (response.data) {
                out.out(formatOutput(response.data))
            } else { throw new Errors.UndefinedResponseError() }
        }
        if(flags.next) {
            
                const error = new Errors.NoNextPage();
                this.error(error.message, { exit: error.code});
            
        }
        
        await fcApi.apiCall("GET", {}, normalResponse)
    
    }
}
