/* WARNING: This file is automatically generated. Please edit the files in the /generation/commands directory. */
import { Command, Flags } from "@oclif/core"
import chalk from "chalk"
import { Output } from "../../output"
import { FreeClimbApi, FreeClimbResponse } from "../../freeclimb"
import * as Errors from "../../errors"
import { wrapJsonOutput, getFormatterForTopic } from "../../ui/format"

export class conferencesCreate extends Command {
    static description = ` Create an empty Conference within the specified account.`

    static flags = {
        alias: Flags.string({
            char: "a",
            description: "A description for this Conference. Maximum 64 characters.",
            required: false,
        }),
        playBeep: Flags.string({
            char: "b",
            description:
                "Controls when a beep is played. Valid values: always, never, entryOnly, exitOnly.",
            required: false,
        }),
        record: Flags.string({
            char: "r",
            description: "Setting to true records the entire Conference.",
            required: false,
            options: ["true", "false"],
        }),
        waitUrl: Flags.string({
            char: "w",
            description:
                "If specified, a URL for the audio file that provides custom hold music for the Conference when it is in the populated state. Otherwise, FreeClimb uses a system default audio file. This is always fetched using HTTP GET and is fetched just once - when the Conference is created.",
            required: false,
        }),
        statusCallbackUrl: Flags.string({
            char: "s",
            description: "This URL is invoked when the status of the Conference changes.",
            required: false,
        }),
        next: Flags.boolean({ hidden: true }),
        json: Flags.boolean({ description: "Output as JSON (for scripting/agents)", default: false }),
        help: Flags.help({ char: "h" }),
    }

    async run() {
        const out = new Output(this)
        const { flags } = await (async () => {
            try {
                return await this.parse(conferencesCreate)
            } catch (error) {
                const err = new Errors.ParseError(error)
                this.error(err.message, { exit: err.code })
            }
        })()
        const fcApi = new FreeClimbApi(`Conferences`, true, this)
        const normalResponse = (response: FreeClimbResponse) => {
            if (response.status === 204) {
                out.out(
                    chalk.green(
                        "Received a success code from FreeClimb. There is no further output."
                    )
                )
            } else if (response.data) {
                if (flags.json) {
                out.out(JSON.stringify(wrapJsonOutput(response.data), null, 2))
            } else {
                const formatter = getFormatterForTopic("conferences", "create")
                out.out(formatter ? formatter(response.data) : JSON.stringify(response.data, null, 2))
            }
            } else {
                throw new Errors.UndefinedResponseError()
            }
        }
        if (flags.next) {
            const error = new Errors.NoNextPage()
            this.error(error.message, { exit: error.code })
        }

        // flags.record === "true" sets record to the boolean representation of the flag
        const record = typeof flags.record === "undefined" ? undefined : flags.record === "true"

        await fcApi.apiCall(
            "POST",
            {
                data: {
                    alias: flags.alias,
                    playBeep: flags.playBeep,
                    record: record,
                    waitUrl: flags.waitUrl,
                    statusCallbackUrl: flags.statusCallbackUrl,
                },
            },
            normalResponse
        )
    }
}
