/* WARNING: This file is automatically generated. Please edit the files in the /generation/commands directory. */
import { Command, flags } from "@oclif/command"
import chalk from "chalk"
import { Output } from "../../output"
import { FreeClimbApi, FreeClimbResponse } from "../../freeclimb"
import * as Errors from "../../errors"
import { wrapJsonOutput, getFormatterForTopic } from "../../ui/format"
import { getOutputFormat } from "../../agent-config"
import { filterFieldsDeep, rejectControlChars, validateResourceId } from "../../validation"

export class conferencesCreate extends Command {
    static description = ` Create an empty Conference within the specified account.`

    static flags = {
        alias: flags.string({
            char: "a",
            description: "A description for this Conference. Maximum 64 characters.",
            required: false,
        }),
        playBeep: flags.string({
            char: "b",
            description:
                "Controls when a beep is played. Valid values: always, never, entryOnly, exitOnly.",
            required: false,
        }),
        record: flags.string({
            char: "r",
            description: "Setting to true records the entire Conference.",
            required: false,
            options: ["true", "false"],
        }),
        waitUrl: flags.string({
            char: "w",
            description:
                "If specified, a URL for the audio file that provides custom hold music for the Conference when it is in the populated state. Otherwise, FreeClimb uses a system default audio file. This is always fetched using HTTP GET and is fetched just once - when the Conference is created.",
            required: false,
        }),
        statusCallbackUrl: flags.string({
            char: "s",
            description: "This URL is invoked when the status of the Conference changes.",
            required: false,
        }),
        next: flags.boolean({ hidden: true }),
        json: flags.boolean({
            description:
                "Output as structured JSON. Also enabled via FREECLIMB_OUTPUT_FORMAT=json env var.",
            default: false,
        }),
        fields: flags.string({
            description:
                "Comma-separated list of fields to include in the response. Limits output to protect context windows when used by agents.",
        }),
        "dry-run": flags.boolean({
            description:
                "Validate the request without executing it. Shows what would be sent to the API.",
            default: false,
        }),
        help: flags.help({ char: "h" }),
    }

    async run() {
        const out = new Output(this)
        const { flags } = (() => {
            try {
                return this.parse(conferencesCreate)
            } catch (error) {
                const err = new Errors.ParseError(error)
                this.error(err.message, { exit: err.code })
            }
        })()
        const outputFormat = getOutputFormat(flags.json)
        if (flags.alias) {
            rejectControlChars(flags.alias, "alias")
        }
        if (flags.playBeep) {
            rejectControlChars(flags.playBeep, "playBeep")
        }
        if (flags.waitUrl) {
            rejectControlChars(flags.waitUrl, "waitUrl")
        }
        if (flags.statusCallbackUrl) {
            rejectControlChars(flags.statusCallbackUrl, "statusCallbackUrl")
        }
        if (flags["dry-run"]) {
            const dryRunOutput = {
                dryRun: true,
                method: "POST",
                endpoint: `Conferences`,
                body: {
                    alias: flags.alias,
                    playBeep: flags.playBeep,
                    record:
                        typeof flags.record === "undefined" ? undefined : flags.record === "true",
                    waitUrl: flags.waitUrl,
                    statusCallbackUrl: flags.statusCallbackUrl,
                },
            }
            if (outputFormat === "json") {
                out.out(JSON.stringify(dryRunOutput, null, 2))
            } else {
                out.out(chalk.yellow("DRY RUN - No API call will be made"))
                out.out(JSON.stringify(dryRunOutput, null, 2))
            }
            return
        }
        const fcApi = new FreeClimbApi(`Conferences`, true, this)
        const formatOutput = (data: any) => {
            const outputData = flags.fields
                ? filterFieldsDeep(
                      data,
                      flags.fields.split(",").map((f: string) => f.trim())
                  )
                : data
            if (outputFormat === "json") {
                return JSON.stringify(wrapJsonOutput(outputData), null, 2)
            }
            const formatter = getFormatterForTopic("conferences", "create")
            return formatter ? formatter(outputData) : JSON.stringify(outputData, null, 2)
        }
        const normalResponse = (response: FreeClimbResponse) => {
            if (response.status === 204) {
                if (outputFormat === "json") {
                    out.out(
                        JSON.stringify(
                            wrapJsonOutput(null, { command: "conferences:create" }),
                            null,
                            2
                        )
                    )
                } else {
                    out.out(
                        chalk.green(
                            "Received a success code from FreeClimb. There is no further output."
                        )
                    )
                }
            } else if (response.data) {
                out.out(formatOutput(response.data))
            } else {
                throw new Errors.UndefinedResponseError()
            }
        }
        if (flags.next) {
            const error = new Errors.NoNextPage()
            this.error(error.message, { exit: error.code })
        }

        // flags.record === "true" sets record to the boolean representation of the flag
        const record = typeof flags.record === "undefined" ? undefined : flags.record === "true"

        await fcApi.apiCall(
            "POST",
            {
                data: {
                    alias: flags.alias,
                    playBeep: flags.playBeep,
                    record: record,
                    waitUrl: flags.waitUrl,
                    statusCallbackUrl: flags.statusCallbackUrl,
                },
            },
            normalResponse
        )
    }
}
