/* WARNING: This file is automatically generated. Please edit the files in the /generation/commands directory. */
import { Command, Flags, Args } from "@oclif/core"
import chalk from "chalk"
import { Output } from "../../output.js"
import { FreeClimbApi, FreeClimbResponse } from "../../freeclimb.js"
import * as Errors from "../../errors.js"

export class conferencesUpdate extends Command {
    static description = ` Update the properties of the specified conference.`

    static flags = {
        alias: Flags.string({
            char: "a",
            description: "Description for this conference. Maximum 64 characters.",
            required: false,
        }),
        playBeep: Flags.string({
            char: "b",
            description:
                "Controls when a beep is played. Valid values: always, never, entryOnly, exitOnly.",
            required: false,
        }),
        status: Flags.string({
            char: "S",
            description: "New status of the conference. Valid values: empty or terminated.",
            required: false,
        }),
        next: Flags.boolean({ hidden: true }),
    }

    static args = {
        conferenceId: Args.string({
            description: "String that uniquely identifies this conference resource.",
            required: true,
        }),
    }

    async run() {
        const out = new Output(this)
        const { args, flags } = await this.parse(conferencesUpdate)
        const fcApi = new FreeClimbApi(`Conferences/${args.conferenceId}`, true, this)
        const normalResponse = (response: FreeClimbResponse) => {
            if (response.status === 204) {
                out.out(
                    chalk.green(
                        "Received a success code from FreeClimb. There is no further output.",
                    ),
                )
            } else if (response.data) {
                out.out(JSON.stringify(response.data, null, 2))
            } else {
                throw new Errors.UndefinedResponseError()
            }
        }
        if (flags.next) {
            const error = new Errors.NoNextPage()
            this.error(error.message, { exit: error.code })
        }
        if (Object.entries(flags).length === 0) {
            this.warn(
                chalk.yellow(
                    "Nothing Has Been Updated: Please enter a parameter to update ('freeclimb conferences:update -h' for a list of parameters to be updated)",
                ),
            )
        }

        await fcApi.apiCall(
            "POST",
            {
                data: {
                    alias: flags.alias,
                    playBeep: flags.playBeep,
                    status: flags.status,
                },
            },
            normalResponse,
        )
    }
}
