/* WARNING: This file is automatically generated. Please edit the files in the /generation/commands directory. */
import { Command, Flags, Args } from "@oclif/core"
import chalk from "chalk"
import { Output } from "../../output.js"
import { FreeClimbApi, FreeClimbResponse } from "../../freeclimb.js"
import * as Errors from "../../errors.js"

export class recordingsDelete extends Command {
    static description = ` Delete the specified recording. Both the audio file and the resource metadata are deleted.`

    static flags = {
        next: Flags.boolean({ hidden: true }),
    }

    static args = {
        recordingId: Args.string({
            description: "String that uniquely identifies this recording resource.",
            required: true,
        }),
    }

    async run() {
        const out = new Output(this)
        const { args, flags } = await this.parse(recordingsDelete)
        const fcApi = new FreeClimbApi(`Recordings/${args.recordingId}`, true, this)
        const normalResponse = (response: FreeClimbResponse) => {
            if (response.status === 204) {
                out.out(
                    chalk.green(
                        "Received a success code from FreeClimb. There is no further output.",
                    ),
                )
            } else if (response.data) {
                out.out(JSON.stringify(response.data, null, 2))
            } else {
                throw new Errors.UndefinedResponseError()
            }
        }
        if (flags.next) {
            const error = new Errors.NoNextPage()
            this.error(error.message, { exit: error.code })
        }

        await fcApi.apiCall("DELETE", {}, normalResponse)
    }
}
