/* WARNING: This file is automatically generated. Please edit the files in the /generation/commands directory. */
import { Args, Command, Flags } from "@oclif/core"
import chalk from "chalk"
import { Output } from '../../output'
import { FreeClimbApi, FreeClimbResponse } from '../../freeclimb'
import * as Errors from '../../errors'
import { wrapJsonOutput, getFormatterForTopic } from '../../ui/format'
import { getOutputFormat } from '../../agent-config'
import { extractQuietIds, filterFieldsDeep, rejectControlChars, validateResourceId } from '../../validation'

export class recordingsDownload extends Command {
    static description = ` Download a Recording. Authentication is required to download a Recording, as with any other request made to the REST API.`
    static examples = [
        "<%= config.bin %> recordings:download RE1234567890abcdef",
        "<%= config.bin %> recordings:download RE1234567890abcdef --json",
    ]
    static flags = {
		next: Flags.boolean({hidden: true}),
		json: Flags.boolean({description: 'Output as JSON. Auto-enabled when stdout is not a TTY or FREECLIMB_OUTPUT_FORMAT=json is set.', default: false}),
		quiet: Flags.boolean({description: 'Output only resource IDs, one per line. Useful for piping into other commands.', default: false}),
		fields: Flags.string({description: 'Comma-separated list of fields to include in the response. Limits output to protect context windows when used by agents.'}),
		help: Flags.help({char: 'h'}),
	}
    
	static args = {
		recordingId: Args.string({description: "String that uniquely identifies this recording resource.", required: true}),
	}

    async run() {
        const out = new Output(this)
        const {args, flags} = await this.parse(recordingsDownload)
        const outputFormat = getOutputFormat(flags.json)
        validateResourceId(args.recordingId, "recordingId")
        
        const fcApi = new FreeClimbApi(`Recordings/${args.recordingId}/Download`, true, this)
        const formatOutput = (data: any) => {
            const outputData = flags.fields ? filterFieldsDeep(data, flags.fields.split(",").map((f: string) => f.trim())) : data
            if (outputFormat === "json") {
                return JSON.stringify(wrapJsonOutput(outputData), null, 2)
            }
            const formatter = getFormatterForTopic("recordings", "download")
            return formatter ? formatter(outputData) : JSON.stringify(outputData, null, 2)
        }
        const normalResponse = (response: FreeClimbResponse) => {
            if (response.status === 204) {
                if (flags.quiet) { return }
                if (outputFormat === "json") {
                    out.out(JSON.stringify(wrapJsonOutput(null, { command: "recordings:download" }), null, 2))
                } else {
                    out.out(chalk.green("Received a success code from FreeClimb. There is no further output."))
                }
            } else if (response.data) {
                if (flags.quiet) {
                    const ids = extractQuietIds(response.data, "recordingId")
                    if (ids) { out.out(ids) }
                    return
                }
                out.out(formatOutput(response.data))
            } else { throw new Errors.UndefinedResponseError() }
        }
        if(flags.next) {
            
                const error = new Errors.NoNextPage();
                this.error(error.message, { exit: error.code});
            
        }
        
        
        
        await fcApi.apiCall("GET", {}, normalResponse)
    
    }
}
