/* WARNING: This file is automatically generated. Please edit the files in the /generation/commands directory. */
import { Command, Flags } from "@oclif/core"
import chalk from "chalk"
import { Output } from '../../output'
import { FreeClimbApi, FreeClimbResponse } from '../../freeclimb'
import * as Errors from '../../errors'
import { wrapJsonOutput, getFormatterForTopic } from '../../ui/format'
import { getOutputFormat } from '../../agent-config'
import { filterFieldsDeep, rejectControlChars, validateResourceId } from '../../validation'

export class recordingsList extends Command {
    static description = ` Retrieve a list of metadata for recordings associated with the specified account, sorted from latest created to oldest.`
    
    static flags = {
		callId: Flags.string({            char: "c",            description: "Show only Recordings made during the Call with this ID.",             required: false,             }),
		conferenceId: Flags.string({            char: "C",            description: "Show only Recordings made during the conference with this ID.",             required: false,             }),
		dateCreated: Flags.string({            char: "d",            description: "Only show Recordings created on this date, formatted as YYYY-MM-DD.",             required: false,             }),
		next: Flags.boolean({char: 'n', description: 'Displays the next page of output.'}),
		json: Flags.boolean({description: 'Output as JSON. Auto-enabled when stdout is not a TTY or FREECLIMB_OUTPUT_FORMAT=json is set.', default: false}),
		fields: Flags.string({description: 'Comma-separated list of fields to include in the response. Limits output to protect context windows when used by agents.'}),
		help: Flags.help({char: 'h'}),
	}
    
    async run() {
        const out = new Output(this)
        const {flags} = (() => {
            try {
                return this.parse(recordingsList)
            } catch(error) {
                const err = new Errors.ParseError(error)
                this.error(err.message, { exit: err.code })
            }
        })()
        const outputFormat = getOutputFormat(flags.json)
        if (flags.callId) { validateResourceId(flags.callId, "callId") }
        if (flags.conferenceId) { validateResourceId(flags.conferenceId, "conferenceId") }
        if (flags.dateCreated) { rejectControlChars(flags.dateCreated, "dateCreated") }
        
        const fcApi = new FreeClimbApi(`Recordings`, true, this)
        const formatOutput = (data: any) => {
            const outputData = flags.fields ? filterFieldsDeep(data, flags.fields.split(",").map((f: string) => f.trim())) : data
            if (outputFormat === "json") {
                return JSON.stringify(wrapJsonOutput(outputData), null, 2)
            }
            const formatter = getFormatterForTopic("recordings", "list")
            return formatter ? formatter(outputData) : JSON.stringify(outputData, null, 2)
        }
        const normalResponse = (response: FreeClimbResponse) => {
            if (response.status === 204) {
                if (outputFormat === "json") {
                    out.out(JSON.stringify(wrapJsonOutput(null, { command: "recordings:list" }), null, 2))
                } else {
                    out.out(chalk.green("Received a success code from FreeClimb. There is no further output."))
                }
            } else if (response.data) {
                out.out(formatOutput(response.data))
            } else { throw new Errors.UndefinedResponseError() }
        }
        const nextResponse = (response: FreeClimbResponse) => {
            if (response.data) {
                out.out(formatOutput(response.data))
            } else { throw new Errors.UndefinedResponseError() }
            if(out.next === null) {
                out.out("== You are on the last page of output. ==")
            }
        }
        
        if(flags.next) {
            if(out.next === undefined || out.next === "freeclimbUnnamedTest") {
                const error = new Errors.NoNextPage();
                this.error(error.message, { exit: error.code});
            
            }
            else {
                await fcApi.apiCall("GET", { params: {cursor: out.next} }, nextResponse)
            }
            return
        }
        
        await fcApi.apiCall("GET", {params: {
				callId: flags.callId,
				conferenceId: flags.conferenceId,
				dateCreated: flags.dateCreated,
			},
		}, normalResponse)
    
    }
}
