/* WARNING: This file is automatically generated. Please edit the files in the /generation/commands directory. */
import { Args, Command, Flags } from "@oclif/core"
import chalk from "chalk"
import { Output } from '../../output'
import { FreeClimbApi, FreeClimbResponse } from '../../freeclimb'
import * as Errors from '../../errors'
import { wrapJsonOutput, getFormatterForTopic } from '../../ui/format'
import { getOutputFormat } from '../../agent-config'
import { filterFieldsDeep, rejectControlChars, validateResourceId } from '../../validation'

export class incomingNumbersDelete extends Command {
    static description = ` Delete the specified incoming number. FreeClimb will no longer answer calls to the number.`
    
    static flags = {
		next: Flags.boolean({hidden: true}),
		json: Flags.boolean({description: 'Output as JSON. Auto-enabled when stdout is not a TTY or FREECLIMB_OUTPUT_FORMAT=json is set.', default: false}),
		fields: Flags.string({description: 'Comma-separated list of fields to include in the response. Limits output to protect context windows when used by agents.'}),
		"dry-run": Flags.boolean({description: 'Validate the request without executing it. Shows what would be sent to the API.', default: false}),
		help: Flags.help({char: 'h'}),
	}
    
	static args = {
		phoneNumberId: Args.string({description: "String that uniquely identifies this phone number resource.", required: false}),
	}

    async run() {
        const out = new Output(this)
        const {args, flags} = await this.parse(incomingNumbersDelete)
        const outputFormat = getOutputFormat(flags.json)
        validateResourceId(args.phoneNumberId, "phoneNumberId")
        if (flags["dry-run"]) {
            const dryRunOutput = {
                dryRun: true,
                method: "DELETE",
                endpoint: `IncomingPhoneNumbers/${args.phoneNumberId}`,
                
            }
            if (outputFormat === "json") {
                out.out(JSON.stringify(dryRunOutput, null, 2))
            } else {
                out.out(chalk.yellow("DRY RUN - No API call will be made"))
                out.out(JSON.stringify(dryRunOutput, null, 2))
            }
            return
        }
        const fcApi = new FreeClimbApi(`IncomingPhoneNumbers/${args.phoneNumberId}`, true, this)
        const formatOutput = (data: any) => {
            const outputData = flags.fields ? filterFieldsDeep(data, flags.fields.split(",").map((f: string) => f.trim())) : data
            if (outputFormat === "json") {
                return JSON.stringify(wrapJsonOutput(outputData), null, 2)
            }
            const formatter = getFormatterForTopic("incoming-numbers", "delete")
            return formatter ? formatter(outputData) : JSON.stringify(outputData, null, 2)
        }
        const normalResponse = (response: FreeClimbResponse) => {
            if (response.status === 204) {
                if (outputFormat === "json") {
                    out.out(JSON.stringify(wrapJsonOutput(null, { command: "incoming-numbers:delete" }), null, 2))
                } else {
                    out.out(chalk.green("Received a success code from FreeClimb. There is no further output."))
                }
            } else if (response.data) {
                out.out(formatOutput(response.data))
            } else { throw new Errors.UndefinedResponseError() }
        }
        if(flags.next) {
            
                const error = new Errors.NoNextPage();
                this.error(error.message, { exit: error.code});
            
        }
        
        await fcApi.apiCall("DELETE", {}, normalResponse)
    
    }
}
