/* WARNING: This file is automatically generated. Please edit the files in the /generation/commands directory. */
import { Args, Command, Flags } from "@oclif/core"
import chalk from "chalk"
import { Output } from '../../output'
import { FreeClimbApi, FreeClimbResponse } from '../../freeclimb'
import * as Errors from '../../errors'
import { wrapJsonOutput, getFormatterForTopic } from '../../ui/format'
import { getOutputFormat } from '../../agent-config'
import { filterFieldsDeep, rejectControlChars, validateResourceId } from '../../validation'

export class incomingNumbersList extends Command {
    static description = ` Retrieve a list of Incoming Phone Numbers associated with the specified account, sorted from newest to oldest.`
    
    static flags = {
		phoneNumber: Flags.string({            char: "p",            description: "Only show incoming phone number resources that match this PCRE-compatible regular expression.",             required: false,             }),
		alias: Flags.string({            char: "a",            description: "Only show incoming phone numbers with aliases that exactly match this value.",             required: false,             }),
		applicationId: Flags.string({            char: "A",            description: "Filters numbers by application ID.",             required: false,             }),
		hasApplication: Flags.string({            char: "h",            description: "Filters numbers by whether or not they are associated with an application.",             required: false,             options: ["true", "false"]}),
		country: Flags.string({            char: "C",            description: "Filters numbers by two character ISO country code.",             required: false,             }),
		region: Flags.string({            char: "r",            description: "Filters numbers by two letter state abbreviation. This flag is only available for US numbers.",             required: false,             }),
		smsEnabled: Flags.string({            char: "E",            description: "Filters numbers based on SMS capability.",             required: false,             options: ["true", "false"]}),
		voiceEnabled: Flags.string({            char: "o",            description: "Filters numbers based on voice capability.",             required: false,             options: ["true", "false"]}),
		next: Flags.boolean({char: 'n', description: 'Displays the next page of output.'}),
		json: Flags.boolean({description: 'Output as structured JSON. Also enabled via FREECLIMB_OUTPUT_FORMAT=json env var.', default: false}),
		fields: Flags.string({description: 'Comma-separated list of fields to include in the response. Limits output to protect context windows when used by agents.'}),
		help: Flags.help({char: 'h'}),
	}
    
    async run() {
        const out = new Output(this)
        const {flags} = await this.parse(incomingNumbersList)
        const outputFormat = getOutputFormat(flags.json)
        if (flags.applicationId) { validateResourceId(flags.applicationId, "applicationId") }
        if (flags.phoneNumber) { rejectControlChars(flags.phoneNumber, "phoneNumber") }
        if (flags.alias) { rejectControlChars(flags.alias, "alias") }
        if (flags.country) { rejectControlChars(flags.country, "country") }
        if (flags.region) { rejectControlChars(flags.region, "region") }
        
        const fcApi = new FreeClimbApi(`IncomingPhoneNumbers`, true, this)
        const formatOutput = (data: any) => {
            const outputData = flags.fields ? filterFieldsDeep(data, flags.fields.split(",").map((f: string) => f.trim())) : data
            if (outputFormat === "json") {
                return JSON.stringify(wrapJsonOutput(outputData), null, 2)
            }
            const formatter = getFormatterForTopic("incoming-numbers", "list")
            return formatter ? formatter(outputData) : JSON.stringify(outputData, null, 2)
        }
        const normalResponse = (response: FreeClimbResponse) => {
            if (response.status === 204) {
                if (outputFormat === "json") {
                    out.out(JSON.stringify(wrapJsonOutput(null, { command: "incoming-numbers:list" }), null, 2))
                } else {
                    out.out(chalk.green("Received a success code from FreeClimb. There is no further output."))
                }
            } else if (response.data) {
                out.out(formatOutput(response.data))
            } else { throw new Errors.UndefinedResponseError() }
        }
        const nextResponse = (response: FreeClimbResponse) => {
            if (response.data) {
                out.out(formatOutput(response.data))
            } else { throw new Errors.UndefinedResponseError() }
            if(out.next === null) {
                out.out("== You are on the last page of output. ==")
            }
        }
        
        if(flags.next) {
            if(out.next === undefined || out.next === "freeclimbUnnamedTest") {
                const error = new Errors.NoNextPage();
                this.error(error.message, { exit: error.code});
            
            }
            else {
                await fcApi.apiCall("GET", { params: {cursor: out.next} }, nextResponse)
            }
            return
        }
        
        // flags.hasApplication === "true" sets hasApplication to the boolean representation of the flag
		const hasApplication = typeof flags.hasApplication  === "undefined" ? undefined : flags.hasApplication === "true"
// flags.smsEnabled === "true" sets smsEnabled to the boolean representation of the flag
		const smsEnabled = typeof flags.smsEnabled  === "undefined" ? undefined : flags.smsEnabled === "true"
// flags.voiceEnabled === "true" sets voiceEnabled to the boolean representation of the flag
		const voiceEnabled = typeof flags.voiceEnabled  === "undefined" ? undefined : flags.voiceEnabled === "true"
        
        await fcApi.apiCall("GET", {params: {
				phoneNumber: flags.phoneNumber,
				alias: flags.alias,
				applicationId: flags.applicationId,
				hasApplication: hasApplication,
				country: flags.country,
				region: flags.region,
				smsEnabled: smsEnabled,
				voiceEnabled: voiceEnabled,
			},
		}, normalResponse)
    
    }
}
