/* WARNING: This file is automatically generated. Please edit the files in the /generation/commands directory. */
import { Command, Flags } from "@oclif/core"
import chalk from "chalk"
import { Output } from '../../output'
import { FreeClimbApi, FreeClimbResponse } from '../../freeclimb'
import * as Errors from '../../errors'
import { wrapJsonOutput, getFormatterForTopic } from '../../ui/format'
import { getOutputFormat } from '../../agent-config'
import { filterFieldsDeep, rejectControlChars, validateResourceId } from '../../validation'

export class accountsGet extends Command {
    static description = ` Retrieve a representation of the specified Account.`
    
    static flags = {
		next: Flags.boolean({hidden: true}),
		json: Flags.boolean({description: 'Output as JSON. Auto-enabled when stdout is not a TTY or FREECLIMB_OUTPUT_FORMAT=json is set.', default: false}),
		fields: Flags.string({description: 'Comma-separated list of fields to include in the response. Limits output to protect context windows when used by agents.'}),
		help: Flags.help({char: 'h'}),
	}
    
    async run() {
        const out = new Output(this)
        const {flags} = (() => {
            try {
                return this.parse(accountsGet)
            } catch(error) {
                const err = new Errors.ParseError(error)
                this.error(err.message, { exit: err.code })
            }
        })()
        const outputFormat = getOutputFormat(flags.json)
        
        const fcApi = new FreeClimbApi(``, true, this)
        const formatOutput = (data: any) => {
            const outputData = flags.fields ? filterFieldsDeep(data, flags.fields.split(",").map((f: string) => f.trim())) : data
            if (outputFormat === "json") {
                return JSON.stringify(wrapJsonOutput(outputData), null, 2)
            }
            const formatter = getFormatterForTopic("accounts", "get")
            return formatter ? formatter(outputData) : JSON.stringify(outputData, null, 2)
        }
        const normalResponse = (response: FreeClimbResponse) => {
            if (response.status === 204) {
                if (outputFormat === "json") {
                    out.out(JSON.stringify(wrapJsonOutput(null, { command: "accounts:get" }), null, 2))
                } else {
                    out.out(chalk.green("Received a success code from FreeClimb. There is no further output."))
                }
            } else if (response.data) {
                out.out(formatOutput(response.data))
            } else { throw new Errors.UndefinedResponseError() }
        }
        if(flags.next) {
            
                const error = new Errors.NoNextPage();
                this.error(error.message, { exit: error.code});
            
        }
        
        await fcApi.apiCall("GET", {}, normalResponse)
    
    }
}
