/* WARNING: This file is automatically generated. Please edit the files in the /generation/commands directory. */
import { Command, Flags } from "@oclif/core"
import chalk from "chalk"
import { Output } from "../../output.js"
import { FreeClimbApi, FreeClimbResponse } from "../../freeclimb.js"
import * as Errors from "../../errors.js"

export class accountsGet extends Command {
    static description = ` Retrieve a representation of the specified Account.`

    static flags = {
        next: Flags.boolean({ hidden: true }),
    }

    async run() {
        const out = new Output(this)
        const { flags } = await this.parse(accountsGet)
        const fcApi = new FreeClimbApi(``, true, this)
        const normalResponse = (response: FreeClimbResponse) => {
            if (response.status === 204) {
                out.out(
                    chalk.green(
                        "Received a success code from FreeClimb. There is no further output.",
                    ),
                )
            } else if (response.data) {
                out.out(JSON.stringify(response.data, null, 2))
            } else {
                throw new Errors.UndefinedResponseError()
            }
        }
        if (flags.next) {
            const error = new Errors.NoNextPage()
            this.error(error.message, { exit: error.code })
        }

        await fcApi.apiCall("GET", {}, normalResponse)
    }
}
