/* WARNING: This file is automatically generated. Please edit the files in the /generation/commands directory. */
import { Args, Command, Flags } from "@oclif/core"
import chalk from "chalk"
import { Output } from '../../output.js'
import { FreeClimbApi, FreeClimbResponse } from '../../freeclimb.js'
import * as Errors from '../../errors.js'
import { wrapJsonOutput } from '../../ui/format.js'
import { getOutputFormat } from '../../agent-config.js'
import { extractQuietIds, filterFieldsDeep, rejectControlChars, validateResourceId } from '../../validation.js'

export class accountsManage extends Command {
    static description = `This command allows you to manage an account.`
    static examples = [
        "<%= config.bin %> accounts:manage --alias \"My Account\"",
        "<%= config.bin %> accounts:manage --alias \"My Account\" --json",
        "<%= config.bin %> accounts:manage --dry-run --alias \"My Account\"",
    ]
    static flags = {
		alias: Flags.string({            char: "a",            description: "Description for this account.",             required: false,             }),
		label: Flags.string({            char: "l",            description: "Group to which this account belongs.",             required: false,             }),
		next: Flags.boolean({hidden: true}),
		json: Flags.boolean({description: 'Output as JSON. Auto-enabled when stdout is not a TTY or FREECLIMB_OUTPUT_FORMAT=json is set.', default: false}),
		quiet: Flags.boolean({description: 'Output only resource IDs, one per line. Useful for piping into other commands.', default: false}),
		fields: Flags.string({description: 'Comma-separated list of fields to include in the response. Limits output to protect context windows when used by agents.'}),
		"dry-run": Flags.boolean({description: 'Validate the request without executing it. Shows what would be sent to the API.', default: false}),
		help: Flags.help({char: 'h'}),
	}
    
    async run() {
        const out = new Output(this)
        const {flags} = await this.parse(accountsManage)
        const outputFormat = getOutputFormat(flags.json)
        if (flags.alias) { rejectControlChars(flags.alias, "alias") }
        if (flags.label) { rejectControlChars(flags.label, "label") }
        if (flags["dry-run"]) {
            const dryRunOutput = {
                dryRun: true,
                method: "POST",
                endpoint: ``,
                body: {
                    alias: flags.alias,
                    label: flags.label
                },
                
            }
            if (outputFormat === "json") {
                out.out(JSON.stringify(dryRunOutput, null, 2))
            } else {
                out.out(chalk.yellow("DRY RUN - No API call will be made"))
                out.out(JSON.stringify(dryRunOutput, null, 2))
            }
            return
        }
        const fcApi = new FreeClimbApi(``, true, this)
        const formatOutput = (data: any) => {
            const outputData = flags.fields ? filterFieldsDeep(data, flags.fields.split(",").map((f: string) => f.trim())) : data
            if (outputFormat === "json") {
                return JSON.stringify(wrapJsonOutput(outputData), null, 2)
            }
            out.render(outputData, { topic: "accounts", command: "manage" })
            return null
        }
        const normalResponse = (response: FreeClimbResponse) => {
            if (response.status === 204) {
                if (flags.quiet) { return }
                if (outputFormat === "json") {
                    out.out(JSON.stringify(wrapJsonOutput(null, { command: "accounts:manage" }), null, 2))
                } else {
                    out.render(null, { topic: "accounts", command: "manage" })
                }
            } else if (response.data) {
                if (flags.quiet) {
                    const ids = extractQuietIds(response.data, "accountId")
                    if (ids) { out.out(ids) }
                    return
                }
                const result = formatOutput(response.data)
                if (result !== null) { out.out(result) }
            } else { throw new Errors.UndefinedResponseError() }
        }
        if(flags.next) {
            
                const error = new Errors.NoNextPage();
                this.error(error.message, { exit: error.code});
            
        }
        if(Object.entries(flags).length === 0) { this.warn(chalk.yellow("Nothing Has Been Updated: Please enter a parameter to update ('freeclimb accounts:manage -h' for a list of parameters to be updated)"))}
        
        
        await fcApi.apiCall("POST", {data: {
				alias: flags.alias,
				label: flags.label,
			},
		}, normalResponse)
    
    }
}
